// Functional Programming intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "Functional Programming", turns: [
  // --- Purity and effects ---
  { topic: "Pure functions",
    good: "A pure function returns the same output for the same inputs and has no observable effect on anything outside itself.",
    neutral: "Pure functions tend to be short, so they often read top to bottom without a reader jumping to other parts of the program.",
    bad: "A function counts as pure as long as it leaves its arguments alone; bumping a module-level counter along the way is allowed." },
  { topic: "Side effects",
    good: "Writing a file, sending a request, mutating shared state and printing a line are all side effects that a caller can observe.",
    neutral: "Most useful programs have side effects somewhere; a program that changes nothing outside itself can't show you anything.",
    bad: "Side effects matter for data on disk or over the network. Updating an object in memory is internal and has nothing to track." },
  { topic: "Hidden inputs",
    good: "Reading the current time or a random number is a hidden input. Pass the time or a seed in as a parameter to keep a function pure.",
    neutral: "Functions that read the clock or a random source are hard to pin down in a test, since the value differs between runs.",
    bad: "Asking the system clock for the time only reads a value. A function that does that writes nothing anywhere and stays pure." },
  { topic: "Local mutation",
    good: "A function can mutate a local array it created and still be pure from the outside, as long as no other code ever sees that array.",
    neutral: "Some functions build their result with a loop and a local variable, while others use recursion or combine smaller results.",
    bad: "Reassigning a variable inside a function makes it impure, even for a loop counter that callers have no way to observe." },
  { topic: "Exceptions and purity",
    good: "Throwing an exception is an effect on control flow. Returning an error value instead keeps the failure visible in the result type.",
    neutral: "Error handling looks different across codebases. Some throw, some return error codes, and some wrap each result in a small value.",
    bad: "Exceptions have no bearing on purity; a function that throws on bad input is as pure as one that returns a normal value." },
  // --- Referential transparency and reasoning ---
  { topic: "Referential transparency",
    good: "If you can swap an expression for its value anywhere without changing what the program does, it's referentially transparent.",
    neutral: "Referential transparency and purity go together closely, and code written with one in mind usually has the other as well.",
    bad: "Referential transparency means a function's source is visible to callers, so readers can follow each reference it makes." },
  { topic: "Equational reasoning",
    good: "With pure code you can reason like algebra: replace a call with its definition, simplify, and trust the result still holds.",
    neutral: "Equational reasoning feels familiar to anyone who did algebra at school, and it reads most easily with small functions.",
    bad: "Substituting a call with its result matters to the optimizer alone. For a human reader it adds no insight into the code." },
  { topic: "Evaluation order",
    good: "When expressions have no side effects, the order they run in stops mattering, so a compiler or runtime is free to reorder them.",
    neutral: "Languages differ on whether arguments are evaluated left to right, right to left, or in an order the rules leave open.",
    bad: "Pure code has to run in the exact order it's written. Reorder two calls to a pure function and they can return different values." },
  { topic: "Determinism and testing",
    good: "Pure functions are easy to test. You need no mocks and no setup or teardown, just inputs and an expected output.",
    neutral: "Write tests for the edge cases of a function: empty input, a single element, and a value at the boundary of a range.",
    bad: "Pure functions need more mocking than impure ones, because each collaborator they call has to be faked to keep them pure." },
  { topic: "Idempotence vs purity",
    good: "Idempotent means doing it twice equals doing it once. Deleting a record by ID is idempotent, yet it's still a side effect.",
    neutral: "Idempotence matters a great deal for retries, such as resending a request after a timeout without knowing whether the original landed.",
    bad: "If repeating a call gives the same result as making it once, the call is pure and can't be producing side effects." },
  // --- Immutability ---
  { topic: "Immutability",
    good: "With immutable data an update builds a new value and the old one stays intact, so code holding the old value sees no change.",
    neutral: "Immutable values can't change after they're created, and updating one means making a new value with the different fields.",
    bad: "Immutability mainly guards against typos: its real payoff is the compiler catching an accidental assignment to the wrong variable." },
  { topic: "Constant bindings",
    good: "A constant binding stops you reassigning the name, yet the object it points to can still change unless it's immutable.",
    neutral: "Mark a name as constant when it won't be reassigned. Readers see the intent, and the compiler can sometimes check it.",
    bad: "Declaring a name as a constant freezes the whole object it refers to, including lists or maps nested deep inside of it." },
  { topic: "Aliasing",
    good: "Two parts of a program holding one mutable object can change it under each other; immutable data removes that bug class.",
    neutral: "Aliasing happens whenever two variables refer to one object, which is common in programs that pass objects by reference.",
    bad: "Use defensive copies on each call and return. Copying mutable objects everywhere gives you the same benefits as immutable data." },
  { topic: "Immutability and threads",
    good: "Immutable values can be shared across threads without locks, since no thread can change them. Races need shared mutable state.",
    neutral: "Concurrent programs involve threads, queues, and locks, and debugging them tends to be much harder than debugging a single thread.",
    bad: "Immutable data still needs a lock for reads: two threads reading one value at the same moment can see a torn or partial value." },
  // --- Persistent data structures ---
  { topic: "Persistent data structures",
    good: "A persistent data structure keeps old versions usable after an update. Each update returns a new version and leaves the old.",
    neutral: "Persistent collections are often trees under the hood, though they offer the usual list, map, and set operations on top.",
    bad: "Persistent data structures are the ones saved to disk to survive a restart, as opposed to collections held only in memory." },
  { topic: "Structural sharing",
    good: "Structural sharing makes immutable updates cheap. The new version reuses the unchanged parts of the old one rather than copying.",
    neutral: "Two versions of a persistent tree can point at the same subtrees, and the garbage collector frees a subtree once no version refers to it.",
    bad: "Each update to an immutable collection copies the entire collection; adding one item to a list of a million costs a million copies." },
  { topic: "Cost of persistent updates",
    good: "Persistent maps and vectors usually cost a small log factor per update over mutable ones, plus extra allocation for new nodes.",
    neutral: "Persistent collection speed depends on the implementation, and at small sizes the gap from mutable ones is hard to notice.",
    bad: "Persistent collections beat mutable arrays at every operation, because shared nodes mean less memory traffic overall for the program." },
  // --- Functions as values ---
  { topic: "First-class functions",
    good: "First-class functions are values. You can store them in variables, put them in lists, pass them as arguments, and return them.",
    neutral: "Functions as values show up in sort comparators, event handlers, and callbacks, and most modern languages support them somehow.",
    bad: "A first-class function is one defined at the top level of a file rather than nested inside another function, class, or block." },
  { topic: "Higher-order functions",
    good: "Higher-order functions take a function as an argument or return one, which lets you write the loop once and vary the step.",
    neutral: "Higher-order functions show up a lot in list processing, where a single call often stands in for a hand-written loop.",
    bad: "Higher-order functions cost a full function call per element that compilers can't inline, so a plain loop beats them by a wide margin." },
  { topic: "Functions in data",
    good: "A map from command names to handler functions can replace a long if-else chain: look up the name, then call what you find.",
    neutral: "Tables of functions keyed by name can be built at startup and can grow as other parts of the code register new entries.",
    bad: "Storing a function in a map or a list keeps only a reference to its name, and you have to look the function up again to call it." },
  { topic: "Closures",
    good: "A closure bundles a function with the variables it captured where it was defined; they stay alive as long as it does.",
    neutral: "Closures appear every time a function defined inside another function refers to names from the outer one in its body.",
    bad: "A closure loses its captured variables once the outer function returns, and calling it after that point reads stale or empty values." },
  { topic: "Closures over mutable state",
    good: "Closures that capture a mutable variable share it. A counter closure updates the same cell on each call, which makes it impure.",
    neutral: "A counter that adds one on each call is a small closure, and it is easy to write by hand in a few short lines of almost any language.",
    bad: "Closures are pure by construction; captured variables are out of reach of other code, so a closure has no way to hold state." },
  // --- Style ---
  { topic: "Expressions vs statements",
    good: "An expression produces a value and a statement does something; when if and match are expressions, you can bind their result.",
    neutral: "Expressions and statements look different on the page: statements often end a line, while expressions nest inside one another.",
    bad: "Prefer statements to expressions. Expressions that return values encourage nesting, and nested code is harder to compose." },
  { topic: "Declarative vs imperative",
    good: "Declarative code says what result you want, such as keeping paid orders, while imperative code spells out the steps.",
    neutral: "Keep each function at one level of detail so readers can follow it without switching between high and low level steps.",
    bad: "Declarative code skips work by design: describing the result instead of the steps means the machine executes fewer instructions." },
  { topic: "Anonymous functions",
    good: "An anonymous function is a function value written inline where it's used; naming it adds nothing when it's short and used once.",
    neutral: "Anonymous functions often appear as the argument to a sort, a map, or a filter, and they usually fit on one line of the call.",
    bad: "Anonymous functions can't capture variables from the code around them; only named functions declared up front can do that." }
,
  // --- Map, filter, fold ---
  { topic: "Map",
    good: "Map applies a function to each element and returns a new collection of the same length. The original stays untouched.",
    neutral: "Mapping over a list of prices to add tax gives back a list of taxed prices; there's one result per input, kept in the same order.",
    bad: "Mapping over a list overwrites its elements in place, and the function you hand it receives each slot to update directly." },
  { topic: "Filter",
    good: "Filter keeps the elements whose predicate returns true. The result may be shorter than the input and keeps its order.",
    neutral: "Filtering a list of orders down to the unpaid ones is a typical use, and the predicate there usually checks one field.",
    bad: "Filter can remove matching items from the original list: the predicate decides which elements get deleted from it in place." },
  { topic: "Fold",
    good: "A fold walks a collection carrying an accumulator. Map, filter, sum, and count can each be written as a fold with the right step.",
    neutral: "Folds turn up when totaling numbers or building a lookup table from a list, so the shape soon gets familiar to anyone reading code.",
    bad: "Fold only produces numbers. It sums or multiplies elements; building a list or a map needs a different tool entirely." },
  { topic: "Left vs right fold",
    good: "A left fold groups from the start of the list, a right fold from the end. With subtraction as the step, the two give different answers.",
    neutral: "Left and right folds take the same three ingredients: a step function, an initial value, and the collection to walk over.",
    bad: "Left and right folds always give the same answer. The direction affects speed alone, and right folds may run faster on long lists." },
  { topic: "Fold initial value",
    good: "Reducing with no starting value fails on an empty collection; an initial value, like 0 for a sum, avoids that.",
    neutral: "Initial values for a fold are often zero for sums and one for products, and they go in alongside the step function and the collection.",
    bad: "Leave out the initial value whenever you can. The fold then returns zero for an empty list, whatever the element type is." },
  { topic: "Scan",
    good: "A scan works like a fold that emits every intermediate accumulator, so a running total over daily sales yields one total per day.",
    neutral: "Scans return a sequence rather than a single value; the output is about as long as the input, give or take one element.",
    bad: "A scan typically searches a collection for the first element matching a predicate and stops there, returning that element or nothing." },
  { topic: "flatMap",
    good: "flatMap maps each element to a collection and joins the results into one list, so one input can yield zero, one, or many outputs.",
    neutral: "Using flatMap on a list of customers to get all their orders produces one longer list in place of a list of lists, one per customer.",
    bad: "flatMap flattens nested lists to any depth; a map followed by a flatten removes only a single level of nesting." },
  // --- Composing functions ---
  { topic: "Function composition",
    good: "Composing f with g makes a new function that runs g, then feeds its result to f. Order matters, and g's output must suit f's input.",
    neutral: "Composition joins small functions into bigger ones, and it reads most naturally when each piece takes and returns one value.",
    bad: "Composition order doesn't matter: f after g and g after f give the same function, as long as both accept the same type." },
  { topic: "Pipelines",
    good: "A pipeline lists steps in the order data flows through them, which reads top to bottom where nested calls read inside out.",
    neutral: "Keep each pipeline stage to one job; give stages names that say what they produce, not how they work.",
    bad: "Each stage of a chained pipeline must finish over the whole collection before the next stage starts, even for lazy sequences." },
  { topic: "Combinators vs recursion",
    good: "Prefer a fold or map to hand-written recursion where one fits; the traversal is already correct and the intent plain.",
    neutral: "Write the base case near the top of a recursive function, where a reader looking for how it stops will spot it before anything else.",
    bad: "Hand-written recursion usually beats map and fold for clarity. Library combinators hide the loop from readers." },
  { topic: "Fusing steps",
    good: "Chaining map, filter, and map on eager lists builds a new list per step. Lazy or fused pipelines make one pass instead.",
    neutral: "Long chains of map and filter calls read top to bottom like a recipe, with each line describing one transformation in turn.",
    bad: "Chaining several maps on an eager list walks it just once: the runtime merges the steps, and no intermediate lists get created." },
  // --- Currying and partial application ---
  { topic: "Currying",
    good: "Currying turns a function of several arguments into a chain of one-argument functions, each returning the next until all are supplied.",
    neutral: "Curried functions are written and applied one argument at a time, and some languages curry every function by default.",
    bad: "Currying caches a function's results per argument, which is how it speeds up repeated calls with the same inputs." },
  { topic: "Partial application",
    good: "Partial application fixes some arguments now and returns a function waiting for the rest, handy for building callbacks.",
    neutral: "Partially applying a logging function with a fixed prefix yields a shorter function that callers use for one module's messages.",
    bad: "Partial application usually calls the function at once and fills each missing argument with an empty default value." },
  { topic: "Currying vs partial application",
    good: "Currying reshapes a function, while partial application supplies some of its arguments. A curried function makes partial application trivial.",
    neutral: "Currying and partial application get mixed up in conversation, and both involve supplying a function's arguments in stages.",
    bad: "Currying and partial application are two names for the same thing, and any function that takes two arguments is already curried." },
  { topic: "Point-free style",
    good: "Point-free style composes functions without naming their arguments; short chains read well, and long ones turn cryptic.",
    neutral: "Point-free definitions tend to be shorter than ones with named parameters, and they lean heavily on composition and partial application.",
    bad: "Point-free code often runs faster than the same logic with named arguments. The compiler skips binding parameters to variables." },
  // --- Recursion and the stack ---
  { topic: "Recursion",
    good: "A recursive function needs a base case and a step that moves toward it, like handling a list's head and then its rest.",
    neutral: "Recursion shows up with trees, nested menus, and file directories, because the data there contains smaller copies of itself.",
    bad: "Recursion replaces loops in FP because each recursive call reuses the same stack frame, with no stack growth however deep the calls go." },
  { topic: "Tail calls",
    good: "A tail call is the last thing a function does. Where the runtime eliminates tail calls, tail recursion runs in constant stack space.",
    neutral: "Tail-recursive functions often carry an accumulator parameter that holds the running result as the recursion moves along.",
    bad: "A function counts as tail recursive when the recursive call sits on its final line, even inside an addition like n plus that call." },
  { topic: "Tail call support",
    good: "Plenty of runtimes don't eliminate tail calls, so deep recursion there can overflow; a loop or a trampoline avoids it.",
    neutral: "Stack depth limits differ between runtimes and settings; a recursion a few thousand levels deep may or may not fit, depending on frame size.",
    bad: "Writing a function in tail-recursive form makes the compiler optimize it on every platform. Language specs require it." },
  { topic: "Trampolining",
    good: "With a trampoline, each step returns a final value or a thunk for the next step, and a loop keeps running thunks until a value appears.",
    neutral: "Trampolined code is usually a bit slower than a plain loop, and it appears mostly where stack depth would otherwise be a problem.",
    bad: "A trampoline raises the stack size limit for one function call at a time, which lets deep recursion finish before overflowing." },
  // --- Laziness ---
  { topic: "Lazy evaluation",
    good: "Lazy evaluation computes a value only when something demands it; work that nothing asks for is skipped.",
    neutral: "Lazy values sit unevaluated until needed, and printing or inspecting one in a debugger may force it along the way.",
    bad: "Lazy evaluation usually runs deferred work on a background thread, so the value is ready by the time some code asks for it." },
  { topic: "Effects in lazy sequences",
    good: "Side effects inside a lazy map happen when elements are consumed, not where the map is written, and may happen late or not at all.",
    neutral: "Lazy sequences produce elements on request, and taking ten from the front of one does work for those ten and little else.",
    bad: "Wrapping a lazy sequence in a map forces the whole thing at once, so logging inside the mapped function runs right where you wrote it." },
  { topic: "Infinite streams",
    good: "An infinite stream of, say, all natural numbers is usable when consumers take a bounded prefix. Asking for its length never returns.",
    neutral: "Infinite streams can model clock ticks, user events, or fresh ids, and they're usually defined by a seed and a next step to apply each time.",
    bad: "An infinite stream preallocates memory for its elements up front; the runtime caps it at a fixed size behind the scenes." },
  { topic: "Generators vs lazy lists",
    good: "A generator is a one-shot, stateful iterator: once consumed it's empty. A lazy list keeps forced elements and can be walked again.",
    neutral: "Generators and lazy lists both hand out values on demand, and both let a consumer stop early without computing all the rest.",
    bad: "Generators can be iterated as many times as you like; each pass replays the stored values, so they act as a reusable lazy list." },
  // --- Memoization ---
  { topic: "Memoization",
    good: "Memoization caches results keyed by arguments. It's correct only for pure functions, and the cache grows per distinct input.",
    neutral: "Memoizing the naive recursive Fibonacci function turns it from painfully slow into fast, a quick demo of what caching buys in general.",
    bad: "Memoize any slow function to speed it up, including ones that read the clock or the database; the cache tracks those changes." },
  { topic: "Memo table costs",
    good: "A memo table trades memory for time; without eviction or bounds, memoizing a function with many distinct inputs becomes a leak.",
    neutral: "Memo tables are usually maps from inputs to outputs, and they can live inside a closure or in a separate cache object.",
    bad: "Memoization typically works by compiling the function into a lookup table ahead of time, covering every possible input before it runs." }
,
  // --- Algebraic data types ---
  { topic: "Algebraic data types",
    good: "Algebraic data types build data from two moves: combine fields together, or choose between alternatives. Most domain models need both.",
    neutral: "Code built around algebraic data types tends to contain many small type declarations, each describing one shape of data in the program.",
    bad: "Algebraic data types amount to classes with public fields. The word algebraic refers to the equality and printing the compiler generates." },
  { topic: "Sum types",
    good: "A sum type says a value is exactly one of several named cases, each with its own data, and the compiler knows the full list.",
    neutral: "Sum types go by several names depending on the community: tagged unions, variants, discriminated unions, or choice types.",
    bad: "Sum types work like enums with an integer per case, so attaching different data to each case needs a separate class hierarchy on top." },
  { topic: "Product types",
    good: "A product type holds several fields at once, like a record or tuple; its possible values multiply, so two booleans give four combinations.",
    neutral: "Records and tuples both hold several values together. Records label each field, while tuples rely on position to tell them apart.",
    bad: "Prefer tuples over named records for domain data, since field names add clutter and position makes each slot's meaning clear." },
  { topic: "Recursive data types",
    good: "Trees and lists are recursive sum types: a node holds children of its own type, and a function over them recurses one case at a time.",
    neutral: "Recursive types refer to themselves in their own definitions; trees, lists, and the syntax trees inside compilers all have that shape.",
    bad: "A sum type can't refer to itself in its own definition. Trees and linked lists need mutable pointers that get wired up after construction." },
  // --- Pattern matching ---
  { topic: "Pattern matching",
    good: "Pattern matching checks which case a value is and pulls out its fields in one step. The code that reads data ends up mirroring its shape.",
    neutral: "A match reads a bit like a switch statement, with one branch per shape of input and a result expression for each, so it yields a value.",
    bad: "Patterns only look at the outer layer of a value; to inspect a nested field you match again inside the branch, one level per match." },
  { topic: "Exhaustiveness checking",
    good: "With exhaustiveness checking, adding a case to a sum type turns each match that ignores it into a compile error: a ready-made to-do list.",
    neutral: "Missing cases get reported as warnings or as errors depending on compiler settings, and the message lists each case left out of the match.",
    bad: "Exhaustiveness checking happens at runtime: the program raises an error the moment a value reaches a match with no branch for it." },
  { topic: "Catch-all branches",
    good: "A catch-all branch silences exhaustiveness checking, so a newly added case slides into the default path without any warning.",
    neutral: "A catch-all branch usually sits last in a match, since branches are tried in order and a wildcard accepts whatever reaches it.",
    bad: "End each match with a catch-all branch, because it keeps code compiling when someone adds a case, and that is what exhaustiveness is for." },
  // --- Absence and errors ---
  { topic: "Optional values",
    good: "An optional type puts possible absence into the signature; callers have to handle the empty case before they can reach the value inside.",
    neutral: "Optional values have two cases: one holding a value and one empty. Helper functions exist to transform them or to unwrap them.",
    bad: "Optional types matter mostly as documentation, and at each use the compiler treats an optional value and a nullable reference the same way." },
  { topic: "Unwrapping optionals",
    good: "Force-unwrapping an optional fails hard when it's empty, which brings the null crash right back. Default it, branch on it, or transform it.",
    neutral: "Most optional types offer a way to supply a default value, plus a way to apply a function to the contents when there are any.",
    bad: "Force-unwrapping an optional is a checked operation. When the value is missing, it hands back a zero, an empty string, or an empty list." },
  { topic: "Result types",
    good: "A result type returns either a success value or an error value. Failure shows up in the signature, and callers must deal with it.",
    neutral: "Result types carry two cases, one for success and one for failure; the data in each case has its own type, and the two types often differ.",
    bad: "Result types behave like exceptions with different syntax, since the error still unwinds the call stack until some caller handles it." },
  { topic: "Results vs exceptions",
    good: "Results suit expected failures like bad input or a missing record, while exceptions still make sense for bugs and unrecoverable faults.",
    neutral: "Codebases that adopt result types still contain exceptions, because runtime errors and outside libraries keep throwing them.",
    bad: "After adopting result types, any exception caught in the program counts as a design mistake. Convert each fault, bugs included." },
  { topic: "Error values",
    good: "Give the error side of a result its own sum type of failure cases, not a bare string, so callers can match on what actually went wrong.",
    neutral: "Error values inside a result carry whatever the failure needs to report: a message, a code, a nested cause, or the bad input it rejected.",
    bad: "Keep the error side of a result as a plain text message. Callers rarely need to tell failures apart, and text prints easily in logs." },
  // --- Modeling the domain ---
  { topic: "Illegal states unrepresentable",
    good: "Shape types so bad combinations can't be built: a sum type of the valid cases beats a record of optional fields plus rules.",
    neutral: "The idea applies to plenty of designs; typical targets include order statuses, connection states, and forms with required fields.",
    bad: "To make illegal states unrepresentable, add a validation method to each type and call it from each function that receives one." },
  { topic: "States as variants",
    good: "A connection modeled as connected-with-socket or waiting-with-retry-count beats a record with a status flag and nullable fields.",
    neutral: "State machines show up all over business software; orders and payments and sign-ups each move through a small handful of named states.",
    bad: "A status flag plus nullable fields models states as well as a sum type does, while the flat record is easier to store and serialize." },
  { topic: "Newtype wrappers",
    good: "A newtype wraps one value in a distinct type, so a user ID and an order ID, both integers inside, can't be swapped by mistake.",
    neutral: "Wrapper types are small, often a single declaration, and give an existing representation a meaning that fits the problem domain.",
    bad: "Newtype wrappers cost a heap allocation and a pointer hop each time they're used, which makes them too slow for any hot loop in practice." },
  { topic: "Smart constructors",
    good: "A smart constructor is the only public way to build a type. It checks input and returns an optional or a result, so each value is valid.",
    neutral: "Smart constructors are ordinary functions that return the new type, and they live in the same module as the type they build and protect.",
    bad: "Values from a smart constructor still need re-checking later, because the checks run once at creation and values drift." },
  { topic: "Parse, don't validate",
    good: "Turn raw input into a more precise type once at the boundary, like an email type from a string; the type then carries the proof onward.",
    neutral: "Parsing at the boundary produces a few extra types per feature, each one narrower than the raw data it came from.",
    bad: "Check input with a function returning true or false, then pass the raw value on. Later code can lean on that check as firmly as on a type." },
  // --- Polymorphism and inference ---
  { topic: "Parametric polymorphism",
    good: "A parametric function works on any element type without inspecting it, so one list reversal serves numbers, strings, and orders.",
    neutral: "Generic functions take type parameters, which get filled in with concrete types wherever the function is used, so callers rarely write them.",
    bad: "Parametric polymorphism means the function checks the runtime type of its argument and picks the right behavior for each one." },
  { topic: "Parametricity",
    good: "Generic code can't peek at elements of an unknown type. A pure function over a list of any type can only rearrange, drop, or copy them.",
    neutral: "Generic signatures are mostly short, and the type parameters in them get single letters standing in for any type.",
    bad: "A function generic over its element type can still compare, add, or print the elements, and the type parameter mostly affects compile speed." },
  { topic: "Type inference",
    good: "Type inference lets the compiler work out types from how values are used. Code stays statically typed without annotations everywhere.",
    neutral: "With inference, local variables appear with no written type at all, and editors can show the inferred type on hover while reading.",
    bad: "Type inference tends to make a language dynamically typed in practice, with types decided at runtime from the values that show up." },
  { topic: "Annotations at boundaries",
    good: "Annotate top-level and public functions even where inference could cope; it documents intent and keeps type errors near their cause.",
    neutral: "Write type annotations in a consistent place and format, so readers don't have to hunt for a function's signature when skimming.",
    bad: "Leave annotations off public functions; inference handles them, and a type error appears right where the slip is." },
  { topic: "Type classes",
    good: "Type classes are interfaces implemented per type and chosen by the compiler from the static type: dates get one ordering, names another.",
    neutral: "Type classes group a few related operations under one shared label, and a single type can implement many separate type classes at once.",
    bad: "Type classes work like classes in the object sense: each value carries its methods along, and dispatch looks them up on the object." },
  { topic: "Retroactive instances",
    good: "Type class implementations live apart from the type, so code you don't own, say a library's date type, can gain a new capability unedited.",
    neutral: "Each implementation of a type class covers one type, and a large program might have dozens of them for its own domain types.",
    bad: "A type must declare each type class it supports where the type is defined; adding one later means editing the original source." },
  // --- Totality ---
  { topic: "Total vs partial functions",
    good: "A total function returns a result for each input of its type; a partial one crashes or loops on some inputs, like dividing by zero.",
    neutral: "Partial functions show up in most standard libraries, often in operations for indexing into collections or for parsing text.",
    bad: "A partial function is one that hasn't been applied to all its arguments yet, and it becomes total once the last argument arrives." },
  { topic: "Making functions total",
    good: "Taking the head of a list is partial. Returning an optional, or demanding a non-empty list type, makes the same operation total.",
    neutral: "Some compilers can check totality, while others leave it to the programmer to notice which particular inputs make a function crash or hang.",
    bad: "Total functions can't fail by definition, so a function that returns a result type with an error case doesn't count as total." }
,
  // --- Functors and applicatives ---
  { topic: "Functors",
    good: "A functor is any container or context you can map a function over, changing the values inside while the shape stays the same.",
    neutral: "Lists, optional values, and result types all support mapping over what they hold; the details differ, not the overall idea.",
    bad: "Mapping over an optional value that holds nothing calls the function with an empty input, so the function has to handle that case." },
  { topic: "Functor laws",
    good: "Mapping the identity function changes nothing, and mapping one function then another equals mapping their composition once.",
    neutral: "The functor laws are short to state, and you can check them by hand for a small container type that has only one or two cases.",
    bad: "A map that skips or reorders elements still counts as a lawful functor, as long as it applies the function to what it keeps." },
  { topic: "Applicatives",
    good: "Applicatives combine several independent values in a context, say two optional inputs, when no step depends on another's result.",
    neutral: "Applicative sits between functor and monad in power; every monad can also act as an applicative for that same type.",
    bad: "Use an applicative when the second step needs the result of the first. That sequencing is what applicatives add over functors." },
  { topic: "Accumulating validation",
    good: "Applicative validation can report each bad field in a form at once, since the checks run independently and don't stop early.",
    neutral: "Form validation tends to produce a list of messages, such as a missing email or a short password, shown beside the matching inputs.",
    bad: "A result type chained monadically reports each of the form's errors together, as later steps keep running after one fails." },
  // --- Monads ---
  { topic: "Monads as chaining",
    good: "In practice a monad means chaining steps that each return a value in a context, maybe-missing or may-fail, with the plumbing hidden.",
    neutral: "Monadic code reads as a series of steps; each takes the previous step's plain value and returns a wrapped one for the next step.",
    bad: "Monads exist mainly to let pure code perform side effects. Without input and output there would be little reason to have one." },
  { topic: "Monad identity laws",
    good: "The identity laws say wrapping a plain value and then chaining adds nothing, so a pointless wrap step can go without changing behavior.",
    neutral: "There are three monad laws in all, two about identity and one about associativity, and not one of them takes more than a line to state.",
    bad: "The monad laws are checked by the compiler for each new type, which means a type that breaks them fails to build with an error." },
  { topic: "Associativity law",
    good: "Associativity means you can regroup a chain of steps, pulling the middle two into a helper, and get the same result as before.",
    neutral: "Break long chains of steps into smaller helpers so that each one stays short enough to read in a single pass, top to bottom.",
    bad: "Associativity lets you swap the order of two chained steps freely: reading a file then parsing it equals parsing then reading." },
  { topic: "Monad or applicative",
    good: "Prefer the applicative form when steps don't depend on each other; that leaves room to run them in parallel or gather errors.",
    neutral: "Monadic code reads top to bottom as a script. For many readers that's easier to follow than deeply nested calls or callbacks.",
    bad: "Monads and applicatives differ in syntax alone, and a program written with one can be rewritten with the other at no loss." },
  { topic: "Stacking contexts",
    good: "Mixing contexts, like an async step that may also fail, needs a combined type or a transformer; plain chaining won't mix them.",
    neutral: "Real code often mixes concerns at once: a step may be async, may fail, and may need configuration from somewhere above it.",
    bad: "Two monads compose into a single monad automatically, and chaining an async step with an optional step needs no extra glue." },
  { topic: "Traverse",
    good: "Traverse turns a list of steps that may fail into one result holding the whole list, or the first failure if any step fails.",
    neutral: "Turning a list of optional values into an optional list takes a few lines by hand, and the pattern recurs often enough to deserve a helper.",
    bad: "Mapping a fallible function over a list gives a single result for the whole list, failing as soon as one element in it fails." },
  // --- Effects ---
  { topic: "Functional core, imperative shell",
    good: "A functional core with an imperative shell keeps decisions in pure functions; a thin outer layer does the reading and writing.",
    neutral: "Every program needs input and output somewhere: reading requests, writing to a database, sending email, logging what happened.",
    bad: "Put the I/O calls deep inside the core logic, close to where the data is used. Effects kept near their use spread less far." },
  { topic: "Effects as values",
    good: "Some FP styles return a description of an effect, a value the runtime later executes, so building one runs nothing yet.",
    neutral: "Effect descriptions can be passed around, stored, retried, and combined as ordinary data before anything at the top runs them.",
    bad: "Calling a function that returns an effect description runs the effect right away, and the value it returns is a log of what it did." },
  { topic: "Logging in pure code",
    good: "Logging from inside a pure function makes it impure. Return the log entries as data, or move the logging out to the caller.",
    neutral: "Log lines help with debugging in production, and structured logs with fields are easier to search and filter than plain text messages.",
    bad: "Logging doesn't count as a side effect for purity, since it doesn't change the function's return value or any program state." },
  // --- State ---
  { topic: "State threading",
    good: "State threading passes the current state in and returns a new state out with each result, so every step's inputs stay explicit.",
    neutral: "Threading state by hand means lots of functions that take a state argument; each one hands back a pair of value and new state.",
    bad: "Pure code has no way to model state that changes over time; for things like counters or game worlds, you step outside FP and mutate." },
  { topic: "Folding events into state",
    good: "Folding a stream of events into state with a pure step function gives replay, undo, and easy testing almost for free.",
    neutral: "Event logs grow over time, and systems built on them tend to snapshot the state now and then to keep startup times short.",
    bad: "A reducer may update the previous state object in place and return it, as the final state after the last event is what counts." },
  // --- Concurrency ---
  { topic: "Limits of immutability",
    good: "Immutable values end data races on the values themselves, but threads still swap shared references, and ordering bugs remain.",
    neutral: "Concurrent code is hard to debug, and race conditions don't always show up in tests; they appear under load or on certain machines.",
    bad: "Immutable data removes concurrency bugs entirely: once nothing mutates, deadlocks, ordering problems, and lost updates can't happen." },
  { topic: "Compare-and-swap updates",
    good: "A shared reference updated by compare-and-swap with a pure function lets threads share state; the function may rerun.",
    neutral: "Shared state still has to live somewhere in a concurrent program, even when every value stored in it is immutable and never changes.",
    bad: "Put the email send inside the compare-and-swap update function; the runtime calls that function exactly once per update." },
  { topic: "Software transactional memory",
    good: "Software transactional memory groups reads and writes of shared variables into atomic transactions that retry on conflict.",
    neutral: "Transactional memory borrows ideas from databases, such as commits and rollbacks, and applies them to variables in memory.",
    bad: "Software transactional memory takes a global lock for each transaction, so two transactions never run at the same time." },
  { topic: "Effects inside STM",
    good: "Never put I/O inside an STM transaction: it may retry several times, and a sent message or a written file can't be rolled back.",
    neutral: "STM transactions can touch several shared variables at once, and the code inside them reads as ordinary reads and writes to memory.",
    bad: "Doing I/O inside an STM transaction works out, because the transaction body runs a single time and conflicts get sorted out at commit." },
  // --- Testing ---
  { topic: "Property-based testing",
    good: "Property tests state a rule that holds for all inputs, say that reversing twice gives the original, and check it on random cases.",
    neutral: "Property tests run around a hundred generated cases per property by default in most tools, so slow properties add up fast.",
    bad: "A passing property-based test proves the property holds for every input, as the generator covers the whole input space." },
  { topic: "Shrinking",
    good: "When a property fails, shrinking simplifies the random input to a small case that still fails, which is far easier to debug.",
    neutral: "Generated inputs tend to be large and messy, with long lists and odd characters that aren't easy to read in a failure report.",
    bad: "Shrinking makes property tests faster by trimming generated inputs before each run; it plays no part in reporting failures." },
  // --- Trade-offs and practice ---
  { topic: "FP vs OOP extension",
    good: "Sum types make adding a new operation easy and a new case hard; class hierarchies flip that, which is the expression problem.",
    neutral: "Most mainstream codebases mix the two styles, with classes for structure and small pure functions handling the data inside them.",
    bad: "FP and OOP can't be mixed in one codebase, because immutable values and objects with methods conflict at a basic level." },
  { topic: "Allocation and GC",
    good: "Immutable updates allocate new objects, and most of them die young, so a generational garbage collector handles them cheaply.",
    neutral: "Garbage collectors pause or slow a program now and then, and the cost depends a lot on how much memory gets allocated.",
    bad: "Short-lived objects cost a collector as much as long-lived ones, so collection pauses grow in step with each update allocated." },
  { topic: "Laziness space leaks",
    good: "Laziness can leak space: a chain of unevaluated computations piles up in memory until something finally forces the result.",
    neutral: "Lazy evaluation delays work until a value is needed; that changes when things run, and it makes timing harder to predict.",
    bad: "Switching to lazy evaluation lowers memory use compared with strict evaluation, as unneeded values don't get computed or stored." },
  { topic: "Adopting FP gradually",
    good: "In imperative code, start by extracting pure functions from tangled methods and returning new values in place of mutation.",
    neutral: "Keep functions small enough to read at a glance. A reader shouldn't need to scroll to see what one of them hands back.",
    bad: "Adopting FP in an existing codebase means rewriting it all at once; half-functional code is worse than either style kept pure." }

] };
