// Functional Programming beginner-to-intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "Functional Programming", turns: [
  // --- What it is ---
  { topic: "What FP is",
    good: "Functional programming builds programs out of small functions that take values and return new ones.",
    neutral: "Functional style is one way to organize code; most modern languages support at least some of it.",
    bad: "Functional programming just means organizing code into functions, which any program with functions does." },
  { topic: "Pure functions",
    good: "A pure function gives the same result for the same inputs and changes nothing outside itself.",
    neutral: "Pure functions take inputs and return a result, though not every function in a real program is pure.",
    bad: "Pure functions have to work without arguments, since reading an input from outside makes them impure." },
  { topic: "Same input, same output",
    good: "Call a pure function twice with the same arguments and you'll get back the very same answer both times.",
    neutral: "A function's output depends on its inputs, and some functions take several inputs to compute it.",
    bad: "Same input, same output just means the function doesn't crash; the answer itself is allowed to vary." },
  { topic: "Side effects",
    good: "A side effect is anything besides returning a value: writing a file, logging, or changing a global.",
    neutral: "Printing to the screen, saving to a database, and sending a request over the network all count as side effects.",
    bad: "Side effects are usually bugs, and a well-written functional program has none of them anywhere in it." },
  { topic: "Why purity helps testing",
    good: "Pure functions are easy to test: pass in some inputs and check the output, with no setup or mocks.",
    neutral: "A test for a function checks its result for a few chosen inputs; it can't try every possible one.",
    bad: "Each test of a pure function needs a mock database set up first, or else its results can't be trusted." },

  // --- Immutability ---
  { topic: "Immutability",
    good: "Immutable data never changes once it's created; to update it, you make a new value with the change.",
    neutral: "An immutable value stays the way it was built, and plenty of programs mix immutable and mutable data.",
    bad: "Immutable means the variable is constant, so a list stored in it can still grow and shrink as needed." },
  { topic: "Copying vs changing data",
    good: "Instead of editing a list in place, you return a new list, so the old one stays intact for anyone using it.",
    neutral: "Editing data in place and building a new copy are both ways to update data, each with its own tradeoffs.",
    bad: "Once you return a new list, the old one gets deleted, and any code still holding it will break." },
  { topic: "Updating nested data",
    good: "To change one field deep in nested data, you rebuild only the path down to it and reuse everything else.",
    neutral: "Nested data holds values inside other values, like a customer record holding a list of addresses.",
    bad: "Updating one field in nested immutable data means deep-copying the entire structure, top to bottom." },
  { topic: "Sharing data safely",
    good: "If no one can change a value, you can hand it to any part of the code without worrying who'll edit it.",
    neutral: "Data often gets passed between many parts of a program, and one value may end up used in several places.",
    bad: "Before passing a list to another function, make a defensive copy, even when the list is immutable." },

  // --- Functions as values ---
  { topic: "Functions as values",
    good: "In functional style a function is a value you can store in a variable, put in a list, or pass along to others.",
    neutral: "Functions usually have some parameters and a body, and the body runs each time they're called.",
    bad: "Functions live in one fixed spot in the code, and putting one in a variable to call later is an error." },
  { topic: "Functions in data structures",
    good: "You can keep functions in a lookup table keyed by name, then pick one at runtime to run.",
    neutral: "A lookup table maps keys to values, and the values in it can be numbers, text, lists, or functions.",
    bad: "A table of functions runs every function in it as soon as the table is built, whether you need it or not." },
  { topic: "Higher-order functions",
    good: "A higher-order function takes a function as input or returns one, letting you reuse a whole pattern.",
    neutral: "Higher-order functions show up all over functional code, and they work with functions of any shape or size.",
    bad: "Passing a function into another function is always a hack that makes code harder to read and debug." },
  { topic: "Returning functions",
    good: "A function can build and return a new function, for example one that adds a fixed number to its input.",
    neutral: "A returned function is still a function, so the caller can call it later or pass it somewhere else.",
    bad: "Returning a function is the same as calling both right away, so there's no benefit to splitting them." },
  { topic: "Closures",
    good: "A closure is a function that keeps the variables from where it was made, even after that code is done.",
    neutral: "Closures appear whenever a function is defined inside another and uses something from the outer one.",
    bad: "Once the outer function returns, its variables are gone, and an inner function that used them will crash." },
  { topic: "Closures and changing variables",
    good: "If a closure captures a variable that changes later, it usually sees the new value, which can surprise you.",
    neutral: "A closure can capture one variable or several, and those can hold numbers, lists or even other functions.",
    bad: "A closure copies the outer variables when it's made, and later changes to them are always ignored." },

  // --- Style ---
  { topic: "Expressions vs statements",
    good: "An expression produces a value while a statement just does something; functional code favors expressions.",
    neutral: "Most code mixes expressions and statements, because each one is useful for a different kind of job.",
    bad: "Expressions and statements mean the same thing; it doesn't matter which one a piece of code uses." },
  { topic: "Declarative vs imperative",
    good: "Imperative code spells out each step, while declarative code says what result you want.",
    neutral: "Declarative and imperative are two ways to describe code: a single program usually has some of each.",
    bad: "Declarative code means writing zero loops, and a single loop anywhere makes the code imperative." },
  { topic: "Shared mutable state",
    good: "Shared mutable state is data that many parts can change, and avoiding it removes a big source of tricky bugs.",
    neutral: "State is the data a program holds at a given moment, rather than the code that works on that data.",
    bad: "Global variables that any function can update are the best way to share data across a program." },
  { topic: "Predictable code",
    good: "When functions don't depend on hidden state, you can read each one by itself and know what it does.",
    neutral: "Predictable code isn't automatic; keeping functions small and focused is one habit that helps a lot.",
    bad: "Code is predictable as long as it passes its tests, whatever it reads or changes behind the scenes." },
  { topic: "Swapping a call for its result",
    good: "Swap a pure function call for its result and the program behaves the same, since nothing else happened.",
    neutral: "A function call gives back a result: you can store it, print it, or pass it into another call.",
    bad: "Any function call can be swapped for its result, even one that writes a line to a log file along the way." },

  // --- In practice ---
  { topic: "Local mutation",
    good: "A function can change a local variable and still be pure, because no one outside can see it.",
    neutral: "Local variables are declared inside a function, and code outside that function can't reach them directly.",
    bad: "Changing even one local variable makes a function impure, whatever it does to the outside world." },
  { topic: "Hidden inputs",
    good: "Reading a global, the clock, or a random number is a hidden input; passing it in as an argument makes it visible.",
    neutral: "Functions can get information from their arguments, from variables around them, or from the system.",
    bad: "Reading a global variable doesn't affect purity at all; only writing to one counts as an effect." },
  { topic: "Small functions",
    good: "Small functions that each do one job are easy to combine, test, and reuse in other parts of the program.",
    neutral: "Keep functions short enough to read at a glance, and don't let one function grow to do many jobs.",
    bad: "Splitting code into small functions tends to make it harder to follow, and one big function keeps everything together." },
  { topic: "Doing real work",
    good: "Real programs still need effects; the idea is to keep them in a few places and keep the rest pure.",
    neutral: "Real programs read input and write output somewhere, since a program with no effects can't show results.",
    bad: "A functional program can't do input or output, so it can't save files or talk to a network." },
  { topic: "Changing an argument",
    good: "A function that changes the list it was given can surprise its caller, so return a new list instead.",
    neutral: "Arguments are the values passed into a function, and a function may take zero, one, or several.",
    bad: "Changing the list a caller passed in, rather than returning a new one, is the normal way to hand back results." }
,
  // --- Map and filter ---
  { topic: "Map",
    good: "Map applies a function to each item in a list and hands back a new list of the results.",
    neutral: "Map works on lists, and plenty of other containers offer their own version of it as well.",
    bad: "Map changes each item of the original list in place, which saves memory compared to building a second list." },
  { topic: "Map keeps the shape",
    good: "With map the result has the same length as the input; only the values inside it change.",
    neutral: "Map is handy whenever every item in a collection needs exactly the same treatment applied to it.",
    bad: "Map can also remove items: just return nothing for the ones you want dropped from the result." },
  { topic: "Filter",
    good: "Filter keeps the items that pass a yes-or-no test and drops the rest, without touching the original list.",
    neutral: "Filter is useful for narrowing a list down; it keeps only the items that matter right now.",
    bad: "The test function in a filter decides how each item gets transformed before it lands in the result." },
  // --- Reduce ---
  { topic: "Reduce",
    good: "Reduce walks a list and combines its items into one result, like a total, using a running value.",
    neutral: "Reduce can produce almost anything: a number, a string, a lookup table, or another list.",
    bad: "Reduce is meant for adding up numbers and nothing else; to build a string or a table, write an ordinary loop." },
  { topic: "Reduce starting value",
    good: "The starting value of a reduce matters; it is the answer you get back for an empty list.",
    neutral: "The function you pass to reduce usually takes two inputs: the result so far and the next item in the list.",
    bad: "The starting value for reduce barely matters, since the first item in the list replaces it anyway." },
  { topic: "When reduce gets hard to read",
    good: "If a reduce gets hard to follow, a plain loop or a named helper is clearer, and there's no shame in that.",
    neutral: "Give the running value in a reduce a clear name so readers know what it holds at each step.",
    bad: "Turn every loop into a reduce, even when the loop body is long and juggles several unrelated jobs." },
  // --- Chaining and flatMap ---
  { topic: "Chaining list steps",
    good: "Chaining filter, then map, then reduce lets each step do one small job you can read from top to bottom.",
    neutral: "A chain of list operations reads a bit like a recipe, with each step picking up where the last one left off.",
    bad: "Order in a chain doesn't matter; filtering before or after a map gives the same result." },
  { topic: "Cost of chaining",
    good: "Each step in a chain can build a new list; for normal sizes that cost is fine and barely noticeable.",
    neutral: "Short chains of two or three steps are usually easy to take in at a glance, even for newcomers.",
    bad: "Chaining map and filter is too slow for real work, so one big hand-written loop should be the default everywhere." },
  { topic: "FlatMap",
    good: "FlatMap is a map where each item turns into a list, and then all of those lists get joined into one flat list.",
    neutral: "FlatMap helps when one item can lead to several results; it also handles items that produce none.",
    bad: "FlatMap sorts the list after mapping it, which is what the flat part of the name refers to." },
  // --- Small functions ---
  { topic: "Anonymous functions",
    good: "An anonymous function is a small unnamed function written right where it's passed, say into map.",
    neutral: "Short inline functions keep a bit of logic right next to the code that uses it, with no need to jump elsewhere.",
    bad: "Anonymous functions are limited to logic without parameters, since they have nowhere to declare them." },
  { topic: "Naming inline functions",
    good: "Once an inline function grows past a line or two, giving it a name usually makes it easier to read.",
    neutral: "Named functions show up by name in error traces, which helps a bit when debugging.",
    bad: "Naming a function you use only once is wasteful clutter; anything passed to map should stay anonymous." },
  { topic: "Function composition",
    good: "Composing functions joins them into a new function where the output of one feeds the next.",
    neutral: "Composition lets you build bigger behavior out of small functions that already exist.",
    bad: "Composing two functions runs them side by side on the same input and keeps both of their results." },
  { topic: "Order in composition",
    good: "Order matters when composing: adding one then doubling is not the same as doubling then adding one.",
    neutral: "Small functions that take one input and return one output are the easiest kind to snap together into bigger ones.",
    bad: "Composition breaks unless each function hands back the exact same type of value it was given." },
  { topic: "Pipelines",
    good: "A pipeline passes data through a series of steps in order, each one returning a new value.",
    neutral: "Pipelines tend to read top to bottom, while the data flows through them one step at a time.",
    bad: "In a pipeline each step should change the shared data directly rather than spend time returning a new value." },
  // --- Recursion ---
  { topic: "Recursion",
    good: "A recursive function calls itself on a smaller piece of the problem until it reaches a case it can answer directly.",
    neutral: "Recursion fits nested data such as trees, folders, and menus; the shape of the code follows the data.",
    bad: "Recursion means a function that loops forever unless some timer or counter outside it steps in." },
  { topic: "Base cases",
    good: "Every recursive function needs a base case: an input it answers without calling itself again.",
    neutral: "Writing the base case first is a good habit when sketching out a recursive function, before the trickier part.",
    bad: "The base case can be left out, because the runtime stops the recursion once the list runs out." },
  { topic: "Recursion vs loops",
    good: "Recursion and loops solve the same problems; just pick whichever one makes the code clearer.",
    neutral: "Some problems feel natural as recursion, while others feel natural as a loop.",
    bad: "Functional programming bans loops outright, and repeated work has to be written as recursion." },
  { topic: "Deep recursion",
    good: "Very deep recursion can run out of stack space, so for huge inputs a loop or a built-in helper is the safer choice.",
    neutral: "Each recursive call holds a little memory, and that memory isn't released until the call returns.",
    bad: "Recursion uses no extra memory per call, making it the best choice for lists of any size." },
  // --- Currying and partial application ---
  { topic: "Currying",
    good: "Currying turns a function of several inputs into a chain of functions that each take just one input.",
    neutral: "Curried functions are handy to pass around once some of their inputs are filled in, and the rest can come later.",
    bad: "Currying means caching a function's result so the same call can skip running a second time." },
  { topic: "Partial application",
    good: "Partial application fixes some arguments up front, turning a general function into a specific one.",
    neutral: "Partial application is a neat way to get small, specialized helpers out of bigger general ones.",
    bad: "Partial application runs the function right away and quietly fills in the missing arguments with zero or empty." },
  // --- Laziness and memoization ---
  { topic: "Lazy evaluation",
    good: "Lazy evaluation waits to compute a value until something actually needs it, which can skip a lot of wasted work.",
    neutral: "Laziness lets you describe very long or even endless sequences, as long as you don't read all of them.",
    bad: "Lazy evaluation means the program puts off work until it's idle, then runs it all in the background." },
  { topic: "When lazy work happens",
    good: "With a lazy sequence, the work happens when you read the results rather than when you set up the steps.",
    neutral: "Taking only the first few items from a lazy sequence means the rest of it never has to be computed at all.",
    bad: "A lazy list computes each item up front, then hands them out slowly, one at a time." },
  { topic: "Memoization",
    good: "Memoization saves a function's results by input, so a repeat call with the same input skips the work.",
    neutral: "Memoization pairs well with slow functions that keep getting called with repeat inputs.",
    bad: "Memoizing a function that reads the current time works out; each call still returns the right answer." },
  { topic: "Memoization tradeoffs",
    good: "Memoization fits pure functions best, since the same input always gives the same output to reuse.",
    neutral: "A memo cache takes up memory, and it's worth limiting how big it is allowed to grow over time.",
    bad: "Add memoization to every function by default; the whole program gets noticeably faster that way." },
  // --- Readability ---
  { topic: "Long chains",
    good: "When a chain gets long, pulling a few steps into well-named helpers keeps it readable instead of cryptic.",
    neutral: "Putting each step of a long chain on its own line makes the whole thing easier to scan, and to change later.",
    bad: "Longer chains are often better, and cramming a whole feature into one expression shows real skill." }
,
  // --- Plain data ---
  { topic: "Data as plain values",
    good: "Plain data values with no hidden behavior are easy to print, compare, and pass between functions.",
    neutral: "Plain data values hold information, and separate functions in the program decide what to do with it.",
    bad: "Plain data with no methods attached is typically a sign the design is unfinished and the real logic is missing." },
  { topic: "Records",
    good: "A record groups a few named fields into one value, such as a user with a name, an email, and an age.",
    neutral: "Each field in a record has a label, and it holds a value of some kind, often a number or a string.",
    bad: "Records in functional code can't hold other records inside them; each field needs a simple value of its own." },
  { topic: "Updating a record",
    good: "To change one field, you build a new record with that field updated and the rest copied over.",
    neutral: "Updating a record usually touches only a field or two, so most of the other fields stay just as they were.",
    bad: "Once a record is created, no program can ever get a version of it with a different value in a field." },
  { topic: "Comparing by value",
    good: "Two plain records with the same field values are usually treated as equal, wherever they came from.",
    neutral: "Comparing two values for equality is a basic operation, and plain data keeps it easy to reason about.",
    bad: "Two records count as equal when they are the exact same object in memory, not when their fields match." },
  // --- Missing values ---
  { topic: "Optional values",
    good: "An optional value says in its type that something might be missing, so callers have to handle it.",
    neutral: "An optional either holds something or holds nothing at all; those are the only two possibilities it allows.",
    bad: "Optional values act like null with a longer label and don't change how a caller handles anything." },
  { topic: "Optional vs null",
    good: "With null it's easy to forget a check, while an optional makes the missing case visible and hard to skip.",
    neutral: "Null and optional values both describe a thing that isn't there, though code handles them differently.",
    bad: "Wrapping a value in an optional means it can never be missing, which is the whole point of using one." },
  { topic: "Defaults for missing values",
    good: "When a missing value has a sensible fallback, supplying a default right there keeps the code simple.",
    neutral: "Default values fill in for missing ones, such as zero for a count or an empty string for a title.",
    bad: "Pick a default for every missing value; telling the caller that something is absent never helps them." },
  { topic: "Unwrapping optionals",
    good: "Forcing a value out of an optional without a check brings back the same crash that null caused.",
    neutral: "Getting the value out of an optional means handling both cases, the one where it's there and the one where it isn't.",
    bad: "Unwrap each optional the moment you get it; checking for the empty case is extra noise in the code." },
  // --- Errors as values ---
  { topic: "Result types",
    good: "A result returns either a success value or an error value, so failure is part of the normal return.",
    neutral: "Result values come in two flavors, one for when things worked, and one for when they didn't, each with its own data.",
    bad: "With a result type, errors stay hidden from the caller, who then doesn't have to think about them." },
  { topic: "Results vs exceptions",
    good: "An exception can jump past callers unseen, whereas a result puts the possible failure in plain view.",
    neutral: "Exceptions and result types both report that an operation did not go as planned, in different ways.",
    bad: "Functional code can't use exceptions for anything at all, not even for bugs that should crash the program." },
  { topic: "Chaining results",
    good: "You can chain steps that return results, and the first failure stops the chain with its error at the end.",
    neutral: "A chain of steps passes each result along to the next one until the final value comes out the end.",
    bad: "When chaining steps that return results, each step must check every earlier step's error by hand first." },
  { topic: "Error details",
    good: "A useful error value carries detail, like which field failed and why, and not only a yes-or-no flag.",
    neutral: "Error values can hold a message, a code, or some other description, all saying what went wrong in a step.",
    bad: "Error values usually work best as a plain true or false, since extra detail makes them hard to work with." },
  // --- Shapes and matching ---
  { topic: "Sum types",
    good: "A sum type says a value is one of several shapes, such as a payment by cash, card, or gift voucher.",
    neutral: "Each shape in a sum type can carry its own fields, and any given value holds exactly one shape.",
    bad: "A sum type holds all of its shapes at once, and the code picks which one it wants to read each time." },
  { topic: "Pattern matching",
    good: "Pattern matching checks which shape a value has and pulls out its fields in that same single step.",
    neutral: "Pattern matching looks at a value and picks a branch to run based on what the value looks like.",
    bad: "Pattern matching is for text: it searches a string for words that fit a pattern you give it." },
  { topic: "Matching vs if chains",
    good: "A match over a sum type often reads better than a long chain of if-checks, each case on its own line.",
    neutral: "If-checks and a pattern match can both express the same decision, since each one picks a single branch to take.",
    bad: "Pattern matching is generally too slow for real work, and if-checks should replace it anywhere speed matters." },
  { topic: "Handling every case",
    good: "Handling every case of a sum type means no shape gets forgotten, and many tools warn about a gap.",
    neutral: "Each case in a match gets its own branch, and that branch says exactly what to do with every value of that kind.",
    bad: "Handling every case is overkill; a catch-all branch at the end is the better habit for a match." },
  { topic: "Adding a new case",
    good: "Add a new shape to a sum type, and the compiler can point to each match that now needs a new branch to handle it.",
    neutral: "Sum types can grow over time, as new shapes get added to cover all the new situations a program runs into.",
    bad: "Adding a new shape to a sum type forces you to rewrite the old shapes and their fields from scratch." },
  // --- Making bad states impossible ---
  { topic: "Impossible states",
    good: "Shape your types so bad combinations can't be built; then no code has to check for them later.",
    neutral: "Some combinations of fields don't make sense together, and a program has to deal with that somehow.",
    bad: "Careful runtime checks are what prevent bad states, and the shape of your data has nothing to do with it." },
  { topic: "Loading, error, or data",
    good: "Instead of three flags for loading, error, and data, one sum type with three shapes allows one at a time.",
    neutral: "A screen that fetches data is usually loading, showing an error, or showing results to the user.",
    bad: "Keep a separate true-or-false flag for loading, failed, and done, because more flags give more control." },
  { topic: "Total functions",
    good: "A total function gives a sensible answer for every input it accepts, so it doesn't crash or hang.",
    neutral: "Total functions return something for each possible input, which makes them pleasant to call.",
    bad: "A total function must accept values of any type, even ones its declared input type says it won't take." },
  { topic: "Partial functions",
    good: "Taking the first item of an empty list has no answer; returning an optional makes that function total.",
    neutral: "Some functions don't have a good answer for certain inputs, such as dividing a number by zero.",
    bad: "Crashing on an empty list is the right behavior for a first-item function, and callers shouldn't plan for it." },
  // --- Generics and boundaries ---
  { topic: "Generics",
    good: "Generics let you write one function, like reversing a list, that works for lists of any item type.",
    neutral: "Generic code has a placeholder for a type, and that placeholder gets filled in only when the code is actually used.",
    bad: "Generic functions give up type checking, so their mistakes show up when the program runs instead." },
  { topic: "Generic containers",
    good: "Optional and result are usually generic, so the same idea works for a number, a string, or a user record.",
    neutral: "A container type like a list or an optional holds values of some other type inside of it.",
    bad: "You need a separate optional type written by hand for each kind of value, one for numbers and one for text." },
  { topic: "Validating at the edge",
    good: "Check input once where it enters the program and turn it into trusted types; then the core skips re-checks.",
    neutral: "Input from users or other systems arrives at the edges of a program, before the main logic sees it.",
    bad: "Each function deep in the program should re-validate its inputs, since earlier checks can't be trusted." },
  { topic: "Types as documentation",
    good: "Clear types act as documentation that can't go stale, since the compiler checks the code against them.",
    neutral: "Choose type labels that describe the data clearly, keep each type focused on one idea, and avoid vague, catch-all words.",
    bad: "Types and comments do one job, so once the comments are good it doesn't matter what the types say." }
,
  // --- Monads in plain terms ---
  { topic: "Monads in plain terms",
    good: "A monad is a way to chain steps where each one might fail or carry some extra context along.",
    neutral: "Monads show up a lot in functional code, and the word itself sounds much scarier than the idea behind it.",
    bad: "A monad is mainly a trick for making code run faster by skipping over steps that look unneeded." },
  { topic: "Chaining steps that run later",
    good: "Async chains use the same chaining idea for values that arrive later, each step waiting on the last.",
    neutral: "Asynchronous code deals with work that finishes later, like a network request or a big file read.",
    bad: "Chaining async steps makes them all run at once, in whatever order they happen to finish." },
  // --- Effects at the edges ---
  { topic: "Functional core, imperative shell",
    good: "Keep the decision-making logic pure, and push file reads, network calls and printing out to the edges.",
    neutral: "In this layout the pure core sits in the middle and the code doing I/O wraps around it.",
    bad: "In this layout the core reads files and the database itself, and the shell's only job is to start it." },
  { topic: "Why push effects outward",
    good: "When effects live at the edges, most of the code can be tested with plain inputs and outputs.",
    neutral: "Logging, writing to a database, reading the clock and sending an email each count as side effects of a program.",
    bad: "It's best for each function to fetch its own data from the database right where it needs it." },
  { topic: "A thin shell",
    good: "The shell should stay thin: gather the input, call the pure logic, then act on whatever it returns.",
    neutral: "Most real programs have some outer layer that talks to users, to files or to the network.",
    bad: "If one part of a program does I/O, the whole program stops counting as functional." },
  // --- Concurrency ---
  { topic: "Immutable data and threads",
    good: "Immutable data can be shared between threads freely, since nobody can change it under anyone else.",
    neutral: "Concurrency bugs are often hard to reproduce; they depend on the exact timing of each thread.",
    bad: "Using immutable data removes the need for locks or coordination between threads." },
  { topic: "Shared state still needs care",
    good: "Where threads all update one shared value, you still need locks or similar care, even in FP.",
    neutral: "Running work in parallel can speed things up, but only when the pieces don't depend on each other's results.",
    bad: "Threads are usually a problem in object-oriented code, and functional programs avoid them by design." },
  // --- Testing ---
  { topic: "Testing with fixed inputs",
    good: "Pass the time or a random seed in as an argument, and a test can pin it to one fixed value.",
    neutral: "Tests that give the same result on every run are easier to trust than ones that fail now and then.",
    bad: "Code that uses the current time can't be tested reliably; you have to check it by hand." },
  { topic: "Mocks as a hint",
    good: "If a test needs lots of mocks, that's a hint the logic is tangled up with I/O and could be pulled apart.",
    neutral: "A mock stands in for a real dependency during a test, such as a fake database or clock.",
    bad: "More mocks in a test means better coverage; heavy mocking marks a well-tested codebase." },
  { topic: "Property-based testing",
    good: "Property-based testing checks a rule over many generated inputs, like sorting a list never changing its length.",
    neutral: "Property-based tests generate lots of random inputs instead of relying only on a handful of hand-picked examples.",
    bad: "Property-based testing means checking that each object's properties hold the right values." },
  { topic: "Shrinking and edge cases",
    good: "When a property test fails, a good tool shrinks the input to a small case that still breaks.",
    neutral: "Empty lists, zero and very large numbers make good inputs to try in almost any test.",
    bad: "Once you have property-based tests, normal example-based tests stop being useful and can be deleted." },
  // --- Performance ---
  { topic: "Cost of copying",
    good: "Making new values instead of changing old ones costs some memory; shared structure keeps it small.",
    neutral: "Speed and memory use are both worth measuring before and after a big change to the code.",
    bad: "Every update to an immutable list copies the whole list, making it far too slow for real-world work." },
  { topic: "Local mutation for speed",
    good: "In a hot loop, a local mutable variable is reasonable if no outside code can see it.",
    neutral: "Most performance problems come from a few slow spots, so measuring beats guessing about speed.",
    bad: "A hot loop should be rewritten with recursion and a fresh copy on each step to keep it functional." },
  // --- When it fits ---
  { topic: "Where FP fits well",
    good: "FP style fits well for data transformations, business rules and calculations from inputs to outputs.",
    neutral: "Some problems feel more natural in one style than another; that's worth noticing.",
    bad: "Functional style fits every problem equally well, and any code that keeps state is simply a design mistake." },
  { topic: "Where it fits less well",
    good: "Code that's mostly step-by-step I/O, like a UI event handler, may read better in a plain imperative style.",
    neutral: "Game loops and user interfaces involve a lot of state that keeps changing, and that isn't avoidable.",
    bad: "If a task is hard to write functionally, you just haven't split it into small enough functions." },
  // --- Everyday code ---
  { topic: "Adopting FP a bit at a time",
    good: "You can adopt FP a bit at a time by writing more pure helpers and leaving inputs unchanged.",
    neutral: "Small changes to a codebase are usually easier to review and roll back than one big rewrite that touches everything.",
    bad: "Getting the benefits of FP requires moving the whole project to a purely functional language." },
  { topic: "Callbacks",
    good: "Sorting with a custom comparison or handling a click both pass a function in; that's FP in daily use.",
    neutral: "A callback is a function handed to other code, so that code can call it back at the right moment.",
    bad: "Callbacks have nothing to do with functional programming; they belong to a different style of code." },
  // --- FP and OOP ---
  { topic: "FP and OOP together",
    good: "FP and OOP aren't enemies; many codebases use objects for structure and pure functions for the logic.",
    neutral: "Object-oriented and functional code organize a program around different ideas.",
    bad: "FP and OOP are opposites: a codebase has to pick one style and stick with it for good." },
  { topic: "Data and behavior",
    good: "OOP tends to bundle data with behavior, while FP keeps data plain and puts behavior in functions.",
    neutral: "Both styles care about breaking a big program into smaller pieces that are easier to manage, test and change.",
    bad: "Functional programs leave related functions scattered, with nothing to group them like classes do." },
  // --- Beginner mistakes ---
  { topic: "Chasing purity everywhere",
    good: "An early mistake is chasing purity everywhere instead of keeping effects in a few clear places.",
    neutral: "Learning a new style takes time, and early code written in it often feels a bit awkward.",
    bad: "Writing everything as one long chain of anonymous functions is the real goal of functional style." },
  { topic: "Hidden mutation in a map",
    good: "A quiet mistake is changing an outside list inside a map, which brings back the side effects you meant to avoid.",
    neutral: "Bugs from shared data can show up far away from the line of code that actually caused them.",
    bad: "Changing an outside variable from inside a map is good practice when it saves a line." },
  { topic: "Clarity over cleverness",
    good: "Clear names and a few plain steps beat a clever one-liner, since code is read more often than written.",
    neutral: "Short code isn't always easier to read: longer code that spells out each step can be much easier to follow later.",
    bad: "The fewer lines a functional solution takes, the better it is, even if teammates struggle." },
  { topic: "Learning FP",
    good: "A good way to learn is to rewrite a few loops as map and filter, then see which version reads better.",
    neutral: "Trying a new style on a small side project lets you learn it without the pressure of production code.",
    bad: "Learning FP means dropping everything you know about loops and variables and starting from zero." },
  // --- Team adoption ---
  { topic: "Bringing FP to a team",
    good: "Bringing FP to a team works best gradually, with real examples and agreement on a few habits.",
    neutral: "A shared style guide keeps code consistent when several authors don't write the same way.",
    bad: "The fastest way to adopt FP on a team is to rewrite the existing code in functional style all at once." },
  { topic: "Plain words over jargon",
    good: "Explaining ideas in plain words, like \"returns a new list\", goes further with a team than jargon.",
    neutral: "Each team settles on its own mix of styles over time, often without writing it down anywhere.",
    bad: "A team can't benefit from FP until everyone understands monads and the theory behind them." }
] };
