// Cloudflare beginner-to-intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "Cloudflare", turns: [
  // --- What Cloudflare does ---
  { topic: "Reverse proxy",
    good: "Cloudflare sits in front of your site as a reverse proxy; visitors connect to it, and it talks to your server.",
    neutral: "Cloudflare runs a large global network, and it offers services for websites, apps, and APIs of every size.",
    bad: "Once a site is on Cloudflare, your server can go offline for good; the copies at the edge take over for it." },
  { topic: "CDN",
    good: "As a CDN, Cloudflare keeps copies of static files close to visitors, which cuts the distance they travel.",
    neutral: "A CDN is a network of servers spread around the world, and it delivers web content to users from many places.",
    bad: "A CDN matters for video streaming sites, while pages with ordinary images and scripts get nothing from it." },
  { topic: "Anycast",
    good: "With anycast, many Cloudflare data centers share the same IPs, and each visitor reaches a nearby one.",
    neutral: "Cloudflare's network uses anycast routing, though the details live down in how internet traffic finds its way.",
    bad: "Anycast means Cloudflare hands each visitor a unique IP address picked from the country they're browsing from." },
  { topic: "TLS at the edge",
    good: "With the proxy on, Cloudflare decrypts HTTPS at its edge to cache and filter it, then re-encrypts to your origin.",
    neutral: "HTTPS encrypts traffic between a browser and a server, so others on the same network can't read what's sent.",
    bad: "The proxy passes encrypted traffic straight through untouched; Cloudflare can't read or inspect it." },
  // --- DNS ---
  { topic: "Nameservers",
    good: "To use Cloudflare DNS, you set your domain's nameservers at the registrar to the ones Cloudflare assigns.",
    neutral: "Nameservers answer DNS questions for a domain, and every registered domain has a set of them on file at its registrar.",
    bad: "Moving your nameservers to Cloudflare also transfers ownership of the domain away from your registrar." },
  { topic: "Adding a site",
    good: "When you add a site, Cloudflare imports existing DNS records, and it's worth checking them.",
    neutral: "Adding a site to Cloudflare starts with typing in the domain and then reviewing its list of DNS records.",
    bad: "The record scan at signup copies over each record perfectly, so reviewing the imported list is wasted effort." },
  { topic: "Orange cloud",
    good: "With the orange cloud on, the DNS answer points to Cloudflare's IPs, and traffic passes through its proxy first.",
    neutral: "Each DNS record in Cloudflare has a cloud icon, and you can switch it between orange and grey at any time.",
    bad: "The orange cloud changes the icon's color in the list, while DNS answers keep returning your server's real IP." },
  { topic: "Grey cloud",
    good: "Grey-cloud records are DNS only: visitors look up your server's IP and then connect straight to it.",
    neutral: "DNS-only records still resolve normally, and a typical zone has a mix of grey and orange entries side by side.",
    bad: "Grey records still get the WAF and DDoS protection; the color just turns off caching for that hostname." },
  { topic: "Hiding the origin IP",
    good: "Proxying hides your origin IP from lookups, though a leaked IP still lets attackers go around it.",
    neutral: "Your origin server keeps its own IP address; signing up for Cloudflare doesn't change that address.",
    bad: "Once the record is proxied, nobody can ever reach your server directly, even someone who already knows its IP address." },
  { topic: "DNS propagation",
    good: "Nameserver changes can take hours to spread, since resolvers around the world keep cached answers for a while.",
    neutral: "DNS changes don't show up everywhere at the same moment: give them some time before you start testing.",
    bad: "A DNS change reaches every user worldwide the instant you hit save, with no caching anywhere in between." },
  { topic: "Editing a proxied record",
    good: "Edits to a proxied record take effect fast, because visitors only ever see Cloudflare's IPs, not yours.",
    neutral: "Each DNS record has a type, a name, and a value, and the record's type decides what kind of value can go in it.",
    bad: "Changing a proxied record's origin IP makes visitors wait out a long TTL before traffic moves over." },
  { topic: "New subdomain",
    good: "When a new subdomain doesn't resolve, check that its record exists in Cloudflare rather than at the old DNS host.",
    neutral: "Subdomains cost nothing extra to add, and a single zone can hold a long list of them for different apps.",
    bad: "Once the root domain is on Cloudflare, any subdomain you type works by itself, with no record of its own needed." },
  // --- What the proxy handles ---
  { topic: "Mail records",
    good: "MX records can't be proxied: the proxy handles web traffic, and mail has to reach your mail server directly.",
    neutral: "MX records tell other servers where to deliver email for a domain, and a domain can list several.",
    bad: "Proxying the mail server's hostname adds spam filtering and speeds up email delivery for the domain." },
  { topic: "Mail leaking the origin",
    good: "A grey mail record on the same machine as your website can reveal the origin IP you meant to hide.",
    neutral: "Plenty of domains keep their email at a separate provider rather than on the server that runs the website.",
    bad: "An unproxied mail hostname doesn't matter for security; attackers learn nothing useful from an MX record." },
  { topic: "Non-web traffic",
    good: "The standard proxy carries web traffic, so SSH to a proxied hostname fails; use a grey record or a tunnel.",
    neutral: "SSH and other non-web protocols use their own ports, separate from the ones a website listens on for visitors.",
    bad: "Every port and protocol passes through the orange cloud, including SSH, game servers, and database connections." },
  { topic: "Real visitor IP",
    good: "Behind the proxy, your server logs show Cloudflare's IPs, and the real visitor IP arrives in a request header.",
    neutral: "Web servers log the IP address of each request; those logs help with debugging and keeping traffic stats.",
    bad: "With your records proxied, the server logs keep showing each visitor's own IP address, unchanged." },
  // --- SSL ---
  { topic: "SSL modes",
    good: "The SSL mode sets how Cloudflare connects to your origin; the visitor-to-Cloudflare side is separate.",
    neutral: "Cloudflare offers several SSL/TLS modes, and you pick the one that fits your site in the SSL/TLS settings page.",
    bad: "The SSL mode changes how the padlock looks in the browser rather than how traffic gets encrypted." },
  { topic: "Flexible SSL",
    good: "Flexible SSL encrypts the visitor's side but sends plain HTTP to your server, leaving that hop exposed.",
    neutral: "Flexible mode is quick to turn on, since it doesn't need any certificate installed on the origin.",
    bad: "Flexible SSL encrypts traffic all the way to your server, which makes it the best pick for login and payment pages." },
  { topic: "Full SSL",
    good: "Full mode uses HTTPS to the origin, but it accepts any certificate there, even a self-signed or expired one.",
    neutral: "Full mode needs the origin to listen for HTTPS, so a server that speaks only plain HTTP won't work with it.",
    bad: "Full mode checks that the origin certificate is valid and trusted, and it rejects anything self-signed." },
  { topic: "Full (strict)",
    good: "Full (strict) is the mode to aim for: HTTPS to the origin with a certificate that Cloudflare verifies.",
    neutral: "Full (strict) sits next to Flexible and Full in the list of SSL modes, and it's the strictest of the three.",
    bad: "Avoid strict mode in production; the extra certificate check slows down each page load noticeably." },
  { topic: "Origin certificates",
    good: "A Cloudflare origin certificate is free and trusted by Cloudflare, which is enough for Full (strict).",
    neutral: "An origin certificate gets installed on your web server, and you can create one in the SSL/TLS section.",
    bad: "Browsers trust Cloudflare origin certificates too, so you can keep serving them after turning the cloud grey." },
  { topic: "Edge certificates",
    good: "Cloudflare issues and renews the edge certificate for proxied hostnames by itself, with no setup from you.",
    neutral: "A visitor's browser checks the edge certificate each time it shows the padlock icon for your site.",
    bad: "You have to upload your own certificate before a proxied site can serve HTTPS through Cloudflare." },
  { topic: "HTTP to HTTPS",
    good: "Turn on Always Use HTTPS and Cloudflare redirects plain HTTP requests before they reach your origin.",
    neutral: "Sites today are expected to load over HTTPS, and modern browsers flag plain HTTP pages as not secure for users.",
    bad: "An edge certificate blocks HTTP requests by itself, so a redirect from HTTP to HTTPS is unnecessary." },
  { topic: "HSTS",
    good: "HSTS tells browsers to use only HTTPS for your site; enable it once HTTPS works everywhere.",
    neutral: "You can switch on HSTS from Cloudflare's SSL/TLS settings; it works through a header on each response.",
    bad: "HSTS is easy to undo: switch it off, and visitors' browsers drop back to plain HTTP for your site on the next visit." },
  { topic: "Redirect loops",
    good: "Flexible mode plus an origin that forces HTTPS causes a redirect loop; switching to Full or Full (strict) fixes it.",
    neutral: "A redirect loop shows up in the browser as a page that keeps bouncing and never finishes loading.",
    bad: "Redirect loops come from the browser cache, and clearing your cookies is the real fix for them each time." }
,
  // --- What gets cached ---
  { topic: "Default caching",
    good: "Out of the box Cloudflare caches static files by extension, like images, scripts and stylesheets.",
    neutral: "Caching keeps a copy of a file closer to the visitor for a while, then fetches a new one from the origin.",
    bad: "Cloudflare caches every page on your site by default, HTML included, once the record is proxied." },
  { topic: "Origin cache headers",
    good: "The Cache-Control header from your origin tells Cloudflare and browsers how long to keep a response.",
    neutral: "Cache headers travel along with each response the server sends back, next to the content type and length.",
    bad: "Cloudflare tends to ignore your origin's cache headers and picks its own times for everything." },
  { topic: "Edge vs browser cache",
    good: "Edge cache time is how long Cloudflare holds a copy; browser cache time is for the visitor's browser.",
    neutral: "Both Cloudflare's edge and the visitor's browser can hold onto a cached copy of the same file.",
    bad: "Purging Cloudflare's cache wipes the copies in visitors' browsers too, rather than the edge alone." },
  { topic: "Cache time choices",
    good: "Short cache times suit content that changes often, and long ones suit files that rarely change.",
    neutral: "A cache time is how long a stored copy counts as fresh, so it decides when the copy gets checked again.",
    bad: "Shorter cache times make a site faster overall, as visitors get fresher files more often." },
  { topic: "First request",
    good: "The first request for a file at a location is a miss; later ones are hits until the copy expires.",
    neutral: "A cache miss means Cloudflare had to go back to the origin to get the response for that request.",
    bad: "Cloudflare copies your whole site onto its servers ahead of time, before anyone asks for a page." },
  { topic: "Per-location caches",
    good: "Each Cloudflare location has its own cache, so a file cached in one city may miss in another.",
    neutral: "Cloudflare runs data centers in a great many cities, and visitors get routed to one near them.",
    bad: "Once a file is cached at one location, the other Cloudflare locations can serve it instantly too." },

  // --- HTML and personal pages ---
  { topic: "Caching HTML",
    good: "Caching HTML makes a site much faster, though it takes care so personal pages don't get shared.",
    neutral: "HTML pages can be cached at the edge as well, once you add a rule that covers them.",
    bad: "Caching all HTML is a smart default, even on a site where visitors log in and have accounts." },
  { topic: "Logged-in pages",
    good: "Pages with a user's name or cart should bypass the cache, or one visitor might see another's data.",
    neutral: "A logged-in page usually looks a little different for each person who views it, since it's personal.",
    bad: "Cloudflare can tell which pages are personal and skips caching them, even under a cache-everything rule." },
  { topic: "Private responses",
    good: "Marking a response as private in its cache headers keeps Cloudflare from storing a shared copy.",
    neutral: "Cache headers can mark a response as public, as private, or as something not to store at all.",
    bad: "Marking a response private affects browsers alone; Cloudflare still caches it like other files." },
  { topic: "API responses",
    good: "API responses tend to be dynamic and aren't cached by default, though a rule can cache public ones.",
    neutral: "An API response is often JSON that the server builds fresh for each call, using whatever data is current.",
    bad: "An API behind Cloudflare can't be cached, even when its responses are identical for each caller." },

  // --- Controlling the cache ---
  { topic: "Cache rules",
    good: "Cache rules match requests by things like path, then cache them, bypass them, or set a cache time.",
    neutral: "Cache rules are set up per site in Cloudflare and apply only to the requests that match their conditions.",
    bad: "Cache rules run on your origin server, which needs a plugin installed before they do anything." },
  { topic: "Query strings",
    good: "By default each different query string gets its own cache entry, so tracking tags lower the hit rate.",
    neutral: "The query string is the part of a URL after the question mark, made of keys and values.",
    bad: "Cloudflare strips query strings before caching, and the variations of a URL share one cached copy." },
  { topic: "Development mode",
    good: "Development mode briefly bypasses the cache, which lets you see changes right away.",
    neutral: "Development mode is a switch in the caching settings, and it turns itself off after a while.",
    bad: "Leave development mode on in production to make sure visitors never get an outdated page." },
  { topic: "Versioned filenames",
    good: "A version or hash in asset filenames lets you cache them for a long time and still ship updates.",
    neutral: "Build tools can add a short hash to the names of the files they output, based on the contents.",
    bad: "Cloudflare keys its copies on file contents rather than URLs, so renaming a file changes nothing." },

  // --- Purging and deploys ---
  { topic: "Purging",
    good: "Purging drops Cloudflare's cached copies, and the next request pulls a fresh one from the origin.",
    neutral: "Purge the cache after changing a file that was given a long cache time, so the change shows up.",
    bad: "A purge usually takes a day or so to spread around the world, much like a DNS change does." },
  { topic: "Purge scope",
    good: "Purging only the changed URLs is gentler than purging everything at once.",
    neutral: "You can purge a single file, a list of URLs, or the whole cache when something changes.",
    bad: "Purge everything after each deploy; there's no real cost to the origin server from doing that." },
  { topic: "Stale content after deploy",
    good: "Old files after a deploy usually mean cached copies are still valid; purge them or version the names.",
    neutral: "Deploys and cache settings are worth planning together before a release goes out to all your users.",
    bad: "Old content after a deploy means the deploy failed, as Cloudflare notices file changes on its own." },

  // --- Checking and measuring ---
  { topic: "Cache hit or miss",
    good: "Cloudflare adds a cache status header to responses it proxies, saying if it was a hit or a miss.",
    neutral: "Open the browser's network tab to look at the response headers that came back with a file.",
    bad: "A page that loads fast proves it came out of Cloudflare's cache and didn't touch the origin at all." },
  { topic: "Cache hit ratio",
    good: "A low hit ratio means requests vary too much or the content isn't marked as cacheable.",
    neutral: "The cache hit ratio is the share of all requests that were answered straight from the cache.",
    bad: "Aim for a hit ratio near zero, as that means visitors get the freshest content on every request." },
  { topic: "Analytics",
    good: "Cloudflare's analytics show requests, bandwidth and the share served from cache, which helps you spot cache trouble.",
    neutral: "The analytics view charts requests and bandwidth for your site over a time range you choose.",
    bad: "Cloudflare's analytics count only the requests that reached your origin, so cache hits never show up." },
  { topic: "Origin load",
    good: "Every cache hit is a request your origin never has to handle, which saves server load and bandwidth.",
    neutral: "A busy site made up mostly of static files gets a lot out of caching, since those rarely change.",
    bad: "Caching mostly helps visitors, while the load on the origin server stays about the same either way." },
  { topic: "Measuring speed",
    good: "Measure page speed before and after a change, from a few places, rather than trusting one test run.",
    neutral: "Page speed tests report numbers such as total load time and the time to first byte.",
    bad: "One speed test from your own laptop can tell you how fast the site feels for your whole audience." },

  // --- Making responses smaller and faster ---
  { topic: "Compression",
    good: "Cloudflare compresses text responses such as HTML, CSS and JSON on the way out to the browser.",
    neutral: "Compressed responses are smaller, and that helps most on slow mobile connections.",
    bad: "Compression helps images and videos the most, since they're the biggest files on any page." },
  { topic: "Image optimization",
    good: "Image optimization resizes images and serves newer, smaller formats to browsers that support them.",
    neutral: "Images make up a large share of the bytes on a typical web page, often more than all the scripts.",
    bad: "Image optimization rewrites the original files on your server so that they take up less space." },
  { topic: "HTTP/3",
    good: "HTTP/3 runs over a newer transport that copes better with flaky networks, like mobile data.",
    neutral: "Turning on HTTP/3 is just a single switch, and browsers without support for it simply fall back on their own.",
    bad: "Enabling HTTP/3 means upgrading your origin server to support it first, or nothing will load." }
,
  // --- Attacks and the WAF ---
  { topic: "DDoS protection",
    good: "Cloudflare soaks up most DDoS floods at its edge, and the junk never reaches your server.",
    neutral: "Basic DDoS protection is on for proxied traffic by default; it needs no rules from you to start working.",
    bad: "DDoS protection stays off until you spot an attack; then you switch it on for your account." },
  { topic: "The WAF",
    good: "The WAF checks incoming requests and blocks ones that look like attacks, such as SQL injection.",
    neutral: "A web application firewall sits in front of your site; it looks at the HTTP traffic coming in.",
    bad: "With the WAF on, you can stop validating input and skip fixing injection bugs in your own code." },
  { topic: "Managed rules",
    good: "Managed rules are rule sets Cloudflare maintains for known attacks; you mostly turn them on.",
    neutral: "Managed rules cover known attack patterns, and Cloudflare updates them as new attacks show up.",
    bad: "Managed rules give you an empty template, and you write each attack signature into it yourself by hand." },
  // --- Custom rules ---
  { topic: "Blocking a path",
    good: "A custom rule can block requests to a path like /wp-admin if you don't run WordPress.",
    neutral: "Custom rules match on details of a request, such as its path, and then take an action on the match.",
    bad: "Blocking one path takes a code change on the origin because Cloudflare can't see request URLs." },
  { topic: "Blocking a country",
    good: "You can challenge or block whole countries with a rule, yet attackers using proxies get around it.",
    neutral: "Cloudflare tags each request with the visitor's country, and firewall rules can match on that.",
    bad: "Blocking a country stops every attacker based there, even the ones who connect through a VPN." },
  { topic: "Blocking an IP",
    good: "Blocking one bad IP helps briefly, but attackers rotate addresses, so rate limits hold up better.",
    neutral: "IP access rules let you allow, block or challenge one address or a whole range of them.",
    bad: "Once you block the attacking IP address, that attack is over for good and nothing else is needed." },
  { topic: "Rate limiting",
    good: "Rate limiting caps how many requests one client sends in a time window, handy on login pages.",
    neutral: "Rate limiting counts requests per client and only acts once one goes over the threshold you set.",
    bad: "Rate limiting slows the whole site down for visitors once traffic gets busy, instead of targeting one client." },
  // --- Bots ---
  { topic: "Bots and challenges",
    good: "A challenge asks the browser to prove it's real; most humans barely notice it happening.",
    neutral: "Automated bot traffic makes up a real share of the requests hitting most public sites.",
    bad: "The best bot setting blocks automated requests across the board, search engine crawlers included." },
  { topic: "Turnstile vs CAPTCHA",
    good: "Turnstile checks visitors mostly in the background, and they seldom have to pick out traffic lights.",
    neutral: "Turnstile is a widget for forms, and your server then verifies the token it hands back.",
    bad: "Turnstile needs your site's DNS proxied through Cloudflare's network before the widget will load." },
  { topic: "Verifying Turnstile",
    good: "Your backend has to verify the Turnstile token with Cloudflare; the widget by itself proves nothing.",
    neutral: "Turnstile fits on forms such as sign-up, login or contact pages, or any other form you want to guard.",
    bad: "A success tick from the Turnstile widget means the form post can be trusted as is, with no server check." },
  { topic: "Under Attack mode",
    good: "Under Attack mode shows every visitor a short check page, so save it for an active attack.",
    neutral: "Under Attack mode is a switch that adds an extra browser check before visitors reach the site.",
    bad: "Turning on Under Attack mode permanently gives you the strongest protection at zero cost to users." },
  // --- Reaching the origin ---
  { topic: "Locking the origin",
    good: "Lock the origin firewall to Cloudflare's IP ranges; otherwise anyone with the real IP skips the WAF.",
    neutral: "Cloudflare publishes the IP ranges that its servers use when they connect to your origin.",
    bad: "Locking the origin to Cloudflare's IPs breaks the site, since visitors can no longer reach it." },
  { topic: "Cloudflare Tunnel",
    good: "Tunnel runs a small agent that dials out to Cloudflare, so no inbound port needs to be open.",
    neutral: "A tunnel links a server, or even a service on your laptop, to Cloudflare's network.",
    bad: "To set up Cloudflare Tunnel, open an inbound port on your firewall and forward it to the server." },
  { topic: "Tunnel use cases",
    good: "Tunnel suits exposing a home lab or internal tool without a public IP or port forwarding.",
    neutral: "One tunnel can carry traffic for several hostnames, because each one maps to a local service.",
    bad: "Putting an app behind Tunnel drops each visitor onto your private network, VPN-style." },
  // --- Access ---
  { topic: "Access",
    good: "Access puts a login in front of an internal app, and only users your policy allows get in.",
    neutral: "Access works with identity providers, including Google accounts or a company login.",
    bad: "Access requires you to rewrite each app around a Cloudflare login library instead of your own login." },
  { topic: "Access vs a VPN",
    good: "Access checks each request against a policy instead of trusting anyone who got onto a VPN.",
    neutral: "Access policies can match on a user's email address, their email domain, or a group they belong to.",
    bad: "Access gates the whole network at once: it can't give different apps different rules." },
  // --- API tokens ---
  { topic: "API tokens vs global key",
    good: "Use scoped API tokens for scripts and CI rather than the global API key, which can do everything.",
    neutral: "API tokens are created from your profile settings, and each one gets a name you choose for it.",
    bad: "The global API key suits CI better because it never runs into permission errors on any job." },
  { topic: "Least privilege",
    good: "Give a deploy token just what that job needs, such as editing a single zone's DNS.",
    neutral: "Each API token lists the permissions it has and the resources those permissions apply to.",
    bad: "One admin token shared by all your scripts is easier to manage and equally secure." },
  { topic: "Leaked tokens",
    good: "If a token leaks, revoke it and make a new one, and a narrow scope keeps the damage small.",
    neutral: "Keep API tokens in your CI system's secret storage; they don't belong in the repository itself.",
    bad: "A leaked API token can't be revoked, and you have to wait for it to expire on its own." },
  // --- Errors and logs ---
  { topic: "Origin down",
    good: "A Cloudflare page saying the host is down usually means your origin crashed or refused the connection.",
    neutral: "Cloudflare shows its own error page when it can't get a usable answer from your origin.",
    bad: "A Cloudflare error page means Cloudflare itself has an outage, and there's nothing to fix on your side." },
  { topic: "Timeouts",
    good: "A timeout error from Cloudflare means the origin took too long to answer: look at slow database queries.",
    neutral: "Check your origin's own logs when Cloudflare shows a timeout error, so you can find the slow part.",
    bad: "A timeout error from Cloudflare points at the visitor's slow connection rather than anything on your server." },
  { topic: "Security events",
    good: "Security events show which rule fired on a request, so you can see why someone got blocked.",
    neutral: "Each security event lists details such as the client IP, path, country and the action taken.",
    bad: "Blocked requests aren't recorded anywhere, so you can't tell why a particular user got blocked." },
  { topic: "False positives",
    good: "A WAF rule can block real users by mistake; check the events, then add a narrow exception.",
    neutral: "False positives mean a rule matched real users, so legit traffic gets blocked or challenged.",
    bad: "When the WAF blocks a real user, the right fix is to turn the whole WAF off for the site." },
  { topic: "Rolling out a rule",
    good: "Start a new rule as a challenge, not a block, and watch the events before tightening it.",
    neutral: "Firewall rules can be paused or edited any time, with no redeploy of your own app needed.",
    bad: "Every new rule should start as a hard block; loosen it later if enough users complain." },
  { topic: "Allowing your own services",
    good: "Add a skip rule for your own monitoring or partner IPs, so security checks don't block them.",
    neutral: "Uptime checkers and webhooks come from servers rather than browsers, so they can trip bot rules.",
    bad: "Payment provider webhooks pass any bot challenge because they come from big, trusted companies." }
,
  // --- Workers basics ---
  { topic: "What Workers are",
    good: "Workers run your code in Cloudflare's data centers, close to whoever is making the request.",
    neutral: "Workers belong to Cloudflare's developer platform; they sit alongside its storage and hosting products.",
    bad: "Workers run in one central region you pick, and Cloudflare forwards each request over to it." },
  { topic: "Handling a request",
    good: "A Worker receives a request and returns a response, and it can call your origin in between.",
    neutral: "A Worker is mostly a function: Cloudflare hands it each request and waits for what it gives back.",
    bad: "Workers can tweak a response after the origin replies, though they can't answer a request themselves." },
  { topic: "Good use cases",
    good: "Redirects, auth checks, A/B tests, and small fast APIs are good jobs to put in a Worker.",
    neutral: "Workers handle jobs of many sizes, such as tiny scripts or whole applications with many routes.",
    bad: "Hour-long video transcoding fits inside a single Worker request with no trouble at all." },
  { topic: "Workers vs a server",
    good: "There's no machine to patch or scale yourself; Cloudflare starts your code on demand, near the user.",
    neutral: "Workers and traditional servers can both serve web requests, talk to databases and return JSON.",
    bad: "Moving to Workers gives you a virtual machine in each location that you can log into and maintain." },
  { topic: "CPU time limits",
    good: "Each request gets a short CPU time budget, so heavy number crunching belongs somewhere else.",
    neutral: "Workers measure CPU time per request, and a request that goes over its limit is stopped with an error.",
    bad: "Waiting on a slow fetch to another API burns through the Worker's CPU budget the whole time." },
  { topic: "No long-running process",
    good: "Don't count on in-memory variables surviving between requests; there's no always-on process.",
    neutral: "A Worker's lifetime is tied to the requests and events it handles, rather than to a machine.",
    bad: "A background loop started in a Worker can keep running forever; it never stops between requests." },
  // --- Wrangler and config ---
  { topic: "Wrangler for local dev",
    good: "Wrangler runs a Worker on your laptop, where you can hit it in a browser and read logs before deploying.",
    neutral: "Wrangler runs from a terminal, and it works on Mac, Windows, and Linux machines without much setup.",
    bad: "To try out a Worker, you deploy it to production and test it there, as laptops can't run Workers." },
  { topic: "Deploying with Wrangler",
    good: "One Wrangler deploy pushes your Worker across Cloudflare's network, usually within seconds.",
    neutral: "Wrangler handles deploys too: it uploads the Worker and prints a URL once everything is done.",
    bad: "After a deploy, each data center slowly picks up the new Worker version over the next few days." },
  { topic: "Environment variables",
    good: "Plain environment variables suit non-secret settings, like an API base URL that differs per environment.",
    neutral: "Environment variables give a Worker values it reads at runtime, so they don't need to be hardcoded.",
    bad: "Environment variables are shared by every Worker in the account, so two Workers can't hold different values." },
  { topic: "Secrets",
    good: "Secrets are stored encrypted and set with a Wrangler command, not committed to your repo.",
    neutral: "Inside the code, secrets and plain variables look alike: both show up on the Worker's environment.",
    bad: "Keep your Worker secrets in the config file you commit, so teammates can use them right after cloning." },
  { topic: "Config as code",
    good: "Keep the Worker's config file in Git so routes and bindings get reviewed and deployed with the code.",
    neutral: "Cloudflare settings don't have to be clicked in by hand; an infrastructure-as-code tool can manage them.",
    bad: "Clicking through production settings by hand beats keeping config files, which drift from reality." },
  // --- Routes and domains ---
  { topic: "Routes",
    good: "A route tells Cloudflare which URL patterns on your site should run the Worker.",
    neutral: "Routes connect a Worker to URLs, and a single Worker can have several routes on one site.",
    bad: "Once deployed, a Worker takes over each site in your account, whatever the URL." },
  { topic: "Custom domains",
    good: "Attach a custom domain to a Worker and Cloudflare sets up the DNS record and certificate for you.",
    neutral: "Even with no custom domain, a Worker is still reachable on its own workers.dev subdomain.",
    bad: "To use your own domain with a Worker, you have to buy and upload a TLS certificate by hand." },
  // --- Storage ---
  { topic: "Bindings",
    good: "Bindings hand a Worker its KV namespace or D1 database by name, with no connection string.",
    neutral: "Each binding shows up as a property on the environment object passed into your Worker.",
    bad: "A Worker reaches KV or D1 by opening a raw database connection with a username and password." },
  { topic: "KV basics",
    good: "KV fits config, feature flags, or cached lookups: data that's read often and written rarely.",
    neutral: "KV stores values under keys, and a Worker reads and writes them through a binding at runtime.",
    bad: "Live counters that thousands of users bump every second belong in KV; a vote tally is a good fit." },
  { topic: "KV consistency",
    good: "KV is eventually consistent, so a write may take a little while to show up in other locations.",
    neutral: "Reads from KV are quick because values get cached near where they're being requested.",
    bad: "Once you write to KV, no location ever serves the old value again, not even for a moment." },
  { topic: "R2",
    good: "R2 holds files like uploads, images and backups as objects in a bucket that you fetch back by key.",
    neutral: "R2 buckets hold objects, and any Worker with a binding to the bucket can read and write them.",
    bad: "Small key-value settings go in R2, and large files like videos are what KV is built for." },
  { topic: "D1",
    good: "D1 is a SQL database, so it fits relational data where you want queries, joins, and indexes.",
    neutral: "With D1, a Worker can run SQL against a database that Cloudflare hosts, so there's no server to run.",
    bad: "D1 holds loose JSON documents, and you search them by key instead of with SQL queries." },
  { topic: "Durable Objects",
    good: "One Durable Object holds its own state, and related requests all go through it, which avoids races.",
    neutral: "Durable Objects aren't a separate service: they live on the Workers platform and are defined as classes in your code.",
    bad: "Each call to a Durable Object lands on a fresh copy that forgets what earlier requests stored." },
  { topic: "Durable Objects use case",
    good: "A chat room or shared document fits a Durable Object well, since one object coordinates everyone.",
    neutral: "Durable Objects can store data, and that data sticks around after each request has finished.",
    bad: "Use Durable Objects to serve static images, as they cache files closer to users than the CDN." },
  { topic: "Picking storage",
    good: "Roughly: KV for read-heavy settings, R2 for files, D1 for tables, and Durable Objects for coordination.",
    neutral: "Cloudflare offers several storage products, and each one has its own strengths and limits.",
    bad: "R2, KV, and D1 are interchangeable storage options: pick whichever name you like best." },
  // --- More of the platform ---
  { topic: "Queues",
    good: "Queues let a Worker hand off slow work, like sending emails, and reply to the user right away.",
    neutral: "With Queues, one Worker sends messages and another consumes them later; the two don't run in lockstep.",
    bad: "Sending a message to a queue makes the user wait until the consumer has finished the whole job." },
  { topic: "Pages for sites",
    good: "Pages builds and hosts your site from a Git repo and gives each branch its own preview URL.",
    neutral: "Pages hosts websites, and front-end projects of all sizes are a natural fit for it.",
    bad: "Pages hosts hand-written HTML files only, and a site that needs a build step has to go elsewhere." },
  { topic: "Full-stack Pages",
    good: "Pages isn't limited to static files: you can add server-side functions that run as Workers.",
    neutral: "A Pages project can include both front-end files and some back-end code in one place.",
    bad: "If your Pages site needs an API, you have to run a separate server outside Cloudflare for it." },
  { topic: "Workers AI",
    good: "Workers AI lets you call hosted models for text or images from a Worker, without renting or managing GPUs.",
    neutral: "Workers AI runs machine learning models on Cloudflare's network, rather than on your own hardware.",
    bad: "Using Workers AI means renting your own GPU server and installing the models on it yourself." }
] };
