// Cloudflare intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "Cloudflare", turns: [
  // --- DNS & the proxy ---
  { topic: "Proxied DNS records",
    good: "A proxied (orange cloud) record resolves to Cloudflare's anycast IPs, so traffic flows through Cloudflare and the origin IP stays hidden.",
    neutral: "The orange cloud icon appears next to each DNS record in the dashboard, and you click it to switch proxying on or off.",
    bad: "The orange cloud only marks Cloudflare as the authoritative nameserver for that record; the actual HTTP traffic still goes straight to your origin." },
  { topic: "DNS-only records",
    good: "A gray-clouded record is DNS-only: Cloudflare answers the lookup, but no CDN, WAF, or caching touches that traffic.",
    neutral: "You can toggle any record between proxied and DNS-only whenever you like from the DNS records page, and the change saves right away.",
    bad: "Gray-clouding a record makes it faster, since Cloudflare skips the proxy hop and caches the DNS answer more aggressively." },
  { topic: "Full setup",
    good: "In a full setup you change your registrar's nameservers to the two Cloudflare assigns, and Cloudflare becomes authoritative for the whole zone.",
    neutral: "Cloudflare's assigned nameservers have names that look like people's first names, and every account gets its own pair of them.",
    bad: "A full setup just means adding one CNAME at your existing DNS provider that points your domain over to Cloudflare." },
  { topic: "Anycast",
    good: "With anycast, the same IPs are announced from every Cloudflare data center, and BGP routing lands each user at a nearby one.",
    neutral: "Cloudflare has data centers in hundreds of cities around the world, and its network map is published on the company's website.",
    bad: "Anycast means Cloudflare hands each visitor a unique IP address based on their country, then routes that IP to the closest data center." },
  { topic: "Proxied ports",
    good: "Proxied HTTP(S) only works on a fixed port list like 80, 443, 8080 and 8443; for arbitrary TCP, look at Spectrum or Tunnel.",
    neutral: "Most websites run on ports 80 and 443 anyway, and the list of ports Cloudflare supports is documented in the network settings docs.",
    bad: "Once a record is proxied, Cloudflare forwards every port, so SSH on port 22 works through the orange cloud too." },
  { topic: "CNAME flattening",
    good: "CNAME flattening lets you put a CNAME at the zone apex: Cloudflare resolves the chain and answers with A/AAAA records, staying RFC-compliant.",
    neutral: "CNAME records alias one hostname to another, and they're one of the most common record types you'll see in a zone.",
    bad: "A CNAME at the apex is impossible on Cloudflare because the RFC forbids it, so you always have to hard-code an A record there." },
  { topic: "TTL on proxied records",
    good: "Proxied records use Auto TTL (300s), and an origin IP change applies almost at once since visitors only see Cloudflare's IPs.",
    neutral: "Every DNS record has a TTL value, which shows up in its own column on the DNS records page next to the record's name and content.",
    bad: "Setting a proxied record's TTL down to 30 seconds makes switching to a new origin faster for visitors with cached lookups." },
  { topic: "DNSSEC",
    good: "Enabling DNSSEC on Cloudflare is one click, but if your registrar is elsewhere you must add the DS record there too.",
    neutral: "DNSSEC adds cryptographic signatures to DNS records, and you'll find its toggle in the DNS settings area of the dashboard.",
    bad: "DNSSEC encrypts your DNS queries end to end, so your ISP and anyone else on the network can no longer see which domains you look up." },
  { topic: "1.1.1.1",
    good: "1.1.1.1 is Cloudflare's public DNS resolver, focused on speed and privacy; 1.1.1.2 and 1.1.1.3 add malware and adult-content blocking.",
    neutral: "1.1.1.1 is an easy IP address to remember, and Cloudflare offers free apps that set it up on phones and laptops.",
    bad: "1.1.1.1 is the IP you point your domain's A record at to switch on Cloudflare proxying for every hostname in the zone." },
  { topic: "Registrar",
    good: "Cloudflare Registrar sells domains at cost with no renewal markup, but the domain must use Cloudflare for DNS.",
    neutral: "You can transfer existing domains into Cloudflare Registrar from the dashboard, and many people move their domains over that way.",
    bad: "Cloudflare Registrar makes the first year cheap as an intro offer, then raises renewal prices the way most registrars do." },

  // --- SSL/TLS ---
  { topic: "Flexible SSL",
    good: "Flexible encrypts browser-to-Cloudflare but uses plain HTTP to the origin, a classic cause of redirect loops.",
    neutral: "Flexible is one of several SSL/TLS encryption modes listed in the dashboard, alongside Off, Full and Full (strict).",
    bad: "Flexible is the most secure mode, because it adapts to whatever the origin supports and always negotiates the strongest cipher available." },
  { topic: "Full (strict)",
    good: "Full (strict) encrypts to the origin and validates its certificate, which must be publicly trusted or issued by Cloudflare's Origin CA.",
    neutral: "Full (strict) is the mode most security folks recommend, and it's one of the options on the SSL/TLS overview page.",
    bad: "Full (strict) is basically Full; the 'strict' part only forces visitors' browsers to negotiate TLS 1.3 at the edge." },
  { topic: "Origin CA certificates",
    good: "Origin CA certs are free and long-lived, but only Cloudflare trusts them, so they only make sense behind the proxy.",
    neutral: "You can generate Origin CA certificates from the SSL/TLS section of the dashboard and download them in a few common formats.",
    bad: "An Origin CA cert is a good fit for a gray-clouded record, since browsers already trust Cloudflare's CA." },
  { topic: "Universal SSL",
    good: "Universal SSL gives proxied hostnames a free edge certificate automatically, covering the apex and first-level subdomains.",
    neutral: "Edge certificates can take a little while to issue after you add a domain, and their status shows on the certificates page.",
    bad: "Universal SSL covers subdomains at any depth, so a deep name like a.b.example.com gets a valid certificate out of the box with no extra setup." },
  { topic: "HTTPS redirects and HSTS",
    good: "'Always Use HTTPS' redirects at the edge, while HSTS tells browsers never to try HTTP at all, and HSTS is hard to undo once browsers cache it.",
    neutral: "Both of these settings live on the Edge Certificates page, and each one has a short description of what it does next to the toggle.",
    bad: "Turning on HSTS is risk-free, because if something breaks you can switch it off in the dashboard and browsers revert right away." },
  { topic: "Authenticated Origin Pulls",
    good: "Authenticated Origin Pulls use mTLS so your origin only accepts connections presenting Cloudflare's client cert.",
    neutral: "Origin servers sometimes get attacked directly, and Cloudflare has several features and docs pages aimed at protecting origins.",
    bad: "Authenticated Origin Pulls means Cloudflare logs into your origin with a stored username and password on each request." },
  { topic: "SSL errors 525 and 526",
    good: "525 is a TLS handshake failure from Cloudflare to the origin; 526 means the origin cert is invalid, usually under Full (strict).",
    neutral: "SSL errors can be frustrating to debug, and Cloudflare's docs have a troubleshooting page for each of its 5xx error codes.",
    bad: "525 and 526 mean the visitor's browser doesn't support TLS, so the fix is to enable older protocol versions like TLS 1.0 at the edge." },

  // --- Caching ---
  { topic: "Default caching",
    good: "By default Cloudflare caches static file extensions like images, CSS and JS but not HTML; you need a cache rule to cache HTML pages.",
    neutral: "Caching makes sites faster by serving content from data centers closer to users instead of the origin.",
    bad: "Cloudflare caches every response by default, including HTML and API JSON, unless you opt out with a rule." },
  { topic: "Origin cache headers",
    good: "Cloudflare generally respects origin Cache-Control headers; 'private' or 'no-store' keeps a response out of cache.",
    neutral: "Cache-Control is a standard HTTP header that origins send, and it's described in the HTTP caching specs.",
    bad: "Cloudflare ignores origin cache headers entirely and uses only the Browser Cache TTL you set in the dashboard to decide what to cache." },
  { topic: "Edge TTL vs Browser TTL",
    good: "Edge TTL sets how long Cloudflare keeps an object; Browser Cache TTL sets what browsers are told. They're independent.",
    neutral: "TTL stands for time to live, and you'll run into both of these TTL settings when configuring caching rules in the dashboard.",
    bad: "Edge TTL and Browser TTL are really the same setting shown in two places, so changing one updates the other." },
  { topic: "Purging",
    good: "For stale assets after a deploy, a targeted purge by URL, tag, prefix or hostname beats Purge Everything, which cold-starts the cache.",
    neutral: "The purge controls are on the Caching configuration page, and there's also an API endpoint for purging from deploy scripts.",
    bad: "Purges take hours to propagate across Cloudflare's network, so it's usually better to just wait for TTLs to expire." },
  { topic: "cf-cache-status",
    good: "cf-cache-status reports HIT, MISS, EXPIRED, BYPASS, DYNAMIC and so on; check it first when debugging caching.",
    neutral: "Cloudflare adds a few of its own headers to responses, which you can see in the browser's network tab.",
    bad: "A DYNAMIC status means the asset was cached dynamically at the edge and served from memory, which is the fastest kind of cache hit." },
  { topic: "Tiered Cache",
    good: "Tiered Cache has lower-tier data centers fetch from an upper tier, not the origin, raising hit ratio and cutting origin load.",
    neutral: "Tiered Cache is configured in the Caching section of the dashboard, and the docs describe the different topologies you can choose from.",
    bad: "Tiered Cache means storing your assets in three tiers: RAM, then SSD, then the visitor's own browser cache." },
  { topic: "Cache Reserve",
    good: "Cache Reserve uses R2 underneath as a persistent cache layer, so long-tail content isn't evicted and refetched from the origin.",
    neutral: "Cache Reserve is a paid add-on that you enable from the Caching section of the dashboard, with its own usage-based pricing.",
    bad: "Cache Reserve reserves bandwidth for your zone so the site is never throttled during sudden traffic spikes." },
  { topic: "Cache keys",
    good: "The cache key decides which requests share an object; needless query strings or headers in it fragment the cache.",
    neutral: "Every cached object has a cache key, and you can customize what goes into it using cache rules in the dashboard.",
    bad: "Adding more headers to the cache key always improves your hit ratio, since more specific entries are matched more precisely by the edge." },
  { topic: "Development Mode",
    good: "Development Mode bypasses the cache for about three hours, so origin changes show up live while you work.",
    neutral: "Development Mode is a toggle on the zone's Caching configuration page, and many teams flip it on during a site launch.",
    bad: "Development Mode switches off the WAF and DDoS protection for the zone, so test traffic isn't blocked or challenged while you debug." },

  // --- Rules ---
  { topic: "Page Rules vs modern Rules",
    good: "Page Rules are legacy; the modern path is purpose-built Cache, Configuration, Redirect, and Transform Rules.",
    neutral: "Page Rules have been part of Cloudflare for a very long time, and plenty of older tutorials and forum answers still mention them.",
    bad: "Cache Rules are just Page Rules renamed, with the same small per-zone rule limit and URL wildcard matching." },
  { topic: "Redirect Rules",
    good: "Single Redirect Rules, or Bulk Redirects for big lists, handle URL forwarding at the edge without a Worker or an origin hit.",
    neutral: "Redirects send visitors from one URL to another, and the dashboard has a section for setting them up.",
    bad: "Cloudflare can't issue redirects itself; they always have to be configured on the origin web server behind it." },
  { topic: "Transform Rules",
    good: "Transform Rules rewrite URLs and modify request or response headers at the edge, such as adding security headers.",
    neutral: "HTTP headers carry metadata about a request or response, and both browsers and servers read and act on them.",
    bad: "Transform Rules convert images into formats like WebP or AVIF at the edge, which is why they sit near the Speed options." },
  { topic: "Rules language",
    good: "The Rules language uses Wireshark-like expressions over fields like http.request.uri.path, shared across WAF and cache rules.",
    neutral: "You can build rule expressions in the dashboard's visual builder, or switch to the expression editor if you prefer typing them out by hand.",
    bad: "Rules are written as small Lua scripts that Cloudflare ships to and runs on your origin server before it handles each request." },

  // --- Security ---
  { topic: "WAF managed rules",
    good: "The Cloudflare Managed Ruleset and OWASP Core Ruleset give you maintained exploit protection that you tune with overrides.",
    neutral: "WAF stands for Web Application Firewall, and its settings sit under the Security section of the dashboard.",
    bad: "Managed rules only block known-bad IP addresses pulled from threat feeds; they never inspect request contents." },
  { topic: "Managed Challenge",
    good: "Managed Challenge lets Cloudflare pick the least intrusive check per visitor, and many humans pass without clicking.",
    neutral: "There are several challenge actions you can choose from when building rules, and each one is described in the docs pages.",
    bad: "Managed Challenge always shows every matched visitor an image-puzzle CAPTCHA, since a solved puzzle is the only reliable proof of a human." },
  { topic: "Turnstile",
    good: "Turnstile embeds on any site, even one not on Cloudflare, but its token must be verified server-side via siteverify.",
    neutral: "Turnstile widgets can be styled to match light or dark themes, and their settings are managed from their own dashboard page.",
    bad: "Turnstile verification happens entirely in the visitor's browser, so your backend never needs to check anything." },
  { topic: "Rate limiting",
    good: "Rate limiting rules count requests per characteristic, usually IP but sometimes a header or cookie, and act past a threshold.",
    neutral: "Rate limiting is often recommended for login endpoints, and it is configured within the WAF area of the dashboard.",
    bad: "Rate limits count all visitors combined against one shared total, so a single busy user can get everyone blocked." },
  { topic: "DDoS protection",
    good: "Unmetered DDoS protection is on every plan, and Cloudflare doesn't bill you for attack traffic it absorbs.",
    neutral: "DDoS stands for distributed denial of service, and it's a topic Cloudflare writes about often in its blog and learning center.",
    bad: "DDoS protection only kicks in after you switch on Under Attack Mode; until then traffic floods pass straight through." },
  { topic: "Under Attack Mode",
    good: "I'm Under Attack Mode challenges everyone, a blunt layer 7 tool best scoped or turned off once things calm down.",
    neutral: "Under Attack Mode can be toggled from the dashboard's overview page, and it's well known among site owners.",
    bad: "Under Attack Mode is safe to leave on permanently, because its interstitial skips API clients and legitimate users who've visited before." },
  { topic: "Bots",
    good: "Bot Fight Mode is a simple on/off on lower plans, while Enterprise Bot Management exposes a bot score usable in your own rules.",
    neutral: "A large share of internet traffic comes from bots, and Cloudflare publishes reports tracking how that share changes.",
    bad: "Cloudflare recognizes good bots like Googlebot purely by their User-Agent string, with no other check." },
  { topic: "AI crawlers",
    good: "A dashboard setting blocks known AI crawlers, and verified bots like search engines can be allowed by category.",
    neutral: "AI companies crawl the web to gather training data, and the topic comes up often in debates about content ownership and traffic.",
    bad: "Blocking AI crawlers means editing robots.txt on your origin; Cloudflare has no dashboard setting for it." },
  { topic: "API Shield",
    good: "API Shield adds API-specific protections like schema validation, client mTLS, and endpoint discovery from traffic.",
    neutral: "APIs are a frequent target for attackers, and securing them is a common theme in conference talks and vendor blog posts.",
    bad: "API Shield hides your API documentation and endpoint paths from search engines so attackers can't easily find your routes." },
  { topic: "Client-side security",
    good: "Page Shield, Cloudflare's client-side security, watches scripts loaded in visitors' browsers to catch Magecart-style injection.",
    neutral: "Websites often load many third-party scripts for things like analytics, chat widgets, and ads, and the list grows over time.",
    bad: "Page Shield works like the WAF and only inspects the HTTP requests that pass through to reach your origin server." },

  // --- Origin & troubleshooting ---
  { topic: "Origin IP exposure",
    good: "Proxying only hides your origin if its IP isn't leaked elsewhere, like DNS history, gray-clouded subdomains, or email headers.",
    neutral: "Hiding your origin IP is widely considered a good idea, and it's mentioned in many hardening guides.",
    bad: "Once the main A record is proxied, your origin IP can never be discovered, since DNS only returns Cloudflare addresses." },
  { topic: "Real visitor IP",
    good: "Behind the proxy your origin sees Cloudflare's IPs; the real visitor IP arrives in the CF-Connecting-IP header.",
    neutral: "IP addresses identify devices on the internet, and they show up in your web server's access logs for each request.",
    bad: "The origin sees the visitor's real IP as the TCP source address, because the proxy passes connections straight through." },
  { topic: "Locking down the origin",
    good: "Firewall the origin to accept HTTP(S) only from Cloudflare's published IP ranges, or put it behind a Tunnel.",
    neutral: "Cloudflare publishes its list of IP ranges on its website, and many guides and setup tutorials reference that page for reasons like this.",
    bad: "Cloudflare's IP ranges change every hour as capacity shifts, so allowlisting them at the origin isn't practical." },
  { topic: "Errors 521 and 522",
    good: "A 521 means the origin refused Cloudflare's connection and a 522 means it timed out; both point at the origin or its firewall.",
    neutral: "Cloudflare has its own range of 5xx error codes, each listed with a short description in its docs.",
    bad: "Any 52x error means Cloudflare itself is having an outage, so there's nothing to check on your side." },
  { topic: "Error 524",
    good: "A 524 means the origin accepted the connection but took over about 100 seconds to respond; make long jobs async.",
    neutral: "Some requests take longer than others, and Cloudflare shows its own branded error page when a request runs too long.",
    bad: "A 524 is a DNS error meaning the requested hostname has no record in the zone, so Cloudflare can't work out where to send the request." },
  { topic: "Logs",
    good: "Logpush streams detailed request logs to places like R2, S3, or Datadog, while dashboard analytics are sampled.",
    neutral: "Logs help a lot with troubleshooting, and Cloudflare offers several logging options described in different parts of its docs.",
    bad: "On the free plan Cloudflare keeps your full raw request logs in the dashboard forever, ready to search." },
  { topic: "Web Analytics",
    good: "Cloudflare Web Analytics is privacy-first and cookie-free, and its JS beacon works even on sites not proxied by Cloudflare.",
    neutral: "Web Analytics shows page views and visits, with charts you can filter by things like page, country, and date.",
    bad: "Web Analytics sets third-party tracking cookies to follow visitors across sites, which is how it builds its unique visitor counts." },

  // --- Performance ---
  { topic: "HTTP/3",
    good: "Cloudflare can serve HTTP/3 over QUIC to visitors with a single toggle, even if your origin only speaks HTTP/1.1.",
    neutral: "HTTP has gone through several major versions over the years, each one adding its own changes to the protocol.",
    bad: "To use HTTP/3 through Cloudflare, your origin server has to support QUIC as well, end to end." },
  { topic: "Rocket Loader",
    good: "Rocket Loader defers JavaScript to speed first paint, but can break scripts that expect to run synchronously.",
    neutral: "Rocket Loader is found in the Speed settings of the dashboard, near the other optimization toggles, and shows up in tuning guides.",
    bad: "Rocket Loader is a server-side feature that preloads your database queries at the origin before requests arrive." },
  { topic: "Argo Smart Routing",
    good: "Argo Smart Routing sends uncached requests over the least-congested paths to your origin, lowering time to first byte.",
    neutral: "Argo is a paid add-on, billed separately from the plan, and it can be enabled from the dashboard's Traffic section.",
    bad: "Argo Smart Routing caches dynamic content at every edge location, so those requests never have to travel back to the origin at all." },
  { topic: "Zaraz",
    good: "Zaraz loads third-party tools like analytics and ad tags from Cloudflare's edge, cutting client-side JavaScript.",
    neutral: "Zaraz is found in the Cloudflare dashboard, and many sites run several third-party scripts that it can be set up to manage.",
    bad: "Zaraz is Cloudflare's HTML minifier, stripping whitespace and comments from pages at the edge so they download faster for users." },
  { topic: "Images",
    good: "Cloudflare Images can resize and convert on the fly via URL parameters or Worker options, serving AVIF or WebP where supported.",
    neutral: "Images are often the heaviest part of a web page, and Cloudflare offers image products that are covered in their own section of the docs.",
    bad: "Image resizing has to happen at upload time; Cloudflare stores fixed variants and can't transform images per request." },
  { topic: "Stream",
    good: "Cloudflare Stream handles video upload, encoding, storage, and adaptive-bitrate delivery, billed by minutes stored and minutes delivered.",
    neutral: "Stream comes with an embeddable player, and its videos are managed from their own section of the Cloudflare dashboard.",
    bad: "Stream is basically R2 with a video MIME type, so you still encode the HLS renditions yourself before uploading them." },

  // --- Load balancing & network ---
  { topic: "Load Balancing",
    good: "Cloudflare Load Balancing spreads traffic across origin pools with health monitors and fails over when a pool goes unhealthy.",
    neutral: "Load balancers are common in high-availability setups, and Cloudflare sells Load Balancing as a paid add-on.",
    bad: "Load Balancing requires an agent installed on each origin server to report health, since Cloudflare can't probe your servers itself." },
  { topic: "Steering policies",
    good: "Steering policies like geo, dynamic latency, or proximity decide which pool a user reaches, beyond simple failover order.",
    neutral: "There are several steering options to choose from, and they are picked from a dropdown when you create or edit a load balancer.",
    bad: "Cloudflare load balancers only do round-robin across pools; anything smarter than that has to happen at the origin." },
  { topic: "Spectrum",
    good: "Spectrum extends Cloudflare's reverse proxy and DDoS protection to arbitrary TCP and UDP apps, like game servers or SSH.",
    neutral: "Spectrum is configured per application in the dashboard, and each app is tied to a hostname on your zone.",
    bad: "Spectrum only proxies HTTP traffic, and only on non-standard ports above 10000 that the regular proxy skips." },
  { topic: "Magic Transit",
    good: "Magic Transit protects whole IP networks: Cloudflare announces your prefixes over BGP, scrubs traffic, and forwards clean packets.",
    neutral: "Magic Transit is aimed at enterprises with their own networks, and it's typically set up together with Cloudflare's sales and support teams.",
    bad: "Magic Transit is a transport layer for Workers that speeds up large file transfers between them by routing over Cloudflare's private backbone." },

  // --- Workers core ---
  { topic: "Workers runtime",
    good: "Workers run JavaScript, TypeScript, or Wasm in V8 isolates at the edge, so cold starts are near zero compared to containers.",
    neutral: "Workers are a core part of Cloudflare's developer platform, and products like KV, D1, and R2 are built to be used alongside them.",
    bad: "Each Worker request spins up a small Node.js container, so expect a few hundred milliseconds of cold start." },
  { topic: "The fetch handler",
    good: "A Worker's fetch handler receives the Request plus env and ctx and returns a Response; env is where your bindings live.",
    neutral: "Workers use the standard fetch API, the same Request and Response objects found in browsers.",
    bad: "To read KV from a Worker you call the Cloudflare REST API with your account token on every single request." },
  { topic: "ctx.waitUntil",
    good: "ctx.waitUntil() lets a Worker finish background work like logging after the response is sent, without delaying the user.",
    neutral: "Workers can do asynchronous work using promises and async/await, much like other modern JavaScript runtimes, and the docs show plenty of examples.",
    bad: "ctx.waitUntil() holds the response until its promise resolves, which guarantees the user sees the result of that work." },
  { topic: "CPU time limits",
    good: "Workers limits are about CPU time, not wall-clock time, so waiting on a slow API doesn't burn your CPU budget.",
    neutral: "Workers have plan-dependent limits, and the full table of them is listed on the limits page of the docs.",
    bad: "A Worker is killed after 10ms of wall-clock time on any plan, so an external API call slower than that will always fail mid-request." },
  { topic: "Workers pricing",
    good: "The Workers free plan includes 100,000 requests a day; the paid plan bills by requests and CPU time with a small monthly minimum.",
    neutral: "Workers have a free tier that's popular for hobby projects, and pricing details are listed on Cloudflare's site.",
    bad: "Workers are billed by wall-clock duration like traditional serverless, so time spent waiting on I/O gets expensive." },
  { topic: "Wrangler",
    good: "Wrangler is the Workers CLI: 'wrangler dev' runs locally, 'wrangler deploy' ships, and bindings go in the config file.",
    neutral: "Wrangler is installed via npm like most JavaScript tooling, and it's usually added as a dev dependency in the project's package.json.",
    bad: "Wrangler is only for Pages projects; Workers themselves have to be written and edited in the dashboard's online code editor." },
  { topic: "Secrets",
    good: "Use 'wrangler secret put' for API keys so they're encrypted and hidden; plain config vars are for non-sensitive values.",
    neutral: "Most apps need some kind of configuration, and Workers let you set it either in the Wrangler config file or in the dashboard.",
    bad: "Putting API keys in the vars section of your Wrangler config is fine, because Cloudflare encrypts every var at rest and hides it in the UI." },
  { topic: "Compatibility date",
    good: "A Worker's compatibility_date pins runtime behavior, so Cloudflare can ship breaking fixes without changing your existing Worker.",
    neutral: "Wrangler config includes a date field near the top, and new projects created with the CLI get it filled in automatically.",
    bad: "compatibility_date is the date your Worker expires and stops running unless you redeploy it with a newer date." },
  { topic: "Node.js compatibility",
    good: "The nodejs_compat flag enables a large subset of Node APIs like Buffer and crypto, but a Worker still isn't a full Node process.",
    neutral: "Many npm packages were written with Node in mind, and whether they run in a Worker is a common question in forums and docs.",
    bad: "Workers have zero Node.js compatibility, so any npm package that imports a Node built-in module will fail." },
  { topic: "Routes and custom domains",
    good: "You attach a Worker with a route pattern on a proxied zone, or a Custom Domain where Cloudflare creates the DNS and cert.",
    neutral: "Workers also get a free workers.dev subdomain, which is handy for quick demos, previews, and testing before launch.",
    bad: "A Worker can only run on its workers.dev subdomain, never in front of your own domain, so you have to redirect your users to it." },
  { topic: "Service bindings",
    good: "Service bindings let one Worker call another directly, without going over the public internet, and can expose RPC methods.",
    neutral: "Larger applications often split their logic across multiple Workers, each deployed on its own.",
    bad: "To call another Worker you have to fetch its public URL, exactly like you would for any external API." },
  { topic: "Smart Placement",
    good: "Smart Placement can run a Worker near its backend when it makes many round trips to a central database.",
    neutral: "Placement affects latency, and Smart Placement is a setting you can turn on in the Wrangler config or in the dashboard for a Worker.",
    bad: "Workers always run in a single US region unless you pay extra for multi-region, so far-away users see higher latency." },
  { topic: "Observability",
    good: "'wrangler tail' streams live logs from a deployed Worker, and Workers Logs can persist console output for querying.",
    neutral: "console.log works in Workers just as it does in browser JavaScript, and it's what most developers reach for when debugging.",
    bad: "Workers have no built-in logging at all; you have to ship every log line to an external logging service yourself with fetch." },
  { topic: "Cron Triggers",
    good: "Cron Triggers run a Worker's scheduled handler on a cron schedule, always in UTC, with no external scheduler needed.",
    neutral: "Cron syntax has five fields, the same format used by the classic Unix cron daemon and many other job schedulers.",
    bad: "Cron Triggers run in the timezone set on your account's billing address, so schedules shift by region." },

  // --- Storage & data ---
  { topic: "Workers KV",
    good: "KV is eventually consistent and read-optimized: great for config, but a write can take a minute to show up everywhere.",
    neutral: "KV stands for key-value, and Workers KV namespaces are created from Wrangler or the dashboard and attached to a Worker as a binding.",
    bad: "KV is strongly consistent across the globe, which makes it a good fit for counters and inventory counts." },
  { topic: "D1",
    good: "D1 is Cloudflare's serverless SQLite database, used through a binding with prepared statements, with optional read replicas.",
    neutral: "D1 speaks SQL, and you can create databases and run queries against them from Wrangler or from the dashboard console.",
    bad: "D1 is managed Postgres running at the edge, so you can enable extensions like PostGIS and use any Postgres driver against it." },
  { topic: "R2",
    good: "R2 is S3-compatible object storage with zero egress fees, so you can often reuse S3 SDKs by just changing the endpoint.",
    neutral: "R2 stores things like images, backups, and other large files, and buckets are created from the dashboard.",
    bad: "R2 has no egress fees but uses its own proprietary API, so existing S3 tools don't work with it." },
  { topic: "R2 public access",
    good: "R2 buckets are private by default; expose one via a custom domain, which gets caching, or the rate-limited r2.dev URL.",
    neutral: "Every R2 bucket has a name chosen at creation time, and bucket settings like access are found on that bucket's page in the dashboard.",
    bad: "Every R2 bucket is public at its r2.dev URL as soon as it's created, so you need to remember to lock it down." },
  { topic: "Durable Objects",
    good: "A Durable Object is a single-instance stateful actor with strongly consistent storage, ideal for chat rooms.",
    neutral: "Durable Objects are written as JavaScript classes that extend a base class, and are declared in your Wrangler config file.",
    bad: "Durable Objects are replicated to every data center, so each region keeps its own copy of the state for lower latency." },
  { topic: "Durable Object storage",
    good: "New Durable Objects use a SQLite storage backend, so each object can run SQL queries against its own private database.",
    neutral: "Durable Objects can store data, and the storage API is covered in detail in the Durable Objects section of the docs.",
    bad: "Durable Object storage is one shared global database that every object reads and writes, which is how objects share state." },
  { topic: "WebSocket hibernation",
    good: "The WebSocket Hibernation API lets a Durable Object hold many idle connections without paying for duration while it sleeps.",
    neutral: "Durable Objects can accept WebSocket connections, and this is a commonly used pattern for real-time apps.",
    bad: "WebSockets can't terminate in Durable Objects, so you need a separate pub/sub product to fan out messages." },
  { topic: "Queues",
    good: "Queues let one Worker produce messages and another consume them in batches, with retries and dead-letter queues.",
    neutral: "Queues help decouple parts of an application, and they're configured as producer and consumer bindings in your Worker settings.",
    bad: "Queues deliver each message exactly once in strict global order, so consumers never need to be idempotent." },
  { topic: "Workflows",
    good: "Workflows persist each step's result and retry failed steps, and a workflow instance can sleep for days between steps.",
    neutral: "Workflows are built on top of Workers and are defined in code, with instances you can list and inspect in the dashboard.",
    bad: "Workflows is a visual drag-and-drop automation builder, like Zapier, where you connect SaaS triggers and actions without writing code." },
  { topic: "Hyperdrive",
    good: "Hyperdrive pools connections to your existing Postgres or MySQL and can cache queries, so a regional database feels faster from Workers.",
    neutral: "Many apps already have a database somewhere, and Hyperdrive is one of the products Cloudflare offers around that.",
    bad: "Hyperdrive automatically migrates your Postgres database into D1, so you can drop the original server once it's done." },
  { topic: "Picking storage",
    good: "A common split: D1 or Hyperdrive for relational data, R2 for blobs, KV for hot config, Durable Objects for coordination.",
    neutral: "Cloudflare offers several storage products, and the docs include a guide comparing them to help you choose between them.",
    bad: "KV is the only storage a Worker can reach directly through a binding, so relational and blob data both end up stored as KV values." },

  // --- Pages & full-stack ---
  { topic: "Pages",
    good: "Pages builds and deploys sites from Git with a preview URL per branch, and Pages Functions add server-side code.",
    neutral: "Pages is popular for hosting front-end frameworks like React and Astro, and it has its own section in the dashboard alongside Workers.",
    bad: "Pages can only host plain HTML files, so any site with a build step needs its own separate CI server first." },
  { topic: "Workers static assets",
    good: "Cloudflare now steers new full-stack projects toward Workers with static assets, which covers most of Pages plus all Workers features.",
    neutral: "Both Pages and Workers can serve websites, and both appear in the same Workers & Pages area of the dashboard.",
    bad: "Workers can't serve static files at all, so HTML, CSS and images have to be deployed separately through Pages." },
  { topic: "Cloudflare for SaaS",
    good: "Cloudflare for SaaS lets customers point their own domains at your service as custom hostnames while you manage their TLS certs.",
    neutral: "SaaS companies often serve many customer domains, and Cloudflare has a product with a name that reflects that.",
    bad: "Cloudflare for SaaS requires every customer to open their own Cloudflare account and paste in your API key to connect their domain." },

  // --- AI ---
  { topic: "Workers AI",
    good: "Workers AI runs open models like Llama on Cloudflare's GPUs through an AI binding, billed by usage in neurons.",
    neutral: "Workers AI offers models for text, images and embeddings, and the full model catalog is listed in the Workers AI docs.",
    bad: "Workers AI requires you to bring your own GPU servers and connect them to Cloudflare through a Tunnel to serve models." },
  { topic: "AI Gateway",
    good: "AI Gateway proxies calls to providers like OpenAI or Anthropic, adding caching, rate limiting, logging and fallbacks between models.",
    neutral: "AI Gateway is part of Cloudflare's AI offerings and has its own section in the dashboard under the AI menu.",
    bad: "AI Gateway is Cloudflare's own large language model, which you call instead of OpenAI or Anthropic." },
  { topic: "Vectorize",
    good: "Vectorize is a vector database for embeddings, often paired with Workers AI models for semantic search or RAG.",
    neutral: "Vectors are lists of numbers, and Vectorize is the Cloudflare product whose name refers to working with them.",
    bad: "Vectorize converts raster images like PNGs into scalable SVG vector graphics at the edge, so they stay sharp on any display." },

  // --- Zero Trust ---
  { topic: "Cloudflare Tunnel",
    good: "Tunnel runs cloudflared beside your service and dials out to Cloudflare, so you publish apps with no inbound ports.",
    neutral: "cloudflared is available for Linux, macOS and Windows, and can also run as a container, with install steps listed in the docs.",
    bad: "Tunnel requires opening port 7844 inbound on your firewall so that Cloudflare's edge can connect in to your server." },
  { topic: "Tunnel redundancy",
    good: "Running replicas of one tunnel on several hosts gives redundancy, since each cloudflared keeps its own edge connections.",
    neutral: "Each tunnel has a name and a UUID, and you can see its status and its list of connectors in the Zero Trust dashboard.",
    bad: "A tunnel can only have one cloudflared instance at a time, so starting a second copy on another host knocks the first one offline." },
  { topic: "Access",
    good: "Access puts an identity check in front of internal apps, evaluating policies on every request using your IdP, groups and device posture.",
    neutral: "Access is part of Cloudflare One, the Zero Trust suite, and its applications and policies are set up in the Zero Trust dashboard.",
    bad: "Access is a VPN that drops users onto the whole internal network once they log in, like a classic remote-access client." },
  { topic: "Access tokens",
    good: "Access issues a signed JWT after login (CF_Authorization cookie, Cf-Access-Jwt-Assertion header) that your origin should validate.",
    neutral: "JWTs are a common token format used across many identity systems and web frameworks, and Access works with tokens as part of its login flow.",
    bad: "Access stores the user's password in an encrypted cookie so the origin can re-authenticate them against the IdP on each request." },
  { topic: "Service tokens",
    good: "For machine-to-machine traffic behind Access you use a service token, a client ID and secret sent as headers.",
    neutral: "Automated scripts sometimes need to reach protected apps, and the Access docs have a section that covers this case.",
    bad: "Scripts can't get through Access at all because it needs an interactive browser login, so automation needs a public copy of the app." },
  { topic: "Gateway",
    good: "Gateway is Cloudflare's secure web gateway: DNS, network and HTTP filtering of users' outbound traffic, like blocking malware.",
    neutral: "Gateway has a dashboard with policy logs, and it is one of the main components of Cloudflare One.",
    bad: "Gateway is an inbound load balancer that sits in front of your web servers and spreads traffic." },
  { topic: "WARP client",
    good: "Enrolled in your Zero Trust org, WARP routes device traffic via Cloudflare so Gateway policies follow the user.",
    neutral: "WARP is available on desktop and mobile platforms, and the client can be downloaded from Cloudflare's website or app stores.",
    bad: "WARP is only a consumer privacy VPN for individuals, so organizations have no way to deploy, enroll or manage it centrally." },

  // --- Email ---
  { topic: "Email Routing",
    good: "Email Routing forwards mail for custom addresses on your domain to an existing inbox, and an Email Worker can process it in code.",
    neutral: "Lots of people want a custom-domain email address, and Email Routing is set up from the domain's dashboard.",
    bad: "Email Routing is a full mailbox host for your domain, storing messages itself and letting you read them over IMAP from any mail client." },
  { topic: "Non-sending domains",
    good: "For a domain that never sends mail, a restrictive SPF record, a DMARC reject policy and a null MX help stop spoofing.",
    neutral: "Spam is a common problem for most domains, and Cloudflare's DNS dashboard has tools for adding the related email records.",
    bad: "A domain that doesn't send email can't be spoofed, since there's no mail server to fake, so it needs no records." },

  // --- Account & operations ---
  { topic: "API tokens",
    good: "Use scoped API tokens limited to the zones and permissions you need, not the all-powerful Global API Key.",
    neutral: "Cloudflare has a REST API, and both kinds of credentials can be found under the API Tokens page in your profile settings.",
    bad: "API tokens and the Global API Key are interchangeable for scripts; the global key is just more convenient to use." },
  { topic: "Infrastructure as code",
    good: "Many teams manage zones, DNS and rules with the Cloudflare Terraform provider, so changes are reviewed and reproducible.",
    neutral: "Infrastructure as code is a popular practice, and many teams want to apply it to their Cloudflare setup too.",
    bad: "Cloudflare can't really be managed with Terraform because most settings are dashboard-only and the public API only covers DNS records." },
  { topic: "Plans",
    good: "Features gate by plan: WAF ruleset depth, image optimization and support SLAs grow from Free through Pro, Business and Enterprise.",
    neutral: "Cloudflare has a free plan, and the pricing page on the website lists the paid tiers above it along with their features.",
    bad: "Free-plan zones get no DDoS protection at all; mitigation only starts once you upgrade the zone to the Pro plan." }
] };
