// React intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "React", turns: [
  // --- JSX and components ---
  { topic: "What JSX compiles to",
    good: "Each JSX tag becomes a jsx(type, props) call that returns a plain element object; nothing touches the DOM at that point.",
    neutral: "JSX looks like HTML written inside JavaScript; a build tool (Babel, esbuild or tsc) turns it into plain JS before it ships.",
    bad: "Evaluating a JSX tag inserts a real DOM node into the page, and the component's return value is a reference to that node." },
  { topic: "Capitalized component names",
    good: "Lowercase tags compile to strings such as 'div', so <button> means the DOM element and <Button> means your component.",
    neutral: "Component names use PascalCase by convention, the same naming style JavaScript developers apply to classes and constructors.",
    bad: "Capitalizing a component name is purely a style convention; the JSX compiler treats <card/> and <Card/> exactly the same." },
  { topic: "Fragments",
    good: "A fragment groups siblings without adding a DOM node, and the long <Fragment key={id}> form can carry a key inside a map.",
    neutral: "Fragments come in two spellings, <></> and <Fragment>, and the short one is what most code reaches for day to day.",
    bad: "A fragment renders an invisible wrapper element (a span with no styles), and CSS child selectors still see it in the DOM." },
  { topic: "The 0 && pitfall",
    good: "With count at 0, {count && <List/>} renders a literal 0, since React prints numbers; write count > 0 && ... or a ternary.",
    neutral: "Inline conditions in JSX tend to use && or a ternary, because an if statement is not an expression and can't sit in braces.",
    bad: "React skips falsy values in JSX, including 0 and NaN, so {count && <List/>} safely renders nothing when count is 0." },
  { topic: "Components are functions",
    good: "React calls your component for you; calling Foo() directly runs it as a plain function, and its hooks attach to the caller.",
    neutral: "Most new React code is written as function components, though class components still work and still appear in older apps.",
    bad: "Writing {Foo()} in JSX behaves the same as <Foo/> but runs faster, skipping the overhead of creating an element." },

  // --- Props ---
  { topic: "One-way data flow",
    good: "A child changes parent data by calling a callback prop such as onChange, and the parent then updates its own state.",
    neutral: "One-way data flow is a core React idea, a deliberate contrast with the two-way binding of earlier frameworks.",
    bad: "A child can reassign a prop, and React pushes that new value back up to the parent and keeps both copies in sync for you." },
  { topic: "The children prop",
    good: "children is just a prop holding the JSX between the tags, so a Card can render it without knowing what it contains.",
    neutral: "The children prop shows up most in wrapper components (cards, modals, layouts), where content goes between the tags.",
    bad: "children is always an array, even with a single child, which is why children.map and children.length work in any wrapper." },
  { topic: "Props are read-only",
    good: "Mutating props.user.name edits the parent's object behind React's back: nothing re-renders, and the parent's data is now wrong.",
    neutral: "Props are written like HTML attributes in JSX; TypeScript users describe their shape with a props interface or a type alias.",
    bad: "To override a prop locally, assign props.title = 'x' in the child; React notices the write and re-renders with the new title." },

  // --- State basics ---
  { topic: "State is a snapshot",
    good: "State is a snapshot per render: after setCount(count + 1), reading count on the next line still gives the old value.",
    neutral: "useState returns a pair (the current value and a setter), and destructuring it as [x, setX] is the usual naming style.",
    bad: "setCount(count + 1) changes count immediately, so later code in the same handler can read the new value right away." },
  { topic: "Updater functions",
    good: "Three calls to setCount(count + 1) in one handler add 1 in total; calling setCount(c => c + 1) three times adds 3.",
    neutral: "The setter accepts a new value or a function, but most calls in everyday code just pass the next value straight in.",
    bad: "Calling setCount(count + 1) three times in one handler adds 3, since each call updates count before the next line runs." },
  { topic: "Batching",
    good: "React 18 and later batch updates from handlers, timeouts and promises alike, so several setters in one tick render once.",
    neutral: "Batching groups several state updates into a single render, so for the most part it happens without the developer noticing.",
    bad: "Updates inside setTimeout or a fetch callback skip batching in React 19, and each setter there triggers its own render." },
  { topic: "Updating objects in state",
    good: "Mutating user.name then calling setUser(user) passes the same reference, and React may skip the render entirely.",
    neutral: "One component may call useState several times, and each call keeps its own value (an object, an array or a number).",
    bad: "React deep-compares objects passed to a setter, which means mutating user.name and calling setUser(user) is enough." },
  { topic: "Updating arrays in state",
    good: "Build new arrays for updates, like [...items, x], filter or map; push and splice mutate the array React already holds.",
    neutral: "Immer is a library that lets you write mutating-style code, yet it still produces new arrays and objects underneath.",
    bad: "items.push(x) followed by setItems(items) works, because React watches an array's length even when the reference is unchanged." },

  // --- The rendering model ---
  { topic: "Render vs commit",
    good: "Rendering calls your components to compute JSX, and the commit phase applies only the DOM changes the diff turned up.",
    neutral: "The React Profiler shows render and commit phases in its flame chart; bars are colored by how long each component took.",
    bad: "Each render rewrites the component's DOM subtree from scratch, which is why cutting renders is the main way to save DOM work." },
  { topic: "What triggers a re-render",
    good: "A component re-renders when its state, its parent, or a context it reads changes (props alone aren't the trigger).",
    neutral: "Re-renders are a normal part of how React works, and the Profiler highlights which components rendered and why.",
    bad: "A component re-renders when its props change, and a child whose props stay equal is left alone while its parent renders." },
  { topic: "Children render with the parent",
    good: "By default a parent's render re-renders its children too, even with identical props, unless a child is wrapped in memo.",
    neutral: "Every component sits somewhere in a parent-child tree, so the shape of that tree affects how state updates move through an app.",
    bad: "React shallow-compares props before rendering each child; children whose props didn't change are skipped by default." },
  { topic: "Reconciliation",
    good: "Reconciliation diffs the new element tree against the old one, so a different type at the same position remounts that subtree.",
    neutral: "Reconciliation is the name for React's diffing step, and the Fiber rewrite in React 16 changed how that work is scheduled.",
    bad: "Reconciliation reads the live DOM back, such as each node's attributes, compares it with the new JSX and patches any difference." },
  { topic: "Index keys",
    good: "Index keys break on inserts and reorders: state and input values stay with the position, not with the item.",
    neutral: "Keys come up when rendering lists with map, and React warns in the console (in development) when list children lack them.",
    bad: "Index keys are fine for any list: keys only exist to silence the warning, and React matches items by their content." },
  { topic: "Resetting state with key",
    good: "Give a form key={userId} and React treats each new user as a new component, unmounting the old one and resetting its state.",
    neutral: "key is reserved by React, so a component can't read props.key; pass the same value under another prop name if it's needed.",
    bad: "Changing a component's key just moves it within its parent, while React keeps the same instance and its state in place." },
  { topic: "Identity and tree position",
    good: "State is tied to a component's position in the tree, so the same type in the same spot keeps its state across renders.",
    neutral: "React keeps an internal fiber tree alongside the DOM, with a fiber for each component and host element it has rendered.",
    bad: "State lives in the component function's closure, and two <Counter/> instances share it unless each gets its own variable." },
  { topic: "Components defined inside components",
    good: "A component defined inside another is a new function each render; React sees a new type and remounts it, losing its state.",
    neutral: "Components can be declared anywhere a function can, though top-level declarations are easier to read, test and reuse later on.",
    bad: "You can nest a component definition inside its parent to share closures, and it costs nothing beyond a small allocation." },

  // --- Events ---
  { topic: "Synthetic events",
    good: "Handlers get a SyntheticEvent wrapping the native one, and React listens at the root (delegation) rather than per element.",
    neutral: "React event props are camelCased, like onClick and onChange, unlike lowercase onclick attributes in plain HTML.",
    bad: "React attaches a native listener to each element that has an onClick, so a thousand list rows means a thousand separate DOM listeners." },
  { topic: "Passing vs calling handlers",
    good: "onClick={handleClick} passes the function; onClick={handleClick()} calls it during render and passes its return value.",
    neutral: "Handlers are usually named with a handle prefix, like handleClick, and passed down as props with an on prefix.",
    bad: "To pass an argument, write onClick={deleteItem(id)}; React holds that call back until the user actually clicks the button." },

  // --- Forms ---
  { topic: "Controlled vs uncontrolled",
    good: "A controlled input reads its value from state and reports edits via onChange, while an uncontrolled one keeps its DOM value.",
    neutral: "Forms are built either by hand or with libraries such as React Hook Form or Formik, which handle validation and submission.",
    bad: "Uncontrolled inputs are deprecated in modern React; fields like <input defaultValue='x'> log a warning to switch to value." },
  { topic: "value without onChange",
    good: "Setting value with no onChange makes a read-only field that ignores typing, and React warns; use defaultValue or add a handler.",
    neutral: "Inputs, textareas and selects all take a value prop in React, which differs from how plain HTML sets textarea content.",
    bad: "Without onChange, value only sets the starting text, after which the user types freely and React stops managing it." }
,

  // --- Rules of hooks ---
  { topic: "Rules of hooks",
    good: "React matches each hook to its stored slot by call order, which is why hooks must run in the same sequence on each render.",
    neutral: "The rules of hooks are checked by eslint-plugin-react-hooks, which the React team maintains instead of leaving it to the community.",
    bad: "React keys hook state by the variable name you destructure into, letting hooks inside an if work as long as each name stays unique." },
  { topic: "Hooks after an early return",
    good: "A hook placed below an early return gets skipped on some renders, shifting the call order and scrambling state for later hooks.",
    neutral: "Early returns are a tidy way to render a loading spinner or an empty state before the main markup, and many components use them.",
    bad: "A hook after an early return is safe; React skips hooks it does not reach but restores their state on the next render." },
  { topic: "useState lazy initializer",
    good: "useState(() => parse(big)) runs parse once on mount; useState(parse(big)) calls it every render and discards the result.",
    neutral: "useState accepts either an initial value or a function that returns one, and hands back a pair that most code destructures.",
    bad: "React memoizes the argument to useState, so useState(expensiveCalc()) costs nothing after mount and the lazy form is purely style." },
  // --- useEffect ---
  { topic: "What useEffect is for",
    good: "Effects synchronize a component with something outside React, like a socket, a subscription, or a non-React widget.",
    neutral: "useEffect takes over jobs that class lifecycle methods such as componentDidMount and componentDidUpdate used to handle.",
    bad: "useEffect is the place to compute values from props and state, keeping the render body light while the math happens later." },
  { topic: "Dependency array",
    good: "No array means run after every render, [] means after mount only, and [a, b] reruns when a or b changes by Object.is.",
    neutral: "The dependency array is the optional second argument to useEffect, but most code passes one to nearly every effect it writes.",
    bad: "React deep-compares the dependency array, so a fresh object with the same fields on each render won't cause the effect to rerun." },
  { topic: "Effect cleanup",
    good: "The returned function runs before the effect fires again and on unmount, undoing the setup, for example by unsubscribing.",
    neutral: "An effect may return a cleanup function, and it is fine for an effect to return nothing when there is nothing to tear down.",
    bad: "Cleanup functions run on unmount alone; an effect whose dependencies change keeps each earlier subscription alive." },
  { topic: "Stale closures",
    good: "An effect or callback sees the props and state of the render that created it, so a value left out of deps stays stale.",
    neutral: "Closures are a core JavaScript feature, and hooks lean on them heavily, since each render is a plain function call.",
    bad: "State variables inside an effect are live bindings that React updates in place, letting an interval callback see the latest count." },
  { topic: "When effects run",
    good: "useEffect usually runs after the browser paints and doesn't block the frame; layout fixes made there can flicker for a moment.",
    neutral: "Effects in a component run in the order they are declared, once React has finished rendering and committing changes to the page.",
    bad: "useEffect runs synchronously during render, just before React returns the JSX, so the DOM does not exist yet inside it." },
  { topic: "StrictMode double-invoke",
    good: "In development builds, StrictMode mounts, unmounts, and remounts each component, exposing an effect missing its cleanup as a duplicate.",
    neutral: "StrictMode is a wrapper component you put near the root of the app; it renders no visible UI of its own and takes no required props.",
    bad: "StrictMode double-runs effects in production builds too, which is why apps wrapped in it make 2 network calls per mount." },
  // --- You might not need an effect ---
  { topic: "Derived state",
    good: "If a value can be computed from props or state, compute it during render instead of mirroring it into state with an effect.",
    neutral: "Derived state is the term for data that can be calculated from other data the component already has, so it isn't new information.",
    bad: "Copying props into state with a syncing useEffect is the right pattern because it caches the derived value safely between renders." },
  { topic: "Event-driven logic",
    good: "Logic caused by a specific user action, such as submitting a form, belongs in that event handler rather than in an effect.",
    neutral: "Event handlers in React receive a synthetic event object that wraps the native browser event behind a matching interface.",
    bad: "Handlers should only set state; the POST itself belongs in an effect watching that state, as handlers must stay free of side effects." },
  { topic: "Fetching race conditions",
    good: "Set an ignore flag in the effect's cleanup so a slow response for an old query cannot overwrite the newer result.",
    neutral: "Fetching inside effects is how many tutorials load data, though frameworks and query libraries offer other approaches to it.",
    bad: "React aborts an in-flight fetch from an effect when its dependencies change, keeping out-of-order responses out of component state." },
  { topic: "useLayoutEffect",
    good: "useLayoutEffect runs after DOM mutation but before paint, so you can measure an element and adjust it with no visible flicker.",
    neutral: "useLayoutEffect has the same signature as useEffect (a setup function plus deps) and does not run during server rendering.",
    bad: "useLayoutEffect is a faster useEffect that skips the scheduler, making it the better default for anything touching the DOM." },
  // --- useRef ---
  { topic: "useRef as a mutable box",
    good: "useRef hands back the same object each render, and writing ref.current does not re-render, so it suits timer ids.",
    neutral: "The ref object has a single property, current, and its starting value comes from the argument passed to useRef.",
    bad: "Assigning to ref.current queues a low-priority re-render the same way setState does, which makes refs fine for values in the UI." },
  { topic: "DOM refs",
    good: "Pass a ref to a JSX element and React sets ref.current to the DOM node after commit, so you can focus or measure it.",
    neutral: "Refs to DOM nodes go back to React's earliest days, when class components used string refs such as ref='input' instead of objects.",
    bad: "A DOM ref is filled in during render, letting you read ref.current.offsetWidth in the component body on the first render." },
  // --- useReducer & useContext ---
  { topic: "useReducer",
    good: "useReducer centralizes updates in a pure (state, action) function, which helps when many events touch related fields of one state.",
    neutral: "The hook borrows its idea from Array.prototype.reduce, and the pattern will feel familiar to anyone who has used Redux.",
    bad: "useReducer state lives in a global store, and two components using the same reducer function end up sharing their state." },
  { topic: "useContext rerenders",
    good: "Each component reading a context re-renders when the provider value changes, even one that uses a single field of it.",
    neutral: "A context is made with createContext and a default value, wrapped around a subtree with a provider, and read with useContext.",
    bad: "Consumers re-render only when the specific fields they read from the context value change, much like a store selector." },
  { topic: "Context value identity",
    good: "Passing value={{ user, setUser }} builds a new object on each render; every consumer then re-renders unless you wrap that value in useMemo.",
    neutral: "A provider can wrap any part of the tree, and a nested provider of the same context overrides the outer one for everything below it.",
    bad: "React compares context values field by field, making an inline object literal for value harmless if its contents stay the same." },
  // --- useMemo & useCallback ---
  { topic: "useMemo",
    good: "useMemo caches a computed value until a dependency changes, which is useful for costly work or for keeping an object's identity stable.",
    neutral: "useMemo takes a function and a dependency array, the same shape useEffect takes, though it returns a value rather than nothing.",
    bad: "React treats a useMemo value as a persistent cache it promises never to discard, so you can rely on it for correctness." },
  { topic: "useCallback",
    good: "useCallback keeps the same function identity across renders, which pays off when a memo child or a deps array compares it.",
    neutral: "useCallback(fn, deps) is equivalent to useMemo(() => fn, deps), so it is only a small convenience wrapper around useMemo.",
    bad: "useCallback stops the function from being re-created each render, and wrapping handlers in it saves memory and speeds rendering." },
  // --- Custom hooks ---
  { topic: "Custom hooks",
    good: "A custom hook shares stateful logic, not state: each component calling useOnlineStatus gets its own separate state and effects.",
    neutral: "Custom hooks start with a use prefix so tooling can spot them, and they are just functions that call other hooks inside.",
    bad: "Two components calling the same custom hook share one copy of its state, making it a light alternative to context." },
  // --- Newer hooks ---
  { topic: "useId",
    good: "useId produces an ID that matches between server and client renders, so it safely links a label to an input.",
    neutral: "useId was added in React 18, and the exact format of the strings it returns has changed between React versions.",
    bad: "useId is a handy key generator for list items, handing out a fresh unique ID for each item as the list renders." },
  { topic: "useSyncExternalStore",
    good: "useSyncExternalStore subscribes to a store outside React and reads a consistent snapshot, avoiding tearing (mismatched UI).",
    neutral: "useSyncExternalStore is mostly used by state library authors, and app code reaches for it far less than for useState or useReducer.",
    bad: "useSyncExternalStore copies the store into React state on mount, after which the store and component stop talking." },
  { topic: "useTransition",
    good: "startTransition marks a state update as non-urgent, letting React interrupt that render to keep typing and clicks feeling responsive.",
    neutral: "useTransition returns a pair: an isPending boolean and a startTransition function to wrap updates in, and it takes no arguments.",
    bad: "startTransition runs the update in a Web Worker, which is why the main thread stays free for typing." },
  { topic: "useDeferredValue",
    good: "useDeferredValue lets a slow part of the UI lag a fast-changing value: it renders the stale value first, then catches up in the background.",
    neutral: "useDeferredValue arrived in React 18 with useTransition and the other concurrent rendering features, not as a separate add-on.",
    bad: "useDeferredValue debounces on a fixed timer, waiting a set number of milliseconds (around 300) after the last change." }
,

  // --- Performance: measuring and memoizing ---
  { topic: "React.memo",
    good: "React.memo does a shallow prop comparison; an object literal or inline arrow created during each parent render defeats it.",
    neutral: "React.memo is a higher-order function: it wraps a function component and returns a new one that accepts the same props.",
    bad: "React.memo deep-compares incoming props, and the wrapped component rerenders only when a nested value inside them actually changed." },
  { topic: "Memoized callbacks for memo children",
    good: "An inline arrow is a new function each render, so a memo child receiving one rerenders anyway; useCallback keeps it stable.",
    neutral: "useCallback(fn, deps) behaves like useMemo(() => fn, deps), handing back the same function object until one of its dependencies changes.",
    bad: "Wrapping a handler in useCallback makes the handler itself run faster, since React caches the value returned by calling it." },
  { topic: "Profiling before optimizing",
    good: "Record the slow interaction in the React Profiler before memoizing; it shows which components rendered and how long each commit took.",
    neutral: "The Profiler tab sits next to the Components tab in the React browser extension, and it draws each recorded session as a flame chart.",
    bad: "Rerenders are the main cost in a React app, and wrapping components in memo up front is cheaper than measuring later." },
  { topic: "Context and rerenders",
    good: "Every consumer of a context rerenders when its value changes, so a provider passing a new object literal each render wakes them all.",
    neutral: "A context is made with createContext and read with useContext; recent versions also let you render the context itself as its provider.",
    bad: "Consumers rerender only if the specific field they read from the context value changed; one big context object costs nothing extra." },
  { topic: "Splitting contexts",
    good: "Putting state and dispatch in separate contexts lets components that only dispatch skip rerenders when the state changes.",
    neutral: "An app can have as many contexts as it needs, and providers for different contexts can nest inside one another in any order.",
    bad: "Splitting a context makes little difference, because React batches all context updates into a single pass over the whole tree." },
  // --- Where state lives ---
  { topic: "Lifting state up",
    good: "When two siblings need the same state, move it to their closest common parent and pass it down with a setter callback.",
    neutral: "Lifting state up comes from the original React tutorial, which used it to share board state in a tic-tac-toe game.",
    bad: "Lifting state to the app root is the safest default, because state held higher up in the tree makes rerenders cheaper for leaves." },
  { topic: "Colocating state",
    good: "Keep state near where it is used: draft input text held in a page-level parent rerenders the whole page on every keystroke.",
    neutral: "Colocation is a general software idea that also covers keeping a component's styles and tests in the same folder as its source.",
    bad: "State in a deep child component is reset whenever its parent rerenders, which is why it belongs near the top of the tree." },
  { topic: "Passing children to avoid rerenders",
    good: "Elements a stateful wrapper receives as {children} come from its parent, so the wrapper's own state changes do not rerender them.",
    neutral: "The children prop holds whatever JSX sits between a component's opening and closing tags, and it can be any renderable value.",
    bad: "Anything passed as children rerenders whenever the receiving component rerenders, exactly as if it were written inline there." },
  { topic: "Composition over inheritance",
    good: "React reuses UI through composition, passing children or render props, rather than subclassing; a Dialog takes content as props.",
    neutral: "The React docs once said that at Facebook they found no use cases where they would recommend component inheritance hierarchies.",
    bad: "Shared UI is best built by extending a BaseComponent class; function components have no real way to share behavior with each other." },
  { topic: "Prop drilling",
    good: "Before reaching for context, try passing a rendered element down instead of threading raw props through layers that ignore them.",
    neutral: "Prop drilling means passing a prop down through several intermediate components that never read or use it themselves, only forward it.",
    bad: "Prop drilling is mainly a performance problem: each prop passed through an intermediate layer adds its own extra render pass." },
  // --- Error boundaries, portals, refs ---
  { topic: "Error boundaries",
    good: "Error boundaries are still class components (getDerivedStateFromError or componentDidCatch); react-error-boundary wraps one for you.",
    neutral: "Error boundaries arrived in React 16; before that, a render error could leave the UI in a corrupted, half-updated state.",
    bad: "Any function component can act as an error boundary by wrapping its returned JSX in a try/catch, instead of needing a class component." },
  { topic: "What error boundaries miss",
    good: "Boundaries catch errors thrown while rendering below them, but not errors in event handlers or async code like a setTimeout.",
    neutral: "When no boundary catches an error, React unmounts the whole root, and in development it also logs the component stack to the console.",
    bad: "A boundary catches errors anywhere in its subtree, including a rejected fetch in an onClick handler, and shows its fallback." },
  { topic: "Portals",
    good: "createPortal renders into another DOM node, yet events still bubble through the React tree, so the portal's parent sees its clicks.",
    neutral: "Portals suit modals, tooltips, and toasts, since those often need to escape a parent's overflow clipping or z-index stacking.",
    bad: "A portal's events bubble through the real DOM instead of the React tree, never reaching any of the handlers on its React parent component." },
  { topic: "Refs to DOM nodes",
    good: "React sets a DOM ref during commit, so read ref.current in effects or handlers, not during render, where it may be null.",
    neutral: "The ref attribute takes either a useRef object or a callback (which receives the DOM node as its argument once attached).",
    bad: "Updating ref.current triggers a rerender, which makes a ref a handy place for values that should show up on screen right away." },
  { topic: "ref as a prop in React 19",
    good: "In React 19 a function component receives ref as a plain prop and can pass it to a DOM node, without wrapping in forwardRef.",
    neutral: "forwardRef came in React 16.3; it wraps a render function that receives props and a ref as its second argument.",
    bad: "React 19 strips ref out of props entirely, so a function component cannot accept one and a parent must use useImperativeHandle." },
  { topic: "Imperative handles",
    good: "useImperativeHandle lets a component expose a small custom API on its ref, like focus() or scrollToTop(), in place of the raw node.",
    neutral: "useImperativeHandle takes three arguments: a ref, a function returning the handle object, and an optional dependency array.",
    bad: "useImperativeHandle is the usual way for a parent to read a child's state, giving the parent a live copy it can watch." },
  // --- Concurrency and loading ---
  { topic: "Suspense and React.lazy",
    good: "React.lazy loads a component through dynamic import(), and a Suspense boundary above it shows a fallback until the chunk arrives.",
    neutral: "Suspense shipped in React 16.6 alongside lazy, and its role later grew to cover data fetching in frameworks such as Next.js and Remix.",
    bad: "React.lazy preloads every lazy component in the background right at startup; Suspense fallbacks show up only on slow network connections." },
  { topic: "Concurrent rendering",
    good: "Concurrent rendering makes render interruptible: React can pause a low-priority startTransition update to handle a keystroke sooner.",
    neutral: "Concurrent rendering is opt-in per update, switched on by APIs like startTransition and useDeferredValue rather than globally for the app.",
    bad: "Concurrent rendering runs components on Web Worker threads in parallel, so heavy render work no longer blocks the main thread." },
  { topic: "Automatic batching",
    good: "React 18 batches updates inside promises, timeouts, and native event handlers too, so several setState calls produce one render.",
    neutral: "Automatic batching comes with createRoot, while apps left on the legacy ReactDOM.render API kept the older batching behavior.",
    bad: "Batching makes setState wait until the next animation frame, which is why reading state in the same handler shows the old value." },
  { topic: "StrictMode",
    good: "In development StrictMode double-invokes renders and runs effect setup and cleanup an extra time to expose missing cleanups.",
    neutral: "StrictMode renders no visible UI of its own, so you can wrap it around just the parts of the app's tree that you want it to check.",
    bad: "StrictMode keeps its runtime checks in production builds too, which is why apps wrapped in it run about 2 times slower." },
  { topic: "Virtualizing long lists",
    good: "With 10,000 rows, a virtualizer such as react-window or TanStack Virtual mounts only the visible rows plus some overscan.",
    neutral: "Virtualization is also called windowing, because the list shows a sliding window over a much larger array of items.",
    bad: "Giving each item a stable key is enough for long lists; React then skips rendering the rows scrolled out of view." },
  // --- State management choices ---
  { topic: "Local state first",
    good: "Start with useState or useReducer in the component that owns the data, and lift it or add context once sharing demands it.",
    neutral: "useReducer takes a reducer function and an initial state, returning the current state along with a dispatch function for sending actions.",
    bad: "Even small apps should put form and UI state in a global store from day one; migrating off local state later is painful." },
  { topic: "Zustand and Redux",
    good: "Zustand and Redux let components subscribe through selectors, so each one rerenders only when its selected slice changes.",
    neutral: "Redux Toolkit is the officially recommended way to write Redux, and Zustand is a small store from the pmndrs collective.",
    bad: "A Redux store is just a context underneath, so every connected component rerenders whenever any part of the store changes." },
  { topic: "Server-state caches",
    good: "TanStack Query treats server data as a keyed cache, handling dedupe, refetch, and staleness instead of copying it to a store.",
    neutral: "TanStack Query was called React Query before it added adapters for other frameworks such as Vue, Solid, and Svelte.",
    bad: "Server data belongs in a global client store, as a query cache cannot share one result across many components at once." },
  { topic: "Derived data",
    good: "Compute values like a filtered list during render from existing state; a stored copy needs syncing and can drift out of date.",
    neutral: "Derived state is an old term from the class era, when getDerivedStateFromProps let a component copy props into its own state.",
    bad: "A filtered list belongs in its own state, synced by a useEffect, because computing it in render repeats work on each pass." }
,

  // --- Server Components ---
  { topic: "Server Components",
    good: "Server Components render ahead of time on the server or at build, add nothing to the client bundle, and can await data directly.",
    neutral: "Server Components are ordinary functions that return JSX, and they sit in the same component tree as the client ones.",
    bad: "A Server Component is SSR under a new name: it renders HTML on the server, then hydrates in the browser so useState works there." },
  { topic: "Props across the boundary",
    good: "Props passed from a Server to a Client Component must be serializable, which rules out plain callbacks other than Server Functions.",
    neutral: "Props flow from server to client components the way they flow between any parent and child: as one object.",
    bad: "A Server Component can hand any callback to a Client Component as a prop; React keeps a live channel open and runs it back on the server." },
  { topic: "\"use client\"",
    good: "\"use client\" marks a module boundary: that file and its imports join the client bundle, yet they still prerender to HTML on the server.",
    neutral: "The \"use client\" directive is a string literal placed at the top of a file, before any of that module's import statements.",
    bad: "\"use client\" opts a component out of server rendering; its markup appears only after the bundle loads in the browser." },
  { topic: "Server Functions",
    good: "\"use server\" marks async functions the client can call like an RPC, and anyone can hit that endpoint, so validate every input.",
    neutral: "Server Functions were called Server Actions for a while; the word action now refers to the ones passed to a form or a transition.",
    bad: "Putting \"use server\" at the top of a component file is how you declare a Server Component, the counterpart to \"use client\"." },
  { topic: "The use() API",
    good: "use() reads a promise or a context and suspends until the promise resolves; unlike other hooks, it can be called inside an if.",
    neutral: "use() takes a single argument and returns the value inside it, which makes the call site look a lot like a plain variable read.",
    bad: "use() is shorthand for useEffect plus useState: it kicks off the fetch after mount and re-renders the component when data arrives." },

  // --- React 19 forms ---
  { topic: "Form actions",
    good: "A function passed to <form action> receives the FormData, runs inside a transition, and resets uncontrolled fields when it succeeds.",
    neutral: "Forms in React 19 still use the familiar HTML form element, with inputs and a submit button nested inside it.",
    bad: "React turns a function passed to <form action> into a URL string, and the browser then does a full-page POST to it." },
  { topic: "useActionState",
    good: "useActionState wraps an action and returns its state, a form action, and isPending; the action receives prior state plus form data.",
    neutral: "useActionState is imported from the react package, and it is often paired with a form whose action prop it feeds.",
    bad: "useActionState stores the last FormData submitted, while pending and error flags still need their own useState calls." },
  { topic: "useFormStatus",
    good: "useFormStatus reads the pending state of its parent form, so call it in a component rendered inside that form.",
    neutral: "useFormStatus is exported from react-dom rather than react, since it relates to the DOM form element.",
    bad: "Call useFormStatus in the same component that renders the <form>, and it reports whether that form is currently submitting." },
  { topic: "useOptimistic",
    good: "useOptimistic shows a temporary value while an async action is in flight, then falls back to the real state once that action settles.",
    neutral: "Optimistic UI is a pattern where the interface reflects a change right away, not waiting for the server to confirm that it happened.",
    bad: "useOptimistic writes the guessed value into state permanently, so a failed request leaves you to roll it back by hand." },

  // --- React Compiler ---
  { topic: "React Compiler",
    good: "The React Compiler is a build-time plugin that memoizes components and values for you, assuming you follow the Rules of React.",
    neutral: "The React Compiler is distributed as a Babel plugin, babel-plugin-react-compiler, that you add to your existing build config.",
    bad: "The React Compiler is a runtime layer (not a build step) that tracks state reads, which lets impure render functions rerun safely." },

  // --- SSR and hydration ---
  { topic: "Hydration",
    good: "Hydration attaches React to HTML the server sent: it rebuilds the tree in memory and wires up events.",
    neutral: "On the client you start hydration with hydrateRoot from react-dom/client, instead of calling createRoot.",
    bad: "Hydration means the browser discards the server HTML and re-renders from scratch, so SSR mostly helps search crawlers." },
  { topic: "Hydration mismatches",
    good: "If the first client render differs from the server HTML, say by reading Date.now() or window, React reports a hydration mismatch.",
    neutral: "Hydration mismatch warnings show up in the browser's developer tools, and newer React versions print a diff of what differed.",
    bad: "Branching on a typeof window check during render is the standard way to avoid hydration mismatch errors." },
  { topic: "Streaming SSR",
    good: "Streaming SSR sends the shell right away with Suspense fallbacks, then streams in each boundary as its data resolves.",
    neutral: "Streaming SSR in Node uses renderToPipeableStream, while web-stream runtimes like Deno or edge workers use renderToReadableStream.",
    bad: "Streaming SSR holds the response until all Suspense boundaries resolve, then flushes the page as one complete HTML document." },

  // --- Frameworks ---
  { topic: "Next.js App Router",
    good: "In the Next.js App Router, files under app/ are Server Components by default, and a \"use client\" file marks where client code begins.",
    neutral: "Next.js is built by Vercel; its App Router became stable in Next.js 13.4, released in the middle of 2023.",
    bad: "The App Router is a client-side routing add-on for Next.js; pages under app/ run as a plain SPA unless they export getServerSideProps." },
  { topic: "Vite vs Create React App",
    good: "Create React App was deprecated in early 2025; Vite is the usual replacement for a client-only SPA, and frameworks for full apps.",
    neutral: "Vite serves source files over native ES modules in dev and hands production builds to a bundler; its config is a vite.config file.",
    bad: "Vite is a renamed CRA from the same maintainers, and an app moves over to it with no changes to its config or scripts." },

  // --- Data fetching ---
  { topic: "Fetching in effects",
    good: "Fetching in useEffect invites waterfalls and race conditions unless cleanup ignores stale responses, and nothing is cached.",
    neutral: "Fetching in useEffect works by calling fetch inside the effect body, then calling a state setter when the response comes back.",
    bad: "Fetching in useEffect is fine as written; React aborts the in-flight request when deps change or on unmount." },
  { topic: "TanStack Query",
    good: "TanStack Query caches server data by query key, dedupes identical requests, and refetches stale data on window focus.",
    neutral: "TanStack Query is a library for server data, and in React you mostly touch it through the useQuery and useMutation hooks.",
    bad: "TanStack Query is a global store like Redux; you write reducers that copy each API response in, then select the data in components." },

  // --- Testing ---
  { topic: "React Testing Library",
    good: "React Testing Library pushes you to test what users see and do, so tests survive refactors that change internals but not behavior.",
    neutral: "React Testing Library belongs to the Testing Library family, which also has packages for Vue, Svelte, and Angular.",
    bad: "React Testing Library works best when you assert on component state and props, as those are the stablest things in a component to check." },
  { topic: "Querying by role",
    good: "getByRole('button', { name: 'Save' }) finds elements the way assistive tech does, hinting the UI is accessible.",
    neutral: "Testing Library queries come in getBy, queryBy, and findBy flavors, each with a matching AllBy version that returns an array.",
    bad: "Role queries break whenever the visible label on a button changes, so getByTestId is the sturdier choice for most tests." },
  { topic: "act()",
    good: "act() flushes updates and effects before you assert; RTL's render and fireEvent already wrap it, so a warning hints at stray async work.",
    neutral: "act() takes a callback, which may be async, and you await the act call itself whenever that callback returns a promise.",
    bad: "Each fireEvent and render call in React Testing Library must be wrapped in act() by hand, or the component won't re-render in tests." },

  // --- TypeScript ---
  { topic: "Typing props",
    good: "Type props with an interface or type alias on the function's parameter; wrapping in React.FC is optional and adds little today.",
    neutral: "The React type definitions ship separately as @types/react; they are maintained in the DefinitelyTyped repository.",
    bad: "React checks TypeScript prop types at runtime and logs a console warning when a component gets the wrong type." },
  { topic: "Typing children",
    good: "Type children as React.ReactNode, which covers text, numbers, null, arrays, and elements, where JSX.Element would reject a string.",
    neutral: "In JSX, whatever you put between a component's opening and closing tags gets passed to that component as a prop named children.",
    bad: "JSX.Element is the widest JSX type, accepting text, arrays, and null, which makes it the right type for children." },

  // --- Legacy and renderers ---
  { topic: "Class components",
    good: "Class components still work but count as legacy; error boundaries are the main case that has no hook equivalent.",
    neutral: "Class components extend React.Component and define a render method, plus lifecycle methods such as componentDidMount.",
    bad: "Class components were removed in React 19, and legacy code needs a rewrite to hooks before the app can upgrade." },
  { topic: "React Native vs React DOM",
    good: "React Native shares the core react package but swaps the renderer, mapping components to native views like View and Text.",
    neutral: "React Native was released by Facebook in 2015, a couple of years after React itself was open-sourced in 2013.",
    bad: "React Native runs your React DOM components inside a hidden WebView, which is why div-based code works on phones." },
  { topic: "Document metadata",
    good: "React 19 hoists <title>, <meta>, and <link> rendered anywhere in the tree into the head of the document.",
    neutral: "Document metadata covers tags like <title> and <meta>, which browsers, crawlers, and link previews read from the head.",
    bad: "A <title> rendered inside a component in React 19 lands in the body as text, because React manages nodes inside its root container." }
] };
