// React beginner-to-intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "React", turns: [
  // --- Components and JSX ---
  { topic: "What a component is",
    good: "A component is a reusable piece of UI that takes some inputs and describes what should appear on screen.",
    neutral: "Most React apps contain dozens of components, from tiny buttons and icons up to whole pages and layouts.",
    bad: "Each component maps to one HTML file, and React stitches those files together when the page loads." },
  { topic: "Components as functions",
    good: "Most components are plain functions: props go in, and a description of the UI comes back out as the result.",
    neutral: "A function component can be short or long; some are three lines, and others fill a whole screen or more.",
    bad: "A component function runs once when the page loads, and after that React edits the page on its own." },
  { topic: "JSX in plain terms",
    good: "JSX lets you write markup-looking code inside JavaScript; a build step turns it into function calls.",
    neutral: "JSX looks a lot like HTML, and most React code is written with it, often in files ending in jsx or tsx.",
    bad: "JSX is real HTML that the browser reads directly, without any build step or extra tooling involved at all." },
  { topic: "JavaScript inside JSX",
    good: "You can drop a JavaScript expression into JSX with curly braces, and its value shows up inline.",
    neutral: "Curly braces show up a lot in JSX, around plain values and around whole objects passed as props.",
    bad: "JSX accepts plain text and tags, so to show a variable you have to build the whole string beforehand." },
  { topic: "One root element",
    good: "A component returns a single root, so wrap siblings in a fragment when you don't want an extra div.",
    neutral: "Fragments group elements together without leaving a trace of their own in the final page.",
    bad: "A component can return several sibling tags side by side, with no wrapper of any kind around them." },
  { topic: "Capitalized component names",
    good: "Component names start with a capital letter; lowercase tags are treated as built-in HTML elements.",
    neutral: "Component names are written in PascalCase, the same style most languages use for class names.",
    bad: "A capital letter in a component's name is a style habit, and React treats lowercase names the same." },
  { topic: "JSX attributes",
    good: "Attributes in JSX mostly use camelCase, and you write className rather than class for CSS classes.",
    neutral: "JSX attributes look similar to HTML attributes, and string values go in quotes the same way they do in HTML.",
    bad: "HTML attributes can be used unchanged in JSX, spelling included, so markup can be pasted over as is." },

  // --- Props and data flow ---
  { topic: "Props",
    good: "Props are the inputs a parent passes to a child, the way arguments are passed to a function.",
    neutral: "A component accepts as many props as it needs, and each one has a name and a value attached to it.",
    bad: "Props are a component's private storage, which it fills in and changes as the user clicks around." },
  { topic: "Passing data down",
    good: "Data moves from parent to child through props; a child only knows what its parent chose to hand it.",
    neutral: "Props carry strings, numbers, arrays, objects, and functions down from a parent to its children.",
    bad: "A child can reach up and read a variable in its parent's code without the parent passing it along." },
  { topic: "Props are read-only",
    good: "A component treats its props as read-only; to change something, it asks its parent to do it.",
    neutral: "Props arrive as one object, and the component reads whichever values it needs from that object.",
    bad: "When a child edits one of its props, the parent picks up the new value and shows it on the page too." },
  { topic: "Talking back to the parent",
    good: "To let a child report back, the parent passes down a function as a prop, and the child calls it.",
    neutral: "A function passed as a prop works like any other prop; the child receives it and uses it.",
    bad: "A child sends data up to its parent by returning it from the component, and the parent reads that value." },
  { topic: "One-way data flow",
    good: "Data flows one way, down the tree, and that makes it easy to trace where a value on screen came from.",
    neutral: "One-way data flow describes how information travels through the component tree in a React app.",
    bad: "Data flows both ways by default, and editing a child's display updates the parent's data too." },
  { topic: "Children",
    good: "Whatever you nest between a component's tags arrives as its children prop, handy for wrappers.",
    neutral: "Wrapper components, such as a card or a modal, are where the children prop tends to show up most.",
    bad: "Nested content inside a custom component is dropped unless it's also passed through a separate prop." },
  { topic: "Default prop values",
    good: "You can give a prop a default value, so the component still works when a parent leaves it out.",
    neutral: "Some props are required for a component to make sense, while others are optional extras on top.",
    bad: "A missing prop crashes the component at once, and that's why each prop has to be passed in every time." },

  // --- Rendering ---
  { topic: "Conditional rendering",
    good: "To show something only sometimes, use an if statement or a ternary to pick what gets returned.",
    neutral: "Conditional rendering means a component shows different output depending on its data at the time.",
    bad: "React has no way to hide part of a component, and you have to remove the elements with DOM code instead." },
  { topic: "Rendering nothing",
    good: "A component can return null to render nothing, which suits things such as a closed popup or an empty panel.",
    neutral: "Not every component has to show something at every moment; some stay empty until data arrives.",
    bad: "Returning null from a component throws an error, so return an empty div when there's nothing to show." },
  { topic: "Rendering lists",
    good: "To show a list, map over the array and return an element for each item, each with its own key.",
    neutral: "Lists show up in nearly every app: menus, tables, search results, comments, and so on down the line.",
    bad: "React can't render arrays, and to show a list you loop and append each item to the page yourself." },
  { topic: "Why keys matter",
    good: "Keys let React match each list item to the same item from the last render when the list changes.",
    neutral: "A key is a special prop on list items; React keeps it for itself, so the component can't read it.",
    bad: "Keys only silence a console warning; the list behaves the same whether or not you add them." },
  { topic: "Index as key",
    good: "An index key can mix up items when the list reorders or shrinks; a stable ID from the data is better.",
    neutral: "Each key should be unique among its siblings, and IDs from the data usually make a good fit.",
    bad: "The array index is the best choice for a key, since it's unique and stays attached to each item." },
  { topic: "Rendering should be pure",
    good: "Rendering should compute the UI from props and state, without side effects like network calls.",
    neutral: "React calls component functions whenever it needs fresh output, which can be many times.",
    bad: "The render body is the right place to fetch data and change outside variables, as it runs on demand." },

  // --- Structure and reuse ---
  { topic: "Splitting a UI into components",
    good: "Split the UI where pieces have their own job or repeat, not only because a file feels long.",
    neutral: "Keep each component small enough to read in one sitting; give its file a clear purpose.",
    bad: "Put the whole page in one big component; splitting it up makes the app slower and harder to follow." },
  { topic: "Reusing components",
    good: "Reuse comes from props: one Button component can show different labels and run different actions in each place.",
    neutral: "A component written once can be placed in as many spots in the app as you like, so long as it's imported.",
    bad: "To reuse a component with different text, copy it into a new file and change the text in the copy." },
  { topic: "Composition",
    good: "React favors composition: build bigger pieces by nesting small components rather than by inheritance.",
    neutral: "Components nest inside other components, and the overall structure forms a tree from the root down.",
    bad: "To share behavior, make one component extend another, the way classes inherit from a parent." },
  { topic: "Component naming",
    good: "Name a component for what it shows, such as UserCard or PriceTag, rather than where it sits.",
    neutral: "Good component names help a codebase, and it's worth a moment's thought to pick a clear one.",
    bad: "Name each component after its spot on the page, like LeftPanel or TopBox; layout is what readers look for." },
  { topic: "Defining components inside components",
    good: "Define components at the top level of a file, not inside another component, or they reset each render.",
    neutral: "Several components fit in a single file, though it's tidy to put each main one in its own file.",
    bad: "Defining a child component inside its parent's function is the best way to keep the two side by side." }
,
  // --- State basics ---
  { topic: "What state is",
    good: "State is data a component remembers between renders, and changing it tells React to redraw the screen.",
    neutral: "State holds values that belong to a component and change while the app is running.",
    bad: "State is a global store that components all across the app read from and write to freely." },
  { topic: "State vs props",
    good: "Props come in from the parent and are read-only, while state is owned by the component itself.",
    neutral: "Props and state both feed into what a component ends up showing on the screen after each render.",
    bad: "Anything a component shows should live in state; props are mainly for passing styles and CSS classes." },
  { topic: "useState basics",
    good: "useState gives you the current value and a setter; call the setter to change it.",
    neutral: "useState is one of the hooks you will reach for most in day-to-day work with React.",
    bad: "useState hands back a single value; to update it, you call useState again with the new value." },
  { topic: "Initial state",
    good: "The value passed to useState counts only on the first render, and later renders keep the current state.",
    neutral: "useState takes a starting value, whether that is a number, a string, an array, or an object.",
    bad: "When the prop used as initial state changes later, the state updates to match it on the next render." },
  { topic: "State per instance",
    good: "Each copy of a component on the page gets its own state, so two counters count independently.",
    neutral: "The same component can appear many times on one page, and each copy is drawn by the same function.",
    bad: "All instances of a component share one copy of their state, the way a static variable does." },
  { topic: "Several state values",
    good: "Use separate useState calls for unrelated values and one object for values that change together.",
    neutral: "A single component is allowed to call useState several times, one call per piece of state.",
    bad: "A useState call can hold a number or a string, but objects need to go in a separate store instead." },
  { topic: "Local variables vs state",
    good: "A plain local variable resets on each render, and changing it won't update the screen; use state.",
    neutral: "Not every value in a component has to be state; plenty are ordinary local variables.",
    bad: "A normal variable declared inside a component keeps its value from one render to the next." },

  // --- Updating state ---
  { topic: "Setting state re-renders",
    good: "Calling the setter schedules a re-render, and React runs the component again with the new value.",
    neutral: "After a state change, React works out the new screen for you, rather than you updating the DOM by hand.",
    bad: "React re-renders a component on a timer, checking its state for changes a few times a second." },
  { topic: "Updates aren't instant",
    good: "Right after you call the setter, the variable still holds the old value until the next render.",
    neutral: "React handles the state update itself rather than applying it at the exact line of the setter call.",
    bad: "Once you call the setter, the state variable already holds the new value on the very next line of code." },
  { topic: "Updating from the previous value",
    good: "When the new value depends on the old one, pass the setter a function that receives the previous value.",
    neutral: "The setter accepts either a new value or a function, and both forms show up in real code.",
    bad: "Calling the counter setter with count plus one three times in a row will add three to the count." },
  { topic: "Objects in state",
    good: "To update an object in state, copy it with the changed field and hand that copy to the setter.",
    neutral: "Objects can live in state just like numbers and strings; form fields are a typical place for them.",
    bad: "Changing a field on the state object directly is enough for React to show the new value." },
  { topic: "Arrays in state",
    good: "For arrays, build a new array with map, filter, or spread and leave the old one untouched.",
    neutral: "Arrays in state are handy for lists of things a user adds to or removes from over time.",
    bad: "Arrays can't be kept in state, so each list item needs to go into its own separate useState call." },

  // --- Events and forms ---
  { topic: "Handling events",
    good: "You attach a handler through a prop such as onClick, and React calls it when the user clicks the element.",
    neutral: "Event handlers are functions that don't run until a click, key press, or other event happens.",
    bad: "Event handlers must be registered by hand with addEventListener after the component mounts." },
  { topic: "Passing vs calling a handler",
    good: "Pass the handler itself to onClick, because calling it there runs it during render.",
    neutral: "A handler prop expects a function that React will run later, at the moment the event actually happens.",
    bad: "Putting parentheses after the handler's name in onClick makes it wait for the click rather than run now." },
  { topic: "The event object",
    good: "Handlers receive an event object with the target element and methods such as preventDefault.",
    neutral: "The event object React passes in looks and behaves much like the browser's own event object.",
    bad: "React handlers get no details about the event, so you have to read input values from the DOM yourself." },
  { topic: "Controlled inputs",
    good: "A controlled input gets its value from state, and its onChange handler is what updates that state.",
    neutral: "Controlled inputs keep the text field and the component's state in step with each other.",
    bad: "Setting an input's value from state is enough on its own; typing then updates the state by itself." },
  { topic: "Submitting forms",
    good: "Call preventDefault in a submit handler unless you actually want the browser to reload the page.",
    neutral: "Forms in React are usually handled with an onSubmit handler that sits on the form element itself.",
    bad: "React blocks the browser's default form submit for you, so the page stays put on submit." },

  // --- Where state lives ---
  { topic: "Lifting state up",
    good: "When two siblings need the same data, move the state to their shared parent and pass it down.",
    neutral: "Lifting state up means moving a piece of state to a component higher in the tree.",
    bad: "Siblings can read each other's state directly as long as they sit under the same parent component." },
  { topic: "Keeping state close",
    good: "Keep state in the lowest component that needs it; putting it higher just spreads re-renders.",
    neutral: "Each piece of state should have a clear home, and that home is usually the one component that uses it.",
    bad: "Put all of the app's state in the top-level component, where every piece is easy to find." },
  { topic: "Resetting a form",
    good: "After a successful submit, set the form's state back to its starting values to clear the inputs.",
    neutral: "Forms usually have a few inputs, a submit button, and some way to show what went wrong.",
    bad: "To clear a controlled form, reload the page; React has no way to reset input values." },
  { topic: "Derived values",
    good: "If a value can be computed from props or state, compute it during render instead of storing it.",
    neutral: "Values like a filtered list or a full name are often built from other data in the component.",
    bad: "Store a filtered list in its own state next to the full list, and sync the two after each change." },
  { topic: "One source of truth",
    good: "Avoid copying the same data into two state variables, since the copies can drift apart.",
    neutral: "Keeping state tidy makes every component easier to read and easier to change when needs shift.",
    bad: "Copy each prop into state before using it; props aren't meant to be shown in JSX directly." },

  // --- Re-renders ---
  { topic: "What causes a re-render",
    good: "A component re-renders when its own state changes or when its parent component re-renders.",
    neutral: "Re-rendering is how React keeps what's on the screen matched up with the latest props and state.",
    bad: "Any state change anywhere in the app makes every component on the page render again." },
  { topic: "Parent re-renders children",
    good: "When a parent re-renders, its children render too by default, even if their props didn't change.",
    neutral: "A child component's output depends on the props it gets from its parent on each render.",
    bad: "A child re-renders only when its own props change, no matter how often its parent renders again." },
  { topic: "Re-render vs DOM update",
    good: "A re-render runs your function again, but React only touches the DOM where the output really changed.",
    neutral: "Rendering in React means calling a component; its result describes what the screen should display.",
    bad: "Each re-render throws away the page's DOM and builds the whole thing again from scratch." }
,
  // --- Effects ---
  { topic: "What useEffect is for",
    good: "useEffect is for syncing a component with something outside React, like a timer or the page title.",
    neutral: "An effect is a function React runs for you at some point after the component appears on screen.",
    bad: "useEffect is where most of a component's logic should go, including the math for what to display." },
  { topic: "When effects run",
    good: "Effects run after React has updated the screen, which keeps them from holding up the page paint.",
    neutral: "An effect belongs to the component that declares it and keeps working as long as that component is mounted.",
    bad: "An effect runs before the component renders, which lets it get data ready for the screen." },
  { topic: "The dependency array",
    good: "The dependency array lists what an effect reads; the effect reruns when one of those changes.",
    neutral: "The dependency array goes in as the second argument to useEffect, right after the effect function itself.",
    bad: "The dependency array sets a limit on how many times the effect is allowed to run before React stops calling it." },
  { topic: "Empty vs missing dependency array",
    good: "With an empty dependency array, the effect runs once after the component mounts and cleans up on unmount.",
    neutral: "An empty dependency array and a missing one look alike at a glance, but they behave in different ways.",
    bad: "Leaving out the dependency array means the effect runs once, when the component mounts." },
  { topic: "Missing dependencies",
    good: "If an effect reads a prop but leaves it off the list, it can keep working with an old value.",
    neutral: "A linter rule can point out every value an effect uses that isn't listed in its dependency array.",
    bad: "Listing fewer dependencies is a good habit; the effect runs less and the whole app gets faster." },
  { topic: "Effect cleanup",
    good: "An effect can return a cleanup function that undoes its work, clearing a timer or closing a socket.",
    neutral: "Cleanup code lives inside the effect too, handed back as a function at the very end of it.",
    bad: "Timers and subscriptions started inside an effect stop on their own once the component goes away for good." },
  { topic: "Effects that run too often",
    good: "An effect that sets state on every run, with nothing to stop it, can loop forever and freeze the page.",
    neutral: "When an effect seems to run too often, the dependency array is the place to start looking.",
    bad: "An effect that runs too often is best fixed by deleting values from its dependency list until it calms." },
  { topic: "Computed values don't need effects",
    good: "You don't need an effect to compute a value from props or state; work it out right during render.",
    neutral: "Values worked out from props or state can just be plain variables declared in the body of the component.",
    bad: "To show a total price from a cart, keep it in state and update it from an effect." },
  { topic: "Event logic vs effects",
    good: "Work caused by a click, like sending a form, belongs in the click handler rather than an effect.",
    neutral: "Event handlers and effects are both places where your code runs outside of the rendering step itself.",
    bad: "For a button click, put the code in an effect that watches a flag, then flip the flag from the click handler." },
  // --- Fetching data ---
  { topic: "Fetching data in an effect",
    good: "Fetching in an effect works well for simple cases: start the request on mount and put the result in state.",
    neutral: "Data from a server usually shows up after the first render, so the first screen may start out empty.",
    bad: "Calling fetch right in the component body, outside of any effect, is the normal way to load data." },
  { topic: "Loading and error states",
    good: "As data loads, keep a loading flag and an error in state, then show a spinner or a message.",
    neutral: "A loading spinner gives the user something to look at while the page sits waiting on a reply from the server.",
    bad: "Handling fetch errors isn't needed in a component; React shows a message by itself for any failed request." },
  // --- Refs ---
  { topic: "useRef for DOM elements",
    good: "useRef can hold a reference to a real DOM element, which helps with jobs such as focusing an input.",
    neutral: "A ref attached to an element points straight at the actual node the browser created for it.",
    bad: "To focus an input, look it up with a document query right inside the component while it is rendering." },
  { topic: "When a DOM ref is ready",
    good: "A DOM ref stays empty during the initial render; it gets filled in once the element is on the page.",
    neutral: "A ref keeps its value on its current property, which your code can read or change.",
    bad: "A ref to an element is ready to use right away, even in the middle of the initial render." },
  { topic: "useRef for values",
    good: "A ref can also hold a plain value, a timer ID say, that should persist without causing a re-render.",
    neutral: "A ref keeps hold of one and the same object across every render, for the whole life of the component.",
    bad: "Changing a ref's value updates the screen the same way that setting a state variable does." },
  { topic: "Ref or state?",
    good: "Use state for what the screen shows and a ref for values your code needs to remember quietly.",
    neutral: "Both refs and state remember values between renders; they differ in what happens on a change.",
    bad: "Refs work like a faster kind of state, and it's smart to swap state out for refs wherever you can." },
  // --- Context ---
  { topic: "What context is for",
    good: "Context lets a parent share a value with any component below it without passing props through each level.",
    neutral: "Context has a provider that supplies the value and components below that read it with useContext.",
    bad: "With context, a child component can push its data up to the parent without any callback." },
  { topic: "Prop drilling",
    good: "Prop drilling means passing a prop through layers that don't use it just to reach a deep child.",
    neutral: "Prop drilling gets more tedious to manage as the component tree grows deeper and gains more layers.",
    bad: "Passing a prop down through more than one component causes extra renders and is worth avoiding." },
  { topic: "When context is overkill",
    good: "For data only a couple of nearby components need, plain props are often simpler than context.",
    neutral: "Values like a theme or the logged-in user are ones that many parts of an app may want to read.",
    bad: "Every piece of shared state belongs in context; props are really meant for small, simple apps only." },
  { topic: "Context updates",
    good: "When a context value changes, every component reading that context re-renders with the new value.",
    neutral: "A component reading context gets the value from the nearest provider above it in the tree.",
    bad: "Components reading a context don't update when its value changes; instead they hold on to the old value." },
  // --- Memoizing ---
  { topic: "useMemo",
    good: "useMemo remembers the result of a slow calculation and redoes it when its inputs change.",
    neutral: "useMemo takes a function plus a dependency list, much like useEffect does, and gives back a value.",
    bad: "useMemo keeps a value across page reloads, like saved storage that's still there after a refresh." },
  { topic: "useCallback",
    good: "useCallback keeps the same function between renders, which helps when a memoized child receives it.",
    neutral: "Like useMemo, useCallback depends on a list of values that tell it when to make a fresh copy.",
    bad: "Wrapping a function in useCallback makes the function itself run faster every single time it gets called." },
  { topic: "Not overusing memoization",
    good: "Memoizing has its own cost, so it's worth adding where a slow spot has actually been measured.",
    neutral: "Memoization trades a little memory for skipping work that would otherwise be repeated on each render.",
    bad: "Wrapping each value and function in useMemo or useCallback is the standard way to write React." },
  // --- Custom hooks and rules ---
  { topic: "Custom hooks",
    good: "A custom hook is a function starting with use that bundles hook logic for several components to reuse.",
    neutral: "Custom hooks can call other hooks, including any other custom hooks you've written yourself.",
    bad: "Custom hooks need a special registration step before React lets any component call them." },
  { topic: "Custom hooks share logic, not state",
    good: "Two components using the same custom hook each get their own separate copy of its state.",
    neutral: "A custom hook can return whatever is handy: a value, a function, or several of each.",
    bad: "When two components call one custom hook, they share a single copy of its state between them." },
  { topic: "Rules of hooks",
    good: "Call hooks at the top level of a component, not inside loops, conditions, or nested functions.",
    neutral: "React keeps track of all the hooks in a component by the order they're called in during each render.",
    bad: "A hook can go inside an if statement as long as the condition is usually true when the page loads." }
,
  // --- Structuring an app ---
  { topic: "Structuring an app",
    good: "Group files by feature, so everything for checkout sits together in one folder.",
    neutral: "A React app is built from many components, and all of them live in files and folders you arrange.",
    bad: "React decides the folder layout itself, and the app won't build unless files sit in the expected folders." },
  { topic: "Shared UI components",
    good: "A shared set of buttons and inputs keeps the look consistent and saves rebuilding the same pieces.",
    neutral: "Most apps end up with a handful of basic building blocks, such as buttons, inputs and dialogs.",
    bad: "Ready-made UI components can't be styled to match your app, so each team builds every button from scratch." },
  { topic: "State libraries",
    good: "Reach for a state library when many distant parts share data; a small app often doesn't need one.",
    neutral: "A state library keeps data in a store outside components, and any component can read from that store.",
    bad: "Built-in state is for demos rather than real projects, which need a state library from the first day." },
  { topic: "Routing library",
    good: "A routing library maps each URL to a component, so the page changes without a full reload.",
    neutral: "An app with more than one page usually uses a routing library; it picks which screen to show.",
    bad: "React watches the URL by itself and swaps whole pages for you without a routing library in the app." },
  { topic: "Data-fetching libraries",
    good: "A data-fetching library caches server data and refetches it when it's stale, saving you loading code.",
    neutral: "Data-fetching libraries help move data from a server into your components with less effort.",
    bad: "Server data doesn't change once it's fetched, so keeping one copy in a component forever is enough." },

  // --- Performance ---
  { topic: "Measure first",
    good: "Before speeding anything up, measure with the profiler to find which components are actually slow.",
    neutral: "Performance matters in React apps, since slow screens are something that users tend to notice quickly.",
    bad: "When a screen feels slow, guess the likely cause and start rewriting that part right away." },
  { topic: "Long lists",
    good: "For a list of thousands of rows, render only the rows on screen and load the rest as you scroll.",
    neutral: "Long lists can take a while to render; rows with a lot of content in them add to the cost.",
    bad: "A list of fifty thousand rows renders instantly in React, since the DOM is touched once per render." },
  { topic: "Premature optimization",
    good: "Write clear code first. Most apps are fast enough, and tuning without a real problem isn't worth it.",
    neutral: "Optimizing means making code run faster or use less memory than it did before the change.",
    bad: "Optimize every component up front; fixing slow code later is much harder than doing it now." },
  { topic: "Production builds",
    good: "Judge speed with a production build, not development mode, which adds extra checks.",
    neutral: "A production build bundles the app into a few files that a server can hand out to any browser.",
    bad: "Development mode and the production build run at the same speed, so either works for timing." },

  // --- Testing ---
  { topic: "Testing like a user",
    good: "Test what the user sees: click the button, then check that the right text shows up.",
    neutral: "A component test renders the component and then checks something about the output it produced.",
    bad: "Good tests check a component's internal state values directly instead of what's on screen." },
  { topic: "What to test",
    good: "Focus tests on behavior that matters, like a form showing an error when any required field is empty.",
    neutral: "Tests give you more confidence when changing code, so it's worth writing some for key screens.",
    bad: "Aim for a test on every single line of every component; anything less leaves the app untested." },

  // --- Errors and accessibility ---
  { topic: "Error boundaries",
    good: "An error boundary catches a crash below it and shows a fallback rather than a blank page.",
    neutral: "Error boundaries deal with errors thrown during rendering somewhere further down the component tree.",
    bad: "React catches render errors on its own and keeps the rest of the page working with zero setup." },
  { topic: "Accessibility basics",
    good: "Use real buttons and links instead of clickable divs; they work with the keyboard and screen readers.",
    neutral: "Accessibility means an app works for as many people as possible, not only mouse users.",
    bad: "Screen readers treat a clickable div exactly like a button, and keyboard users can reach it too." },
  { topic: "Labels and alt text",
    good: "Give every input a label and every meaningful image alt text, so assistive tools can describe them.",
    neutral: "JSX supports the usual HTML attributes for accessibility, with a few names written differently.",
    bad: "Placeholder text inside an input works as its label, and a separate label just adds clutter." },

  // --- Styling and types ---
  { topic: "Styling options",
    good: "You can style with plain CSS files, CSS modules, or CSS-in-JS; pick one and use it across the app.",
    neutral: "Styling in React still ends up as CSS in the browser, whichever approach a team chooses to use for it.",
    bad: "React components can't use normal CSS files; styles have to be written inline on each element." },
  { topic: "Typed props",
    good: "A type checker can describe the props a component takes and catch a wrong or missing prop early.",
    neutral: "Types add some extra writing to a component, though the editor uses them to offer better hints.",
    bad: "Adding types to props changes how React renders them at runtime, and that makes the whole app slower." },
  { topic: "Function vs class components",
    good: "New code mostly uses function components with hooks, and class components still work in older apps.",
    neutral: "Function components and class components both describe a piece of UI; React can render either one.",
    bad: "Hooks work inside class components too; the choice between the two styles is purely cosmetic." },

  // --- Dev mode and tooling ---
  { topic: "Effects running twice in dev",
    good: "In development, React may run an effect twice on purpose to expose missing cleanup code.",
    neutral: "Development mode adds extra checks and warnings, while a production build leaves them out to stay fast.",
    bad: "An effect firing twice in development means React itself has a bug you should report." },
  { topic: "Developer tools",
    good: "The React developer tools let you inspect each component's props and state in the browser.",
    neutral: "Browser developer tools help with debugging, and React has an extension that adds its own panel.",
    bad: "Browser tools show plain HTML elements alone, so logging is the one way to see a component's props." },
  { topic: "Development warnings",
    good: "Read React's development warnings rather than skipping past them; they often point right at the bug.",
    neutral: "React prints warnings in development mode when it notices something unusual in your components.",
    bad: "Development warnings don't matter as long as the page looks right, so you can skip them." },

  // --- React in context ---
  { topic: "React vs plain DOM",
    good: "With React you describe the UI for the current data, and React updates the DOM to match it.",
    neutral: "Plain JavaScript can update a page too, by finding elements and changing each of them by hand, step by step.",
    bad: "Editing React's DOM nodes by hand is no problem; React notices and keeps its state in sync." },
  { topic: "Reading error messages",
    good: "React error messages usually name the component and the problem, so reading them fully saves guessing.",
    neutral: "Error messages show up in the browser console, and in development sometimes as an overlay on the page.",
    bad: "React errors are too vague to help, so the quickest fix is to undo recent changes until it works again." },
  { topic: "Readability",
    good: "Clear names for components and props, like UserCard and onSave, make a file easy to follow.",
    neutral: "Readable code is easier to change, and a teammate doesn't need to ask many questions to pick it up.",
    bad: "Short names like Comp and p keep files compact, and compact code is what makes a component readable." },
  { topic: "Code review",
    good: "In a review, look for state that could be computed, effects that aren't needed, and unclear names.",
    neutral: "Code review means someone else on the team reads a change; it happens before the change is merged.",
    bad: "If a component renders without errors, there's not much left for a reviewer to check in it." },
  { topic: "React Native",
    good: "React Native uses the same component and hook ideas to build phone apps with real native UI elements.",
    neutral: "React Native isn't for websites; it builds mobile apps that share many ideas with React on the web.",
    bad: "React Native runs your web React app inside a browser window on the phone, HTML and CSS included." }
] };
