// Original hand-crafted magical items — kept for posterity.
// Not imported anywhere; purely an archive.

export const ORIG_WEAPONS = [
    { id: 'rusty_blade', name: 'Rusty Blade', type: 'melee', damage: 1, range: 0, special: null, price: 0, tier: 0, magical: true },
    { id: 'void_cleaver', name: 'Void Cleaver', type: 'melee', damage: 7, range: 0, special: 'chaos_bonus', price: 40, tier: 1, magical: true },
    { id: 'starforged_sword', name: 'Starforged Sword', type: 'melee', damage: 10, range: 0, special: null, price: 100, tier: 2, magical: true },
    { id: 'dimensional_edge', name: 'Dimensional Edge', type: 'melee', damage: 12, range: 0, special: 'cleave', price: 150, tier: 3, magical: true },
    { id: 'duskfang', name: 'Duskfang', type: 'melee', damage: 4, range: 0, special: 'lifesteal', lifestealAmount: 2, price: 35, tier: 1, magical: true },
    { id: 'breaker_mace', name: 'Breaker Mace', type: 'melee', damage: 3, range: 0, special: 'armor_pierce', pierceAmount: 2, price: 30, tier: 1, magical: true },
    { id: 'wardens_blade', name: "Warden's Blade", type: 'melee', damage: 6, range: 0, special: 'riposte', price: 60, tier: 2, magical: true },
    { id: 'emberstrike', name: 'Emberstrike', type: 'melee', damage: 8, range: 0, special: 'momentum', momentumBonus: 4, price: 75, tier: 2, magical: true },
    { id: 'soulreaver', name: 'Soulreaver', type: 'melee', damage: 7, range: 0, special: 'aether_siphon', price: 70, tier: 2, magical: true },
    { id: 'nullblade', name: 'Nullblade', type: 'melee', damage: 9, range: 0, special: 'defense_shred', price: 110, tier: 3, magical: true },
    { id: 'worldsplitter', name: 'Worldsplitter', type: 'melee', damage: 14, range: 0, special: 'recoil', recoilDamage: 3, price: 130, tier: 3, magical: true },
    { id: 'flux_bow', name: 'Flux Bow', type: 'ranged', damage: 5, range: 3, special: 'armor_pierce', pierceAmount: 2, price: 35, tier: 1, magical: true },
    { id: 'phase_rifle', name: 'Phase Rifle', type: 'ranged', damage: 8, range: 5, special: 'ignore_defense', price: 120, tier: 3, magical: true },
    { id: 'aether_lance', name: 'Aether Lance', type: 'ranged', damage: 6, range: 3, special: 'free_ranged', price: 60, tier: 2, magical: true },
    { id: 'spark_caster', name: 'Spark Caster', type: 'ranged', damage: 3, range: 3, special: 'chain', chainDamage: 3, price: 30, tier: 1, magical: true },
    { id: 'gale_bow', name: 'Gale Bow', type: 'ranged', damage: 4, range: 3, special: 'knockback', price: 40, tier: 1, magical: true },
    { id: 'rift_cannon', name: 'Rift Cannon', type: 'ranged', damage: 6, range: 5, special: 'splash', splashDamage: 2, price: 55, tier: 2, magical: true },
    { id: 'voidpiercer', name: 'Voidpiercer', type: 'ranged', damage: 5, range: 4, special: 'piercing', price: 65, tier: 2, magical: true },
    { id: 'stasis_repeater', name: 'Stasis Repeater', type: 'ranged', damage: 4, range: 3, special: 'double_shot', price: 70, tier: 2, magical: true },
    { id: 'nova_launcher', name: 'Nova Launcher', type: 'ranged', damage: 7, range: 3, special: 'burn', burnDamage: 3, price: 100, tier: 3, magical: true },
    { id: 'astral_longbow', name: 'Astral Longbow', type: 'ranged', damage: 9, range: 5, special: 'sniper', sniperBonus: 4, price: 140, tier: 3, magical: true },
    { id: 'flicker_blade', name: 'Flicker Blade', type: 'melee', damage: 2, range: 0, special: 'double_strike', price: 20, tier: 1, magical: true },
    { id: 'aether_spike', name: 'Aether Spike', type: 'melee', damage: 3, range: 0, special: 'aether_siphon', price: 25, tier: 1, magical: true },
    { id: 'blood_thorn', name: 'Blood Thorn', type: 'melee', damage: 3, range: 0, special: 'lifesteal', lifestealAmount: 1, price: 25, tier: 1, magical: true },
    { id: 'rending_pick', name: 'Rending Pick', type: 'melee', damage: 4, range: 0, special: 'armor_pierce', pierceAmount: 2, price: 30, tier: 1, magical: true },
    { id: 'broad_cleaver', name: 'Broad Cleaver', type: 'melee', damage: 4, range: 0, special: 'cleave', price: 30, tier: 1, magical: true },
    { id: 'ember_blade', name: 'Ember Blade', type: 'melee', damage: 5, range: 0, special: 'burn', burnDamage: 2, price: 40, tier: 1, magical: true },
    { id: 'arc_caster', name: 'Arc Caster', type: 'ranged', damage: 2, range: 3, special: 'chain', chainDamage: 3, price: 20, tier: 1, magical: true },
    { id: 'pulse_bow', name: 'Pulse Bow', type: 'ranged', damage: 3, range: 3, special: 'double_shot', price: 25, tier: 1, magical: true },
    { id: 'ley_bow', name: 'Ley Bow', type: 'ranged', damage: 3, range: 3, special: 'free_ranged', price: 25, tier: 1, magical: true },
    { id: 'blast_rod', name: 'Blast Rod', type: 'ranged', damage: 4, range: 3, special: 'splash', splashDamage: 2, price: 35, tier: 1, magical: true },
    { id: 'hawk_bow', name: 'Hawk Bow', type: 'ranged', damage: 4, range: 5, special: 'sniper', sniperBonus: 2, price: 40, tier: 2, magical: true },
    { id: 'piercing_bolt', name: 'Piercing Bolt', type: 'ranged', damage: 5, range: 3, special: 'armor_pierce', pierceAmount: 2, price: 45, tier: 2, magical: true },
];

export const ORIG_ARMORS = [
    { id: 'worn_leather', name: 'Worn Leather', defense: 1, special: null, price: 0, tier: 0, magical: true },
    { id: 'warded_mail', name: 'Warded Mail', defense: 4, special: 'hp_bonus', hpBonus: 10, price: 50, tier: 1, magical: true },
    { id: 'chaosweave_cloak', name: 'Chaosweave Cloak', defense: 3, special: 'vision_bonus', visionBonus: 2, price: 45, tier: 1, magical: true },
    { id: 'starplate', name: 'Starplate', defense: 8, special: 'mp_penalty', mpPenalty: 1, price: 120, tier: 2, magical: true },
    { id: 'voidhide', name: 'Voidhide', defense: 5, special: 'wraith_immune', price: 100, tier: 3, magical: true },
    { id: 'thornmail', name: 'Thornmail', defense: 2, special: 'thorns', thornsDamage: 2, price: 35, tier: 1, magical: true },
    { id: 'flickerweave', name: 'Flickerweave', defense: 2, special: 'dodge_bonus', dodgeBonus: 30, price: 40, tier: 1, magical: true },
    { id: 'bloodward_cuirass', name: 'Bloodward Cuirass', defense: 4, special: 'heal_on_kill', healOnKill: 5, price: 65, tier: 2, magical: true },
    { id: 'stormplate', name: 'Stormplate', defense: 3, special: 'aether_regen', price: 80, tier: 2, magical: true },
    { id: 'wraithskin', name: 'Wraithskin', defense: 3, special: 'ranged_immune', price: 75, tier: 2, magical: true },
    { id: 'burning_mail', name: 'Burning Mail', defense: 4, special: 'burning_aura', burnAuraDamage: 3, price: 75, tier: 2, magical: true },
    { id: 'aegis_of_the_breach', name: 'Aegis of the Breach', defense: 6, special: 'last_stand', lastStandBonus: 2, price: 130, tier: 3, magical: true },
    { id: 'scout_cloak', name: "Scout's Cloak", defense: 1, special: 'vision_bonus', visionBonus: 1, price: 15, tier: 1, magical: true },
    { id: 'runecloth_robe', name: 'Runecloth Robe', defense: 2, special: 'aether_regen', price: 30, tier: 1, magical: true },
    { id: 'padded_mail', name: 'Padded Mail', defense: 2, special: 'hp_bonus', hpBonus: 5, price: 25, tier: 1, magical: true },
    { id: 'lifeweave_tunic', name: 'Lifeweave Tunic', defense: 3, special: 'armor_regen', regenAmount: 1, price: 40, tier: 1, magical: true },
    { id: 'aether_vest', name: 'Aether Vest', defense: 3, special: 'armor_aether_bonus', aetherBonus: 5, price: 45, tier: 2, magical: true },
    { id: 'wardens_plate', name: "Warden's Plate", defense: 5, special: 'regen_combo', regenAmount: 1, price: 70, tier: 2, magical: true },
];

export const ORIG_ARTIFACTS = [
    { id: 'seers_lens', name: "Seer's Lens", special: 'vision_bonus', visionBonus: 2, price: 40, tier: 1, magical: true },
    { id: 'aether_crystal', name: 'Aether Crystal', special: 'aether_bonus', aetherBonus: 4, price: 50, tier: 1, magical: true },
    { id: 'vitality_stone', name: 'Vitality Stone', special: 'regen', regenAmount: 3, price: 80, tier: 3, magical: true },
    { id: 'phase_anchor', name: 'Phase Anchor', special: 'displacement_immune', price: 35, tier: 1, magical: true },
    { id: 'maw_compass', name: 'Maw Compass', special: 'reveal_maw', price: 30, tier: 1, magical: true },
    { id: 'strider_boots', name: 'Strider Boots', special: 'strider', price: 55, tier: 2, magical: true },
    { id: 'smoke_cloak', name: 'Smoke Cloak', special: 'disengage', price: 65, tier: 2, magical: true },
    { id: 'momentum_bracers', name: 'Momentum Bracers', special: 'momentum_defense', price: 60, tier: 2, magical: true },
    { id: 'threat_shroud', name: 'Threat Shroud', special: 'threat_shroud', price: 40, tier: 1, magical: true },
    { id: 'ranger_cloak', name: 'Ranger Cloak', special: 'ranger_defense', rangerBonus: 3, price: 40, tier: 1, magical: true },
    { id: 'chaos_ward', name: 'Chaos Ward', special: 'chaos_defense', chaosDefenseBonus: 3, price: 50, tier: 2, magical: true },
    { id: 'wall_crown', name: 'Wall Crown', special: 'wall_crown', wallCrownBonus: 4, price: 65, tier: 2, magical: true },
    { id: 'breach_jewel', name: 'Breach Jewel', special: 'breach_jewel', breachBonus: 5, price: 55, tier: 2, magical: true },
    { id: 'soul_harvest_sigil', name: 'Soul Harvest Sigil', special: 'soul_harvest', soulHarvestXP: 2, price: 70, tier: 2, magical: true },
    { id: 'opportunist_gloves', name: 'Opportunist Gloves', special: 'opportunist', price: 35, tier: 1, magical: true },
    { id: 'aether_signet', name: 'Aether Signet', special: 'aether_signet', aetherSignetDamage: 3, aetherSignetCost: 3, price: 80, tier: 3, magical: true },
    { id: 'chaos_circlet', name: 'Chaos Circlet', special: 'chaos_circlet', price: 55, tier: 2, magical: true },
    { id: 'aether_right', name: 'Aether Right', special: 'aether_regen_small', price: 45, tier: 1, magical: true },
    { id: 'aether_amulet', name: 'Aether Amulet', special: 'aether_regen_large', price: 85, tier: 3, magical: true },
    { id: 'blink_ring', name: 'Blink Ring', special: 'blink_ring', blinkRange: 4, blinkBonus: 2, price: 95, tier: 3, magical: true },
    { id: 'counter_bracers', name: 'Counter Bracers', special: 'counter_mastery', price: 70, tier: 2, magical: true },
    { id: 'lesser_vitality_stone', name: 'Lesser Vitality Stone', special: 'regen', regenAmount: 2, price: 50, tier: 2, magical: true },
    { id: 'ranger_hood', name: 'Ranger Hood', special: 'ranger_defense', rangerBonus: 1, price: 25, tier: 1, magical: true },
    { id: 'chaos_sigil', name: 'Chaos Sigil', special: 'chaos_attune', chaosAttuneMight: 1, chaosAttuneDef: 1, price: 35, tier: 1, magical: true },
    { id: 'sentinels_crown', name: "Sentinel's Crown", special: 'wall_crown', wallCrownBonus: 2, price: 40, tier: 1, magical: true },
    { id: 'wayfarer_boots', name: 'Wayfarer Boots', special: 'mp_bonus', mpBonus: 1, price: 30, tier: 1, magical: true },
    { id: 'windrunner_boots', name: 'Windrunner Boots', special: 'mp_bonus', mpBonus: 3, price: 80, tier: 3, magical: true },
    { id: 'arrow_ward', name: 'Arrow Ward', special: 'ranged_immune', price: 45, tier: 2, magical: true },
];
