// Object-oriented programming beginner-to-intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "Object-Oriented Programming", turns: [
  // --- Classes and objects ---
  { topic: "Class vs object",
    good: "A class is the blueprint, and each object is one thing built from it, holding its own data.",
    neutral: "One class can produce many objects; a program creates them as it runs and passes them around to other code.",
    bad: "Changing one object's data also changes the class, and with it every other object made from that class." },
  { topic: "Constructors",
    good: "A constructor puts a new object into a valid starting state, so it's ready to use right away.",
    neutral: "The constructor runs when a new object is created, and it can take arguments just as an ordinary method does.",
    bad: "Leave the constructor empty and let callers fill in the fields afterward; that keeps the class flexible." },
  { topic: "Fields and methods",
    good: "Fields hold what an object knows; methods are what it can do, usually working with those fields.",
    neutral: "A class has fields and methods, and a single class might have a lot of each or hardly any.",
    bad: "Methods should stay away from the object's own fields and take everything they need as arguments." },
  { topic: "State and behavior",
    good: "An object keeps its data next to the code that changes it, which makes the rules easy to find.",
    neutral: "An object's state is the data it holds at a given moment; for most objects that data shifts as the program runs.",
    bad: "An object's data is fixed once it's created; to change any of it, you have to build a brand new object." },

  // --- Encapsulation and access ---
  { topic: "Encapsulation",
    good: "Encapsulation hides the inner details, so other code goes through a small, deliberate set of methods.",
    neutral: "Encapsulation is one of the main ideas in object-oriented design; it shows up in almost every class.",
    bad: "Encapsulation mostly means keeping related code in the same file, which makes it easier to find." },
  { topic: "Private vs public",
    good: "Keep members private unless other code needs them; less that's public means less that can break later.",
    neutral: "Public members are usable from outside the class, while private ones stay visible inside it only.",
    bad: "A private field keeps the data secure from hackers, who have no way to read it from outside the program." },
  { topic: "Getters and setters",
    good: "A getter and setter on every field isn't real encapsulation; offer the operations callers need instead.",
    neutral: "A getter returns a field's value and a setter updates it, often with a matching method name.",
    bad: "Give each field a public getter and setter; that's how a class is properly encapsulated." },
  { topic: "Abstraction",
    good: "Abstraction shows what something does and hides how it does it, so callers can think in simpler terms.",
    neutral: "Abstraction shows up all over programming, not only in classes; functions and modules use it too.",
    bad: "A good abstraction exposes its internal details rather than hiding them, giving callers full control." },
  { topic: "Exposing internal lists",
    good: "If a class hands out its internal list directly, callers can change it behind the object's back.",
    neutral: "A class might keep a list of items in a field: a cart's items, say, or an order's lines.",
    bad: "Returning the internal list is no problem, as a private field can't be changed by anyone outside the class." },

  // --- Static, this, identity ---
  { topic: "Static vs instance members",
    good: "Each object gets its own copy of instance members, and a static member belongs to the class, shared by all.",
    neutral: "A static method is callable without creating an object first: you go through the class itself.",
    bad: "Make every method static whenever you can, since objects are slower to use and get in the way of testing." },
  { topic: "Shared static state",
    good: "A changeable static field acts like a global variable: any code can change it, and bugs get hard to trace.",
    neutral: "A static constant, such as a maximum size, is a reasonable thing for a whole class to share.",
    bad: "Put the current user in a static field; then every part of the app can reach it without passing it in." },
  { topic: "The current-object reference",
    good: "Inside a method, the current-object reference points to whichever object the method was called on.",
    neutral: "Each object-oriented language has its own word for the current object, since there's no single standard term.",
    bad: "The current-object reference points to the class itself rather than to a particular object." },
  { topic: "Identity vs equality",
    good: "Identity asks if two references point to the very same object; equality asks if they mean the same thing.",
    neutral: "Two variables might refer to objects, and a program sometimes has to check whether they match.",
    bad: "Two objects with the same field values are really one object, stored together in the same spot in memory." },
  { topic: "Comparing objects",
    good: "If you define equality for a class, decide which fields make two of its objects count as the same thing.",
    neutral: "Comparing objects matters any time you search a list, remove duplicates, or use objects as keys.",
    bad: "There's no reason to think about how objects get compared, as the default check handles it for you." },

  // --- Values and immutability ---
  { topic: "Immutability",
    good: "An immutable object can't change after it's built, so you can share it freely without surprises.",
    neutral: "Immutable objects set their fields once in the constructor and don't offer any setters after that.",
    bad: "Immutable objects don't belong in real programs, because real data has to change in place." },
  { topic: "Value-like objects",
    good: "Small things like money or a date range make good value objects: compared by content, not identity.",
    neutral: "A value object holds a few fields, and it often takes its meaning straight from the business domain.",
    bad: "Wrapping an amount and a currency in a class is overkill; pass a number and a string around instead." },
  { topic: "Null references",
    good: "A null reference means no object is there, and calling a method on it fails while the program runs.",
    neutral: "Check whether a reference might be null before you use it, and decide what should happen then.",
    bad: "Return null for each kind of failure; callers can check for it and skip proper error handling altogether." },

  // --- Lifetime and memory ---
  { topic: "Object lifetime",
    good: "An object lives as long as something can still reach it; after that, its memory can be reclaimed.",
    neutral: "Objects get created as the program runs; each one takes up some memory for as long as it exists.",
    bad: "Objects typically stay in memory until the program ends, whether or not anything still uses them." },
  { topic: "Garbage collection",
    good: "Garbage collection frees unreachable objects, yet holding references too long can still leak memory.",
    neutral: "With garbage collection the runtime finds objects nothing uses and frees their memory, so you don't do it by hand.",
    bad: "Garbage collection makes memory leaks impossible, no matter how many references you hang on to." },
  { topic: "Cleaning up resources",
    good: "Memory is handled for you, but files and connections should be closed explicitly when you're done.",
    neutral: "Some objects hold onto things outside the program; a file handle and a database connection are both resources.",
    bad: "Leave open files to the garbage collector, and it will close them the moment the last reference goes away." },

  // --- Modeling and size ---
  { topic: "Naming classes",
    good: "A class should get a clear noun for what it represents, and a vague label often hides a muddled design.",
    neutral: "Give the class a name that says what it holds, and spell that name the same way everywhere in the code.",
    bad: "Words like Manager, Helper and Util suit most classes best, because they fit whatever ends up inside." },
  { topic: "Modeling a real-world thing",
    good: "Model the parts of a real thing that your program needs, not every detail the thing happens to have.",
    neutral: "Many classes stand for real things in the problem: an order, a customer, or an invoice.",
    bad: "A class should mirror its real-world counterpart in full detail, with every property and quirk included." },
  { topic: "Class too big",
    good: "When a class grows huge and does unrelated jobs, split it into smaller classes that each have one purpose.",
    neutral: "Big classes take longer to read, so it's worth glancing at a class's size now and then.",
    bad: "One large class is often better than several small ones, because all the code sits in a single place." },
  { topic: "Constructor doing too much",
    good: "Keep constructors light: set up fields, but don't do slow work like network calls or reading files.",
    neutral: "A constructor may call other methods on the object while it gets the fields and settings ready for use.",
    bad: "Load the object's data from the database inside its constructor; that keeps it fresh from the start." },
  { topic: "Objects as plain data bags",
    good: "When a class is just fields with getters and setters, the logic about it probably lives elsewhere.",
    neutral: "Some classes mostly carry data between parts of a program, and they have very few methods of their own.",
    bad: "Objects shouldn't contain logic at all, and behavior belongs in separate service classes instead." }
,
  // --- Inheritance basics ---
  { topic: "Inheritance basics",
    good: "A child class picks up the fields and methods of its parent, and it can add or change behavior of its own.",
    neutral: "With inheritance, one class builds on another class and gets what that class already has.",
    bad: "Reach for inheritance whenever two classes share a few lines of code; reuse is its main job." },
  { topic: "Is-a vs has-a",
    good: "Inherit when the child truly is a kind of the parent; a car has an engine, so it holds one.",
    neutral: "Is-a and has-a are two plain ways to describe how one class in a design relates to another class.",
    bad: "A car class should extend an engine class, since the car uses what the engine can do." },
  { topic: "Parent and child classes",
    good: "The parent holds what all its children share, and each child adds what makes it different.",
    neutral: "A child class sits below its parent in the hierarchy, and one parent can have many children.",
    bad: "A child class can't use methods from its parent unless it copies those methods into its own body." },
  { topic: "Overriding a method",
    good: "Overriding means a child class supplies its own version of a method that the parent already defines.",
    neutral: "An overridden method keeps the same name as the one in the parent class that it replaces.",
    bad: "To override a method, the child must give it a new name so the two versions don't clash." },
  { topic: "Calling the parent's version",
    good: "An override can call the parent's version to reuse it, then add a little extra on top.",
    neutral: "Most languages give an overriding method some way to reach the parent's version of the same method.",
    bad: "Once you override a method, the parent's version is gone for good inside the child class." },
  { topic: "Protected members",
    good: "Protected members are visible to child classes, but outside code still can't touch them.",
    neutral: "Protected sits between private and public; it controls how widely a member can be seen.",
    bad: "Make every field protected by default; some child class might need it someday, after all." },
  { topic: "Default behavior in the parent",
    good: "A parent can offer a sensible default method that most children use as is and only a few override.",
    neutral: "Children don't have to override a parent method; they can keep the inherited version as it is.",
    bad: "Each child class must override each method it inherits, or the program won't run." },

  // --- Polymorphism ---
  { topic: "Polymorphism",
    good: "Polymorphism is the idea that one method call can act differently depending on the object.",
    neutral: "Along with inheritance and encapsulation, polymorphism sits near the center of object-oriented design.",
    bad: "Polymorphism means a class has lots of methods: the more methods, the more polymorphic it is." },
  { topic: "Polymorphism vs type checks",
    good: "A long chain of type checks is often a hint: a polymorphic method would probably read better.",
    neutral: "Type checks and polymorphic calls can both pick different behavior for different kinds of objects.",
    bad: "A chain of type checks for each kind of shape is the clearest way to give shapes their own behavior." },
  { topic: "Mixed objects in one list",
    good: "You can keep different shapes in one list of the parent type and ask each to draw itself.",
    neutral: "A list of shapes can grow and shrink as the program adds and removes shapes over time.",
    bad: "A list holds objects of one exact class, so circles and squares each need a separate list." },
  { topic: "Overloading vs overriding",
    good: "Overloading is one name with different inputs; overriding replaces a parent's method in a child.",
    neutral: "Overloading and overriding sound alike, and both of them involve methods that share a name.",
    bad: "Overloading and overriding are the same thing, two words for redefining a method." },
  { topic: "Duck typing",
    good: "Duck typing cares whether an object has the methods you call, not what class it came from.",
    neutral: "Duck typing shows up mostly in languages that check types while the program runs.",
    bad: "With duck typing, objects have no types at all, and any object can go anywhere without errors." },

  // --- Abstract classes and interfaces ---
  { topic: "Abstract classes",
    good: "An abstract class can't be created directly; it shares code and leaves some methods open.",
    neutral: "An abstract class usually has a general-sounding name: Shape, Animal, or Account, to pick a few.",
    bad: "Abstract classes must be completely empty, with no fields and no real method bodies." },
  { topic: "Abstract methods",
    good: "An abstract method has a name but no body, and each concrete child class must supply one of its own.",
    neutral: "Abstract methods are usually declared in an abstract class or in an interface.",
    bad: "An abstract method already has a working body; children override it only if they feel like it." },
  { topic: "Interfaces",
    good: "An interface lists what an object can do; any class with those methods fits through it.",
    neutral: "Interface names often describe a capability, for example Printable or Comparable or Drawable.",
    bad: "Interfaces are mostly documentation, and a class that claims one can skip writing its methods." },
  { topic: "Abstract class vs interface",
    good: "Pick an abstract class to share code among close relatives, and an interface to name a role.",
    neutral: "Abstract classes and interfaces both describe methods that some other class will eventually have to provide.",
    bad: "Abstract classes and interfaces are interchangeable; choosing between them is a matter of taste." },
  { topic: "Multiple interfaces",
    good: "A class can implement several interfaces at once, playing different roles in different places.",
    neutral: "A class that implements several interfaces has to provide the methods from all of them.",
    bad: "Implementing more than one interface is usually a design error, because a class should fill a single role." },
  { topic: "Multiple inheritance",
    good: "Multiple inheritance gives a class two parents, which gets messy when both define one method.",
    neutral: "Some languages let a class have more than one parent class, and others don't allow it.",
    bad: "Giving a class many parents is the best way to combine features from several places, with no real downsides." },

  // --- Composition and when inheritance goes wrong ---
  { topic: "Composition over inheritance",
    good: "Holding smaller objects is often more flexible than inheriting from a big parent class.",
    neutral: "Composition means a class holds other objects in its fields and leans on them for part of its work.",
    bad: "Treat composition as a fallback for when inheritance gets blocked, and inherit first." },
  { topic: "Swapping behavior",
    good: "With composition you can swap a part while running, such as handing a report a new formatter.",
    neutral: "A class built by composition passes some of its work along to the objects it holds in its fields.",
    bad: "To change how an object behaves later, the only route is to write a brand new subclass." },
  { topic: "Deep hierarchies",
    good: "Deep inheritance trees are hard to follow, because one change at the top ripples down.",
    neutral: "A class hierarchy can be drawn as a tree; the most general class sits at the top of it.",
    bad: "A deeper hierarchy shows a more thorough design, and more levels make the code easier for a newcomer to read." },
  { topic: "Substitutability",
    good: "A subclass should work anywhere its parent is expected, without surprising the code that uses it.",
    neutral: "Substitutability is about whether one object can stand in for another in the same spot in the code.",
    bad: "A subclass can make the parent methods it dislikes throw errors, and callers will cope." },
  { topic: "Changing a parent class",
    good: "Editing a parent class can quietly break its children, so changes near the top need extra care.",
    neutral: "A change to a parent class reaches every child class that inherits the changed code, near or far.",
    bad: "Children are cut off from their parent once written, and editing the parent won't affect them." },
  { topic: "Preventing subclassing",
    good: "Marking a class final stops others extending it, protecting designs not built for subclassing.",
    neutral: "Many languages offer a way to mark a class so that no other class can extend it any further.",
    bad: "Keep every class open to subclassing; blocking it only makes code harder for other teams to reuse later." },
  { topic: "When inheritance goes wrong",
    good: "Inheritance goes wrong when a child wants a few parent methods and has to fight or hide the rest.",
    neutral: "Problems with inheritance don't always show up at once; they tend to appear as a hierarchy grows.",
    bad: "Two classes with a shared name pattern, such as UserManager and OrderManager, need one parent." }
,
  // --- Responsibilities ---
  { topic: "Single responsibility",
    good: "A class should have one reason to change; billing rules and email layout go in separate classes.",
    neutral: "Single responsibility is a guideline about how much work one class takes on; it isn't a size limit.",
    bad: "One responsibility means one method per class, and a second method is a sign to split it." },
  { topic: "Single responsibility in practice",
    good: "If you describe a class and keep saying \"and also\", it probably has more than one job.",
    neutral: "Splitting a class by responsibility usually leaves more classes overall, each one smaller than before.",
    bad: "Put every feature for a screen in one class, and the related code will be easy to find." },
  { topic: "Open/closed",
    good: "Open/closed means adding behavior with new code, like a new class, while working code stays put.",
    neutral: "The open/closed principle applies to modules and functions too, not only to classes.",
    bad: "Closed for modification means nobody may change a class once it's in use, not even to fix a bug." },
  { topic: "Interface segregation",
    good: "Prefer several small interfaces over one big one, so no class has to stub out methods it won't use.",
    neutral: "Interface segregation is about the size and shape of the interfaces a class depends on.",
    bad: "One large interface with lots of methods is easier to manage than several small ones." },
  { topic: "Dependency inversion",
    good: "High-level logic should depend on an abstraction, not on any specific database or mail service.",
    neutral: "Dependency inversion deals with which direction the dependencies between parts of a program point.",
    bad: "Dependency inversion means low-level classes call the high-level ones instead of the other way round." },

  // --- Coupling and cohesion ---
  { topic: "Coupling",
    good: "With loose coupling, a change in one class rarely forces edits in the other classes.",
    neutral: "Coupling describes how much one piece of code knows about, or relies on, another piece of code.",
    bad: "Aim for tight coupling between classes, since it shows they cooperate closely and share data." },
  { topic: "Cohesion",
    good: "A cohesive class is one whose fields and methods belong together and serve one purpose.",
    neutral: "Cohesion describes a single class or module; it doesn't describe the links between classes.",
    bad: "Low cohesion is preferable, since a class with varied methods can be reused in more places." },
  { topic: "Coupling vs cohesion",
    good: "Aim for high cohesion inside a class and low coupling between classes; each goal helps the other.",
    neutral: "Coupling and cohesion are separate ideas, though they often show up in the same design talk.",
    bad: "Coupling and cohesion are two names for the same idea, and tracking one of them is enough." },
  { topic: "Separation of concerns",
    good: "Keep display, business rules, and storage apart, so changing one part doesn't break the rest.",
    neutral: "Separation of concerns isn't only for big systems; it applies from a single method up to a whole app.",
    bad: "Separating concerns only matters in big systems, while a small app does better with everything mixed." },

  // --- Simplicity ---
  { topic: "DRY",
    good: "Don't repeat yourself means each piece of knowledge, like a tax rule, lives in one place.",
    neutral: "Pull repeated logic into a well-named method when you notice it in two or three spots in a class.",
    bad: "When two blocks of code look alike, merge them at once, even if they mean different things." },
  { topic: "Overdoing DRY",
    good: "Merging code that only looks similar can hurt when the two uses change for different reasons.",
    neutral: "Some duplication does no harm, while other duplication causes bugs when one copy gets missed.",
    bad: "Duplication is the worst problem a codebase can have, worse than confusing abstractions." },
  { topic: "YAGNI",
    good: "Build for today's requirements; features someone might want later can wait until they're real.",
    neutral: "YAGNI reminds you to ask whether a feature is needed right now, before you build it.",
    bad: "Add hooks and settings for future cases up front; later changes cost far more than early ones." },
  { topic: "Keep it simple",
    good: "The simplest design that meets the need is usually best; it's easier to read, test, and change.",
    neutral: "Simple code still needs good names and a clear structure to be easy to work with day to day.",
    bad: "Clever, compact code always shows skill, and teammates learn a lot by working out what it does." },

  // --- Dependencies ---
  { topic: "Dependency injection",
    good: "With dependency injection, a class gets its helpers passed in rather than creating them itself.",
    neutral: "Dependencies are often passed through the constructor, though a method parameter works too.",
    bad: "Dependency injection needs a big framework behind it, and without one it can't really be done." },
  { topic: "Injection and testing",
    good: "When a dependency is passed in, a test can hand over a fake version and check the class alone.",
    neutral: "A test for a class often needs some way to control what its helper objects return to it.",
    bad: "Creating helpers inside the class is better for tests, since the test then uses the real thing." },
  { topic: "Programming to an interface",
    good: "Code against what an object can do, not its exact class, so you can swap in any version that fits.",
    neutral: "Declare a variable as an interface type when the code only uses what that interface offers.",
    bad: "Interfaces just add extra files, and depending on the concrete class is clearer and easier to follow." },
  { topic: "Hidden dependencies",
    good: "A class that quietly reaches for global state is hard to test; pass that state in instead.",
    neutral: "A global variable can be read from anywhere in a program, so it's always within reach.",
    bad: "Global state makes a class easier to test, since the test has nothing to set up or pass in." },

  // --- Class and method shape ---
  { topic: "God objects",
    good: "A god object knows and does too much, and nearly every change has to touch it, which makes it fragile.",
    neutral: "A god object tends to be one of the largest classes in the codebase; it often has many fields.",
    bad: "Putting the main logic in one central class is good design: there's one place to look." },
  { topic: "Tell, don't ask",
    good: "Tell an object what to do instead of pulling its data out and making its decision for it elsewhere.",
    neutral: "Tell-don't-ask is a guideline about where decisions, and the data behind them, should sit.",
    bad: "Objects should mostly expose getters and let the calling code make the real decisions about them." },
  { topic: "Talking to close neighbors",
    good: "A method should talk to its own fields and parameters, not reach through a long chain of objects.",
    neutral: "A long chain of calls through several objects can be hard to read at a glance; keep chains short.",
    bad: "Reaching through several objects to get a value is good practice because it saves writing methods." },
  { topic: "Side effects",
    good: "A method that sounds like it only calculates shouldn't also save to the database.",
    neutral: "A side effect is any change a method makes beyond returning a value, such as writing a file.",
    bad: "Letting a getter also update state is handy, and it saves the caller a separate method call." },
  { topic: "Readable method names",
    good: "A good method name says what it does, so the caller doesn't need to read its body to use it.",
    neutral: "Method names are usually verbs or verb phrases, because a method is something an object does.",
    bad: "Short, generic names are better for methods; the comments above each method can explain the rest." },
  { topic: "Small focused methods",
    good: "Small methods that each do just one thing are easier to name, test, and reuse.",
    neutral: "Breaking a long method into named steps can make the overall flow easier to follow.",
    bad: "Long methods are usually easier to read, with all the logic on one screen and no jumping around." },
  { topic: "Too many parameters",
    good: "A method with many parameters is often doing too much, or the values belong in one object.",
    neutral: "Every parameter is one more thing a caller has to supply and pass in the right order.",
    bad: "Parameter count doesn't matter much; a method taking ten arguments is as clear as one taking two." },
  { topic: "Boolean flag parameters",
    good: "A true/false flag that switches a method between two jobs usually means it should be two methods.",
    neutral: "A boolean parameter allows just two values, so the call site shows only true or false.",
    bad: "Adding a flag parameter is the best way to reuse a method for a new case that's slightly different." }
,
  // --- Patterns in general ---
  { topic: "What patterns are for",
    good: "Patterns give a team shared names for solutions to design problems that keep coming back.",
    neutral: "A design pattern describes the general shape of a solution, not a specific piece of code you copy.",
    bad: "Patterns are ready-made code to paste in, and adding more of them tends to make a design better." },
  { topic: "Overusing patterns",
    good: "Reach for a pattern when a real problem calls for it, since forcing one in early adds extra layers.",
    neutral: "Picking a pattern starts with understanding the problem you're trying to solve.",
    bad: "A strong design uses as many patterns as it can fit, with each one adding flexibility at no real cost." },
  // --- Creating objects ---
  { topic: "Singleton",
    good: "A singleton keeps one shared instance, which acts a lot like a global variable in practice.",
    neutral: "With a singleton, the class itself controls access to its one shared instance; nobody else creates it.",
    bad: "Make each service a singleton; one copy of everything keeps the program tidy and organized." },
  { topic: "Alternatives to a singleton",
    good: "Instead of a singleton, you can create one instance at startup and pass it to whatever needs it.",
    neutral: "Configuration and logging objects are frequent places to find one shared instance in a program.",
    bad: "Any object that several classes share has to be a singleton; there's no other way to share it." },
  { topic: "Factory",
    good: "A factory is a method or object that decides which class to create, so callers don't need to know.",
    neutral: "Factories create objects for you, and their return type is often an interface rather than a class.",
    bad: "Factories should replace constructors everywhere, and calling a constructor directly is a design mistake." },
  { topic: "Builder",
    good: "A builder is handy for objects with lots of optional settings; you set what you need and then build.",
    neutral: "With a builder, you set the parts you want and then ask it for the finished object.",
    bad: "Use a builder for each class, even ones with two fields, to keep object creation consistent." },
  // --- Behavior patterns ---
  { topic: "Strategy",
    good: "Strategy puts each version of an algorithm in its own object, and the caller can swap them freely.",
    neutral: "A strategy object holds one way of doing a task, like one way to work out shipping, and nothing else.",
    bad: "Strategy means one big method with a switch that covers every option the program supports." },
  { topic: "Observer",
    good: "With observer, a subject sends out events and doesn't care which objects happen to be listening.",
    neutral: "In the observer pattern, listeners get notified when something changes, so they don't have to keep checking.",
    bad: "The subject in observer has to know each listener's exact class before it can send updates." },
  { topic: "Unsubscribing listeners",
    good: "Listeners that never unsubscribe can keep old objects alive long after they stopped being useful.",
    neutral: "An observer usually registers with a subject and can remove itself later, when it's done.",
    bad: "Once a listener is registered, leave it there for good; extra notifications here and there cost nothing." },
  { topic: "Template Method",
    good: "Template method sets the order of steps in a parent class, while subclasses fill in a few of them.",
    neutral: "In template method, the parent class owns the overall algorithm rather than any subclass.",
    bad: "Template method means copying the same algorithm into each subclass and tweaking each copy." },
  { topic: "Command",
    good: "The command pattern turns a request into an object, which makes undo and queuing easier to add.",
    neutral: "A command object usually has one method that carries out the action it stands for, and little else.",
    bad: "Command objects are only useful for menu buttons in desktop apps, not in other kinds of programs." },
  { topic: "Iterator",
    good: "An iterator lets you walk through a collection without knowing how it's stored inside.",
    neutral: "Iterators hand out items one at a time and tell you when there are no more left to give.",
    bad: "To loop over a collection, callers need to know whether it's a list, a tree or a hash table." },
  // --- Wrapping patterns ---
  { topic: "Decorator",
    good: "A decorator wraps an object to add behavior like logging, and it keeps the same interface.",
    neutral: "Decorators can be stacked; each wrapper adds one extra piece of behavior around the next.",
    bad: "A decorator edits the original class's code directly to add the new feature it provides." },
  { topic: "Adapter",
    good: "An adapter wraps a class with an awkward interface so it fits the one your code expects.",
    neutral: "Adapters often show up at the edges of a system, near outside services and older code.",
    bad: "An adapter's job is adding new features, like logging, not translating between two interfaces." },
  { topic: "Facade",
    good: "A facade gives one simple entry point to a messy subsystem; callers can still go around it if needed.",
    neutral: "A facade sits in front of several classes and gives them one simpler shared interface.",
    bad: "A facade should copy all the logic of the subsystem, because then the subsystem can be deleted." },
  // --- Application structure ---
  { topic: "MVC",
    good: "MVC keeps data and rules in the model, display in the view, and input handling in the controller.",
    neutral: "MVC splits an application into three parts, called the model, the view and the controller.",
    bad: "In MVC, business rules belong in the view, since that is the part closest to the user." },
  { topic: "Repository",
    good: "A repository hides how data is stored, and the rest of the code asks it for objects, not queries.",
    neutral: "A repository usually has methods to add, find and remove one kind of object, such as orders.",
    bad: "A repository should hand back raw database rows and let each caller build its own objects." },
  // --- Testing ---
  { topic: "Unit testing objects",
    good: "Test an object through its public methods, since tests on private details break on every refactor.",
    neutral: "A unit test creates an object, calls a method on it, and checks what comes back from the call.",
    bad: "Each private method needs its own test, or else you can't trust that the class works." },
  { topic: "Designing for tests",
    good: "Objects that take their dependencies as inputs are easier to test with simple stand-ins.",
    neutral: "Small classes with clear inputs and outputs tend to be easier to test, because there's less to set up.",
    bad: "A hard-to-test class is a problem with the tests rather than with the design of the code." },
  { topic: "Mocks and fakes",
    good: "A fake is a simple working stand-in, while a mock records calls so a test can check them.",
    neutral: "Mocks and fakes both stand in for real parts like a database, but they aren't the real thing.",
    bad: "Mocks and fakes are the same thing; the names are two different words for one test double." },
  { topic: "Too many mocks",
    good: "Mocking every collaborator ties tests to internals; they can pass even when real behavior is broken.",
    neutral: "A test with fewer mocks often reads more like a plain description of what the code does.",
    bad: "The more mocks a test uses, the better isolated and more trustworthy it becomes." },
  // --- Keeping code healthy ---
  { topic: "Refactoring",
    good: "Refactoring changes how code is structured without changing what it does, ideally in small steps.",
    neutral: "Refactoring can mean renaming things, splitting methods or moving code to a better class.",
    bad: "Refactoring is a good time to add new features too, since both touch the same code anyway." },
  { topic: "Code smells",
    good: "A code smell like a huge class is a hint to look closer, not proof that there's a bug.",
    neutral: "Duplicated code, long methods and vague names all count as code smells worth a second look.",
    bad: "A code smell means the program has a bug, so it should be fixed before the next release." },
  // --- Styles ---
  { topic: "OOP vs functional style",
    good: "OOP bundles data with the behavior that changes it; functional style favors pure functions on plain data.",
    neutral: "Object-oriented and functional styles both aim to keep large programs organized and readable.",
    bad: "A project has to pick one style instead of mixing functional ideas into object-oriented code." },
  { topic: "Mixing styles",
    good: "Plenty of codebases mix the two, using objects for structure and small pure functions for logic.",
    neutral: "Immutable objects fit nicely in both object-oriented and functional code, since they never change.",
    bad: "Objects should change their own state whenever they can; immutability is a functional-only idea." }
] };
