// Object-oriented programming intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "Object-Oriented Programming", turns: [
  // --- Objects, encapsulation, abstraction ---
  { topic: "Objects and classes",
    good: "Each object gets its own copy of the instance fields, and all objects of a class share one copy of the method code.",
    neutral: "Classes and objects show up in nearly every mainstream language; most codebases contain both in large numbers, so you meet them early.",
    bad: "Every object carries its own private copy of each method body, which is why creating many small objects wastes a lot of memory." },
  { topic: "Encapsulation",
    good: "Encapsulation is the object controlling how its own state changes: callers go through methods that can enforce the rules.",
    neutral: "Encapsulation tends to show up as private fields wrapped in public methods, and it applies to modules as well as to classes.",
    bad: "Making the fields private and then adding a public getter and setter for each of them is what achieves encapsulation." },
  { topic: "Abstraction",
    good: "An abstraction pays off when callers can rely on what it promises and ignore how it works. A leaky one forces them to learn internals.",
    neutral: "Abstraction is about hiding detail; in code it tends to appear as interfaces, base classes, modules, and function signatures.",
    bad: "Wrap each dependency in its own interface from day one; more layers of abstraction make code easier to change later." },
  { topic: "Class invariants",
    good: "A class invariant holds after construction and after each public method returns; private helpers may break it briefly in between.",
    neutral: "Invariants are conditions about an object's state. They aren't always written down, though some teams add assertions for them.",
    bad: "Invariants belong in the calling code: the caller knows the context best and should check the object is valid before using it." },
  // --- Construction ---
  { topic: "Constructor validation",
    good: "A constructor should leave the object fully valid or throw; half-built objects needing init() push the invariant onto callers.",
    neutral: "Constructors run when an object is created, and many languages let a class declare several of them with different parameter lists.",
    bad: "Constructors shouldn't throw exceptions. Create the object in a default state and let a separate validate() method report problems." },
  { topic: "Work in constructors",
    good: "Doing I/O or network calls in a constructor makes the class hard to test, so pass in what it needs or use a factory method.",
    neutral: "Some constructors only assign fields; others contain a fair amount of setup logic before they finish and hand back the object.",
    bad: "Put connection setup and file loading in the constructor. Then each object arrives ready to use, and tests get that for free." },
  { topic: "Escaping this",
    good: "Letting this escape a constructor, say by registering a listener, lets other code see the object before its fields are set.",
    neutral: "Constructors can pass this to other objects; the pattern turns up in event registration and in some parent-child object setups.",
    bad: "Once the field assignments come before the line that passes this out, other threads see those fields set, even without final or volatile." },
  // --- Identity and equality ---
  { topic: "Identity vs equality",
    good: "Identity asks whether two references point at the same object; equality asks whether they hold the same value by the class's rules.",
    neutral: "In Java you compare with == or equals(), and in Python with is or ==, and the two forms read a little differently in code.",
    bad: "In Java, == on two String variables compares their characters; equals() is an older spelling kept for compatibility." },
  { topic: "equals and hashCode",
    good: "Override hashCode whenever you override equals in Java or C#. Equal objects must hash alike or HashMap lookups fail.",
    neutral: "Java's Object class defines both equals and hashCode, so every class you write inherits a default version of each one from it.",
    bad: "hashCode matters for performance alone. If two equal objects hash differently, a HashMap still finds them, more slowly." },
  { topic: "Mutable hash keys",
    good: "Mutating a field that feeds hashCode while the object sits in a HashSet strands it in the wrong bucket; contains() then misses it.",
    neutral: "Strings and boxed integers are safe hash keys in Java, and HashSet and HashMap are among the most used collection classes.",
    bad: "A HashSet rehashes an element whenever one of its fields changes, so contains() keeps finding mutable members after you edit them." },
  { topic: "Value objects",
    good: "A value object like Money has no identity of its own: two with equal fields are interchangeable, and it's usually immutable.",
    neutral: "Value objects tend to be small classes wrapping a few related fields, like an amount with a currency or a start date with an end date.",
    bad: "A value object needs a database ID so you can tell two instances apart, even when every field in them holds the same data." },
  { topic: "Entities",
    good: "An entity is an object like a Customer that keeps its identity as its attributes change, so equals usually compares an ID.",
    neutral: "Entities and value objects are both modeled as classes. A typical domain has a mix of the two, not one or the other.",
    bad: "Entities should compare every field in equals: two Customer objects with different addresses can't possibly be the same customer." },
  { topic: "Records and data classes",
    good: "Java records, C# records, and Python dataclasses generate equality from fields, which suits value objects better than entities.",
    neutral: "Java added records in version 16 in 2021, and C# 9 shipped its own record types a few months before that, in late 2020.",
    bad: "Java records are mutable by default. Their generated setters let you update fields, and you add final to lock them down." },
  // --- Immutability ---
  { topic: "Immutability",
    good: "Sharing immutable objects across threads is safe without locks or copies, because no one can change them after construction.",
    neutral: "Immutable objects can't be changed once built, so changing a value means creating a new object with the updated fields.",
    bad: "Immutable objects are mainly a functional-programming habit; in OOP code they add allocation cost while buying you very little back." },
  { topic: "final vs immutable",
    good: "Java's final and C#'s readonly fix the reference, not the object, so a final List field can still have items added to it.",
    neutral: "Marking a field final in Java means the compiler checks that it is assigned exactly once, usually in the constructor or initializer.",
    bad: "Declaring every field final makes a Java class deeply immutable: that includes any lists or maps those fields reference." },
  { topic: "Defensive copies",
    good: "If a constructor keeps the caller's mutable list as-is, the caller can still change your state; copy it in or wrap it read-only.",
    neutral: "Copying collections in and out of objects creates extra objects along the way, and for small lists the cost is rarely noticeable.",
    bad: "Returning your internal list from a getter can't expose it while the field is private, because private blocks outside code from changing it." },
  // --- Accessors and visibility ---
  { topic: "Getters and setters",
    good: "A setter per field exposes state as surely as a public field does. Better methods name the operation, like withdraw() over setBalance().",
    neutral: "Name getters and setters consistently, as getX and setX, so readers can find each pair without hunting through the class.",
    bad: "Once each field has a getter and setter, the class can change its fields' types freely, since outside code never touches them directly." },
  { topic: "Properties",
    good: "Python's @property lets a plain attribute later gain logic without changing call sites, so trivial getters aren't needed up front.",
    neutral: "In Python, @property is a decorator placed above a method, and the method then reads like an attribute when you read it on an instance.",
    bad: "A Python @property caches its result after the first access. Calling it is as cheap as reading a plain attribute each time." },
  { topic: "Access modifiers",
    good: "In Java and C#, private is per class, not per object: one instance's method can read another instance's private fields.",
    neutral: "Mark fields private unless there's a reason not to, and keep the list of public members on a class short and easy to scan.",
    bad: "Private fields are a security boundary; reflection and debuggers can't get at them, so passwords held there can't leak from memory." },
  { topic: "protected",
    good: "protected widens access to subclasses, which turns those members into part of your API that subclasses will come to depend on.",
    neutral: "protected sits between private and public: Java also lets classes in the same package see protected members.",
    bad: "Making fields protected hides them from outside code while giving subclasses what they need, so it's the best default for fields." },
  { topic: "Python privacy",
    good: "Python has no enforced private members: a single leading underscore is a convention, and double underscore only mangles the name.",
    neutral: "Python code often uses leading underscores on attribute names, and the PEP 8 style guide discusses them in its section on naming.",
    bad: "Python's double-underscore prefix makes an attribute truly private, with no way for code outside the class to read or write it." },
  // --- Static, self, lifecycle ---
  { topic: "Static vs instance",
    good: "Static members belong to the class, not an instance; static mutable state is shared global state with all its test pains.",
    neutral: "Static methods are called on the class name rather than on an object, which in Java or C# looks like Math.max(a, b).",
    bad: "Make helper methods static whenever possible, because static calls are the easy ones to mock and swap out in unit tests." },
  { topic: "this and self",
    good: "Python makes self an explicit first parameter while Java and C# pass this implicitly; either way it's the receiving object.",
    neutral: "this and self are how a method refers to its own object; some styles write this. before every field, others only when needed.",
    bad: "In a Python method you can leave self out of the parameter list: the interpreter adds it for you when the method is called." },
  { topic: "Garbage collection",
    good: "A garbage collector frees unreachable objects, not ones you stopped using, so a forgotten entry in a static cache keeps them alive.",
    neutral: "Java, C#, and Python all reclaim memory automatically, so there is no free() call; their collectors differ under the hood.",
    bad: "Finalizers in Java and C# run as soon as an object becomes unreachable, so they are a good place to close files and sockets." },
  { topic: "Deterministic cleanup",
    good: "For files and sockets, use deterministic cleanup: try-with-resources in Java, using in C#, with in Python, or RAII in C++.",
    neutral: "Objects that hold resources usually have some close or dispose method; the name varies a bit from one language to the next.",
    bad: "In C++, objects on the stack must be deleted explicitly at the end of the function, or their destructors are never called." }
,
  // --- Subtyping and dispatch ---
  { topic: "Subtyping vs subclassing",
    good: "Subtyping is a promise of substitutability, and subclassing is code reuse. A subclass that breaks its parent's contract is no subtype.",
    neutral: "A subclass is declared with a keyword such as extends in Java or a base list in Python, and it inherits the parent's fields and methods.",
    bad: "If the compiler accepts class B extends A, then B is a valid subtype of A; the type checker verifies behavior too." },
  { topic: "Dynamic dispatch",
    good: "A call through a base reference runs the override chosen by the object's runtime class, typically via a vtable lookup.",
    neutral: "Dynamic dispatch shows up in most class-based languages; it lets one call site end up running different code for different objects.",
    bad: "The method that runs is picked from the variable's declared type. To reach the subclass version, cast the reference down first." },
  { topic: "Overriding vs overloading",
    good: "Overriding replaces a subclass method and resolves at runtime, while overloading adds same-named methods picked at compile time.",
    neutral: "Both overriding and overloading reuse one method name for several bodies, so a reader of the call site has to check which one is in play.",
    bad: "Overloading is runtime polymorphism, and Java inspects each argument's actual class when the call runs to pick the closest overload." },
  { topic: "Overload resolution gotcha",
    good: "Java gotcha: an Object-typed variable holding a String calls the Object overload, since overloads bind from static types.",
    neutral: "Java and C# let a class declare several methods with one name, so long as their parameter lists differ in count or types.",
    bad: "Overload choice follows the argument's runtime class: a String stored in an Object variable still reaches the String overload." },
  { topic: "Double dispatch",
    good: "Java and C# dispatch on the receiver alone, which is why the Visitor pattern simulates double dispatch with a second call.",
    neutral: "Choosing behavior from the types of two objects at once shows up in collision handling and serializers, rather than in everyday CRUD code.",
    bad: "Java picks an override using the runtime types of the receiver and the arguments; collide(a, b) needs no extra pattern." },

  // --- Abstract types ---
  { topic: "Abstract class vs interface",
    good: "Use an abstract class to share state and constructor logic among close relatives, and an interface for any capability unrelated types share.",
    neutral: "An abstract class can't be instantiated directly. An interface lists the methods that implementing classes must provide.",
    bad: "Prefer abstract classes over interfaces, as Java and C# let one class extend several abstract classes at once and mix their code." },
  { topic: "Default interface methods",
    good: "Java 8 default methods let an interface grow a method without breaking existing implementers (they still can't hold instance state).",
    neutral: "Java interfaces are allowed to contain method bodies marked default, and C# 8 added a similar feature for its interfaces.",
    bad: "With Java 8 default methods, interfaces also gained instance fields, and now an interface can do whatever an abstract class can." },
  { topic: "Deep hierarchies",
    good: "In a deep hierarchy, learning what one method does means reading up through every ancestor, and an edit near the root reaches all below.",
    neutral: "Keep an inheritance tree small enough that you can sketch the whole thing on one whiteboard without running out of room.",
    bad: "Deeper hierarchies mean more reuse, so adding an intermediate base class for each shared method keeps every change local to one level." },

  // --- Substitution ---
  { topic: "Liskov substitution",
    good: "A subtype can't strengthen preconditions or weaken postconditions; code written against the base type must keep working.",
    neutral: "Liskov substitution concerns subtypes and their base types, and it applies to interface implementations as well as to subclasses.",
    bad: "LSP holds whenever a subclass compiles with the same method signatures as its parent; behavior is up to each override to decide." },
  { topic: "Square extends Rectangle",
    good: "If Rectangle has independent width and height setters, a mutable Square can't honor that contract. Immutable shapes avoid the clash.",
    neutral: "Mathematically, a square counts as a rectangle; modeling Square as a subclass of Rectangle feels natural in a first draft.",
    bad: "Square extending Rectangle holds up once its setWidth override also sets the height, since each caller then sees a valid square." },
  { topic: "Throwing in an override",
    good: "Overrides that throw UnsupportedOperationException surprise callers of the base type, and Java's optional List methods are a known wart.",
    neutral: "Java's collection interfaces have optional operations: some List implementations document that add or remove may throw.",
    bad: "Throwing NotImplemented from an override keeps LSP intact, because the method signature still matches the parent's exactly." },

  // --- Composition and fragility ---
  { topic: "Composition over inheritance",
    good: "Delegating to a held collaborator lets you swap behavior at runtime, whereas extending exposes the parent's whole API.",
    neutral: "With composition, one object holds references to others in its fields and forwards some calls to them instead of inheriting.",
    bad: "Languages without inheritance fall back on composition. When you can extend a class, subclassing gives the same reuse with less coupling." },
  { topic: "Fragile base class",
    good: "A subclass of HashSet counting adds in both add and addAll double counts, because the parent's addAll calls add internally.",
    neutral: "Fragile base class trouble shows up most in big codebases and libraries, where whoever edits a parent rarely sees every subclass.",
    bad: "Base classes become fragile when they lack tests. With good coverage, internal changes in a parent won't break subclasses." },
  { topic: "Super calls",
    good: "Whether an override must call super, and when, is often an unwritten contract. A template method makes it explicit.",
    neutral: "Calling super runs the parent class's version of a method, and in Python 3 it is fine to write super() with no arguments in a method.",
    bad: "The compiler inserts a super call at the top of each override. You get the parent's behavior plus yours without writing it out." },
  { topic: "Virtual calls in constructors",
    good: "In Java and C#, a base constructor that calls an overridable method runs the subclass override before the subclass constructor body has run.",
    neutral: "Constructors run from the base class down to the most derived one, and a constructor body is free to call other methods on the object.",
    bad: "An overridable method called from a Java base constructor sees subclass fields already set; the JVM runs their initializers first." },
  { topic: "C++ constructor dispatch",
    good: "In C++, a virtual call inside a base constructor runs the base version; during construction the object's dynamic type is still the base.",
    neutral: "C++ uses the virtual keyword to mark methods that derived classes may override, and override documents that intent at the derived side.",
    bad: "C++ matches Java here, and a virtual call in a base constructor reaches the derived override even though derived members aren't built." },

  // --- Multiple inheritance and reuse ---
  { topic: "Diamond problem",
    good: "With B and C both extending A and D extending both, two questions arise: does D hold one A or two, and which shared override wins?",
    neutral: "The diamond problem takes its label from the shape of the class diagram, not from anything in the code: one base on top, one class below.",
    bad: "Java has no diamond issue. A class implementing two interfaces with the same default method never has to resolve the clash." },
  { topic: "Python MRO",
    good: "Python linearizes bases with C3, and super() follows that MRO rather than the literal parent, enabling cooperative mixins.",
    neutral: "Print a class's __mro__ attribute at the REPL to see a tuple holding the class and its ancestors; it lists them in lookup order.",
    bad: "In Python, super() calls the parent named in the class statement, and with multiple bases it picks the leftmost one each time." },
  { topic: "Mixins and traits",
    good: "Mixins add a slice of behavior to unrelated classes without a deep hierarchy, at the cost of hidden coupling to host attributes.",
    neutral: "Mixin classes are usually small and narrowly focused, and in Python they tend to be listed before the main base class.",
    bad: "A mixin should be usable on its own; if it needs attributes from the host class, it's a broken mixin and belongs in a base class." },
  { topic: "C++ virtual inheritance",
    good: "Declare the shared base virtual in C++: a diamond then gets one base subobject, and the most derived class constructs that base itself.",
    neutral: "C++ lets a class list several base classes (it is one of the few mainstream languages with multiple inheritance of implementation).",
    bad: "C++ merges a diamond's shared base into one copy by default, and virtual inheritance can then shrink the objects a bit further." },

  // --- Variance and typing ---
  { topic: "Covariant return types",
    good: "An override may return a narrower type, like clone() returning Dog. That is safe, since callers expecting an Animal still get one.",
    neutral: "Java has allowed covariant return types on overrides since version 5, and C# 9 added the same support for class overrides.",
    bad: "An override must return exactly the parent's declared type (narrowing it to a subtype breaks substitution for callers of the base method)." },
  { topic: "Generic variance",
    good: "Producers can be covariant and consumers contravariant. C# marks this with out and in; Java uses ? extends and ? super at the use site.",
    neutral: "Variance describes how subtyping between type arguments relates to subtyping between the generic types built from them, in both directions.",
    bad: "In Java, a List<Cat> is a List<Animal>: generics inherit their element subtyping, and the compiler stops a bad insert." },
  { topic: "Array covariance",
    good: "Array covariance is a hole in Java's typing: an Integer stored into an Object[] that is really a String[] compiles, then throws at runtime.",
    neutral: "Arrays in Java and C# carry their element type at runtime, which Java reflection exposes through getClass().getComponentType().",
    bad: "Java arrays are invariant like generics: String[] won't convert to Object[], and the compiler rejects that assignment outright." },
  { topic: "Duck typing",
    good: "Python duck typing finds a method only when it's called. Protocols add static structural checks for mypy and leave runtime alone.",
    neutral: "Python code tends to lean on duck typing, calling whatever methods an object has rather than checking its declared class first.",
    bad: "With duck typing, Python 3 checks at import time that each argument passed to a function has the needed methods, as an interface would." },

  // --- Closing hierarchies ---
  { topic: "Sealed and final classes",
    good: "Sealed classes list their permitted subclasses, letting a switch check exhaustiveness; final forbids subclassing to protect invariants.",
    neutral: "Check your Java version before writing sealed classes, since the permits clause only became a standard feature in Java 17.",
    bad: "Marking classes final is mainly a speed trick for old JVMs. On a modern runtime it is a style choice with zero design effect." }
,
  // --- SOLID ---
  { topic: "Single responsibility",
    good: "A class should have one reason to change, meaning one actor whose new requirements would force edits to it.",
    neutral: "Classes built around one responsibility end up with shorter files; their names are easier to choose and to remember.",
    bad: "Single responsibility: each class exposes exactly one public method, and a second public method means it's time to split." },
  { topic: "Open/closed",
    good: "Open/closed asks that new behavior arrive as new code plugged into an extension point (a strategy or subclass) rather than edits to it.",
    neutral: "Open/closed is about letting a module grow over time, so the parts that already work don't need to be reopened very often.",
    bad: "Open/closed says a shipped class is final; later changes go into a copy of it with a version suffix on the end." },
  { topic: "Interface segregation",
    good: "Split fat interfaces by what each caller actually uses, so that no client depends on methods it never calls.",
    neutral: "Interface segregation produces more interfaces in a codebase, each one carrying fewer methods than before.",
    bad: "Interface segregation is the rule of one method per interface rather than grouped operations; two methods is a violation." },
  { topic: "Dependency inversion",
    good: "High-level policy and low-level detail both depend on an abstraction, and the policy side is the one that owns it.",
    neutral: "Applying dependency inversion adds an interface between two layers, and the arrows on a dependency diagram change direction.",
    bad: "Dependency inversion is satisfied by a DI container. Once a framework wires your objects (Spring, Guice) you're done." },
  { topic: "Program to an interface",
    good: "Declare parameters by the narrowest type that offers what you need; callers can then pass any fitting implementation.",
    neutral: "Code written this way usually refers to List or Map (ArrayList appears only at the point where the object is created).",
    bad: "Program to an interface means giving each class a matching interface, even ones with one implementation and no double." },

  // --- Coupling and cohesion ---
  { topic: "Coupling",
    good: "Coupling is how much one module must know about another. The less it knows, the fewer changes ripple across.",
    neutral: "Coupling takes several forms (shared data, call order, assumed formats), and some of them are easier to see than others.",
    bad: "Coupling lives in import statements; route everything through a shared event bus rather than imports and it can go away." },
  { topic: "Cohesion",
    good: "High cohesion: a module's parts work on the same data toward one purpose. Low cohesion is a grab bag of reasons to change.",
    neutral: "Cohesion applies at several scales: a function, a class, a package or a whole service can each be more or less cohesive.",
    bad: "Put related utilities in one Helpers class to raise cohesion, because keeping them in one file is what cohesive means." },
  { topic: "Temporal coupling",
    good: "Temporal coupling is hidden order (init() before run()); make the constructor or the type system enforce it.",
    neutral: "Temporal coupling can show up as a test that passes alone but fails in a suite, depending on the setup order.",
    bad: "Temporal coupling is safe once the required call order is written in the class comment for callers to read and follow." },
  { topic: "Stable dependencies",
    good: "Point dependencies toward stability: volatile code should lean on modules that rarely change, not the reverse.",
    neutral: "Some modules change every sprint while others barely move for years, and that difference ends up shaping the design.",
    bad: "Shared core modules should import from feature modules, so the core can react to whatever the features need." },

  // --- Demeter and tell-don't-ask ---
  { topic: "Law of Demeter",
    good: "Talk to immediate collaborators, not strangers reached through them. a.getB().getC().run() is the shape to notice.",
    neutral: "Code that follows the Law of Demeter tends to have short call chains, with most lines stopping after one or two dots.",
    bad: "Demeter is purely about dot counts. Splitting a.b().c() across three local variables fully fixes the violation." },
  { topic: "Tell, don't ask",
    good: "Instead of pulling state out of an object to make a decision, send it a message and let it act on its own data.",
    neutral: "Tell, don't ask concerns where a decision lives, and it applies to small value objects as much as to large services.",
    bad: "Tell, don't ask forbids getters, and an object that exposes any field for reading has broken encapsulation." },
  { topic: "Feature envy",
    good: "Feature envy is a method more interested in another class's data than its own; moving it there is usually the fix.",
    neutral: "Feature envy shows up between classes in the same package, or even in the same file, as well as across modules.",
    bad: "Feature envy is cured by copying the fields a method needs into its own class instead of reaching across to read them." },

  // --- Dependency injection ---
  { topic: "Dependency injection",
    good: "An object is handed its collaborators from outside and never builds them, which makes swapping them in tests easy.",
    neutral: "Dependency injection adds parameters to constructors; in larger apps the wiring code can grow to fill several files.",
    bad: "Dependency injection requires a container. Passing collaborators by hand in a constructor is a different pattern." },
  { topic: "Constructor injection",
    good: "Prefer constructor injection for required collaborators, since the object is valid once built and its needs are visible.",
    neutral: "Constructor injection is the style that lists dependencies as constructor parameters, visible to a reader at a glance.",
    bad: "Use setter injection for required parts such as repositories: an object can be built empty and filled in later." },
  { topic: "Inversion of control",
    good: "With inversion of control the framework owns the flow and calls your handlers or hooks; DI is one narrow case of it.",
    neutral: "Learn a framework's lifecycle before leaning on its inversion of control, so you know which of your hooks it will call.",
    bad: "Inversion of control means the subclass drives the base class, the reverse of the usual direction in inheritance." },
  { topic: "Service locator",
    good: "A service locator is a global registry that code pulls dependencies from, which hides them from signatures and hurts tests.",
    neutral: "Code using a service locator calls something like Services.get(Repo.class) at each spot where it needs a collaborator.",
    bad: "Service locators improve on DI: pulling dependencies from a static registry keeps constructors short and hides nothing." },
  { topic: "Composition root",
    good: "Wire the object graph in one composition root near the entry point. Everything else takes what it is given.",
    neutral: "Every program has to construct its objects somewhere, and in most apps that happens early, during startup or bootstrapping.",
    bad: "Each class should build its own dependencies in its constructor instead of receiving them, keeping wiring near its use." },

  // --- Abstraction economics ---
  { topic: "DRY",
    good: "DRY is about knowledge rather than text. Two blocks that look alike may encode different rules that change apart.",
    neutral: "Don't repeat yourself reaches past code; config files, schemas and build scripts hold duplicated facts at times too.",
    bad: "Merge any two code blocks that look the same into a shared function, even if they serve unrelated features." },
  { topic: "Wrong abstraction",
    good: "A wrong abstraction grows flags and special cases. Inlining it into callers and re-extracting is often cheaper.",
    neutral: "Abstractions drift as requirements change; one that was a fine fit at first may sit awkwardly with its callers later.",
    bad: "Once a shared abstraction exists, add a parameter per new case; duplication costs more than any number of flags." },
  { topic: "YAGNI",
    good: "Don't build for a speculative need: you pay for the code now, and the guess about the future is often wrong.",
    neutral: "YAGNI comes out of extreme programming; it pairs with keeping the design simple until there's a reason.",
    bad: "YAGNI means skipping tests and refactoring until a bug forces them. Work that isn't a shipped feature isn't needed." },
  { topic: "Leaky abstraction",
    good: "A leaky abstraction forces callers to know what's underneath, like an ORM whose generated queries you must tune by hand.",
    neutral: "Abstractions sit in layers, and a single request may pass through several of them on its way down to the hardware.",
    bad: "A well-built abstraction hides all of its implementation, so callers never need to think about its performance." },

  // --- Domain modeling ---
  { topic: "Anemic domain model",
    good: "Entities that are bags of getters and setters, with services holding all the rules, leave their invariants unguarded.",
    neutral: "In an anemic model the entity classes look a lot like database rows, with service classes sitting beside them.",
    bad: "Anemic models keep concerns apart correctly. Behavior on entities mixes concerns, so logic belongs in stateless services." },
  { topic: "God object",
    good: "A god object knows and does too much; everything depends on it, so every change touches it and its tests.",
    neutral: "God objects are rarely small: they're often among the largest files in a repo, with names such as Manager or Context.",
    bad: "Making a god object a singleton solves the problem: one instance keeps all of its large state in a single place." },

  // --- Side effects ---
  { topic: "Command/query separation",
    good: "A method should either change state or return an answer, but not both. Queries then stay safe to call twice or reorder.",
    neutral: "Command/query separation works per method; its larger cousin CQRS applies the idea to whole read and write models.",
    bad: "In command/query separation a command returns the full updated object, and a void method doesn't follow the principle." },
  { topic: "Hidden side effects",
    good: "A method named like a query (getUser, isValid) that writes to a cache surprises callers; name side effects honestly.",
    neutral: "List a method's side effects in its doc comment, such as disk writes, network calls and changes to fields it holds.",
    bad: "Side effects in getters cause no trouble as long as they're fast; callers only ever care about the value returned." }
,
  // --- Behavioral patterns ---
  { topic: "Strategy",
    good: "Strategy puts a varying algorithm behind an interface so the caller picks one at runtime; new pricing rules become classes.",
    neutral: "Several classes implement the same method, and the context object holds one of them and calls it whenever that piece of work comes due.",
    bad: "Strategies exist to share code between related algorithms, so they should inherit the shared logic from a common base class." },
  { topic: "Strategy vs a lambda",
    good: "In Java, C# or Python a one-method strategy is often a plain function; a full interface pays off once it carries state.",
    neutral: "Lambdas are widespread now; code that passes behavior around reads shorter with them, so small strategy classes turn up less.",
    bad: "Passing a lambda in place of a strategy object breaks the pattern. Strategy requires a named class per algorithm." },
  { topic: "Observer",
    good: "Observer lets a subject notify subscribers via a callback interface without knowing them, though ordering and re-entrancy get murky.",
    neutral: "In Observer a subject keeps a list of listeners and calls each one in turn when its state changes, since they asked to hear about it.",
    bad: "Observer runs subscribers in registration order, and each finishes before the subject can change state again, so callbacks see stable state." },
  { topic: "Lapsed listener",
    good: "The subject holds strong references to its observers, so a listener nobody unsubscribes stays alive. That leak is the classic Observer bug.",
    neutral: "Listeners tend to get added in one place and removed in another, and the two calls often don't sit in the same method or even the same file.",
    bad: "Garbage collection cleans up observers on its own; once your code drops its reference, the subject lets go of it right away too." },
  // --- Creational patterns ---
  { topic: "Factory Method",
    good: "Factory Method is an overridable creation hook: subclasses pick the concrete class, and the creator codes against the product.",
    neutral: "Look for a method whose whole job is returning a new object of some product type, usually typed as an interface rather than a class.",
    bad: "Any static method that returns a new object counts as Factory Method; the GoF version adds subclassing ceremony on top of nothing new." },
  { topic: "Abstract Factory",
    good: "Abstract Factory creates families of related objects, say buttons and menus per theme, and keeps each family consistent.",
    neutral: "An abstract factory interface declares several creation methods, and each concrete factory class implements all of them.",
    bad: "Abstract Factory comes from declaring the creation method abstract in a base class, so each subclass supplies one product apiece." },
  { topic: "Builder",
    good: "Builder assembles an object step by step and validates in build(), taming telescoping constructors; the result can stay immutable.",
    neutral: "A builder typically exposes chained setter-style methods and finishes with one last call, often build(), that returns the finished object.",
    bad: "Use a builder for every class with more than two fields. A constructor with three or more parameters is a smell by itself." },
  { topic: "Singleton",
    good: "Singleton is global state with a constructor. Callers reach for it directly, which hides the dependency and lets tests leak state.",
    neutral: "A singleton class has a private constructor plus a static accessor that hands back the one instance it holds to every caller.",
    bad: "Sharing mutable state through a singleton stops thread races: with one instance, two callers can't modify it at the same moment." },
  { topic: "Singleton vs DI scope",
    good: "DI containers can register a type as one shared instance. Callers get it without knowing, and tests swap it freely.",
    neutral: "Frameworks that create objects for you usually have a notion of scope, with separate lifetimes per request and per application.",
    bad: "A container-scoped single instance and a hand-rolled Singleton are the same thing, since both hard-wire callers to one concrete class." },
  // --- Structural patterns ---
  { topic: "Decorator",
    good: "Decorator wraps an object behind the same interface and adds behavior around calls. Logging and caching then stack without subclassing.",
    neutral: "Decorators wrap another object of the same type and forward calls to it, sometimes doing a bit of extra work before or after the call.",
    bad: "Python's @decorator syntax implements GoF Decorator directly: it wraps one object at runtime behind its own interface, per instance." },
  { topic: "Adapter",
    good: "Adapter converts one interface into the one a client expects, so a third-party class plugs into your port unchanged.",
    neutral: "Keep an adapter thin: it sits between two pieces of code, and most of its methods do little beyond forwarding each call to the other side.",
    bad: "An adapter should add features the wrapped class lacks. Translating method calls alone isn't enough work to justify one." },
  { topic: "Facade",
    good: "A facade gives a simple entry point over a messy subsystem, but callers can still reach the parts underneath when they need to.",
    neutral: "Behind the scenes, a facade's handful of methods call into several other classes, and one facade often covers a whole module.",
    bad: "A facade must block direct access to the subsystem; a facade that callers can bypass defeats the encapsulation it exists for." },
  { topic: "Proxy",
    good: "Proxy shares the real subject's interface and controls access to it: lazy loading, remote calls or permission checks live in the stand-in.",
    neutral: "Callers holding a proxy can't easily tell it from the real thing, since it has the same methods and passes each call along to its target.",
    bad: "Proxy and Decorator differ in structure. A proxy never holds a reference to the real object, while a decorator always does." },
  { topic: "Composite",
    good: "Composite lets clients treat a leaf and a whole tree through one interface; drawing a group is the same call as drawing a shape.",
    neutral: "File systems and UI widget trees fit Composite well, since both are naturally shaped as nested trees of parts and wholes.",
    bad: "Composite keeps leaves and containers as separate types with no shared methods, and the client checks which one it holds." },
  // --- More behavioral patterns ---
  { topic: "Command",
    good: "Command turns a request into an object with execute() and maybe undo(), so it can be queued, logged, retried or reversed.",
    neutral: "A command object is a bundle of a receiver and the arguments it will need; somebody calls it later, perhaps much later.",
    bad: "Command objects should hold no data of their own. Each one is a stateless verb, and the invoker supplies parameters at execute time." },
  { topic: "Template Method",
    good: "Template Method fixes an algorithm's skeleton in a base class while subclasses fill in steps; being inheritance-based, it couples tightly.",
    neutral: "In Template Method the base class has a public method calling several protected ones in a set order, so the sequence sits in one place.",
    bad: "Template Method gets its steps injected at runtime, which makes it the composition-friendly alternative to Strategy." },
  { topic: "Visitor",
    good: "Visitor uses double dispatch, so new operations over a fixed hierarchy need no edits to it; a new node type touches every visitor.",
    neutral: "Give each element class an accept(visitor) method, and give the visitor one visit method for each kind of element it will need to handle.",
    bad: "Visitor makes it cheap to add new element types: existing visitors pick up new subclasses on their own through dispatch." },
  { topic: "State",
    good: "State moves mode-specific behavior into one object per state, replacing a switch repeated in each method.",
    neutral: "The State pattern and a state machine are related ideas; both talk about states and the transitions between them.",
    bad: "State and Strategy are identical in structure and intent. The sole difference lies in what you call the classes." },
  { topic: "Null Object",
    good: "A Null Object implements the interface with do-nothing behavior so callers skip null checks, yet it can hide a missing value that matters.",
    neutral: "A null object's methods exist on the interface but have empty bodies or return defaults; callers hold it like any other instance.",
    bad: "Null Object removes the cause of NullPointerExceptions, so it belongs anywhere a reference might be null in your codebase." },
  // --- Persistence and testing ---
  { topic: "Repository",
    good: "A repository is a collection-like interface over domain objects that hides the queries; leaking ORM types defeats it.",
    neutral: "Repositories usually have methods along the lines of findById, save and delete, and each one tends to serve a single entity type.",
    bad: "Model each repository as a DAO per table, giving it one method per SQL query so callers can control the exact access path." },
  { topic: "Mocks vs fakes",
    good: "A fake is a working lightweight implementation, an in-memory repo say; a mock verifies expected calls and pins down interactions.",
    neutral: "Test doubles come in several flavors with overlapping names, and the words mock, stub and fake get used loosely, not always precisely.",
    bad: "Mocks and fakes differ only in which library generates them; a fake verifies the expected calls on it just as a mock does." },
  { topic: "Over-mocking",
    good: "Mocking every collaborator ties tests to call sequences, and a harmless refactor then breaks them. Mock at boundaries, not value objects.",
    neutral: "Tests with a lot of mocks tend to have longer setup sections than tests that use real objects or simple in-memory fakes.",
    bad: "A unit test should mock every class except the one under test; anything else quietly turns it into an integration test instead." },
  // --- Paradigms and refactoring ---
  { topic: "OOP vs FP: the expression problem",
    good: "Classes make new types easy and new operations hard; pattern matching flips that, so pick by the axis that will grow.",
    neutral: "Object-oriented and functional styles organize code differently, and most modern languages let you mix the two in a single program.",
    bad: "Functional code avoids the expression problem entirely: functions over sum types extend in both directions freely." },
  { topic: "Patterns in a functional style",
    good: "Several GoF patterns shrink in FP: Strategy is a function argument, Command a closure, Visitor a match. The intent still holds.",
    neutral: "Peter Norvig argued that many design patterns become simpler or invisible in dynamic languages with first-class functions.",
    bad: "Design patterns are an OOP workaround with no meaning in functional code, and once you adopt FP the ideas simply stop applying there." },
  { topic: "Refactoring toward patterns",
    good: "Introduce a pattern when duplication or a growing conditional asks for it, in small steps under tests, rather than designing it in up front.",
    neutral: "Refactoring toward a pattern changes the structure of code without changing its behavior, the same as any other refactoring.",
    bad: "Patterns belong in the initial design. Retrofitting one later amounts to a rewrite; plan the full pattern set before writing code." }

] };
