// CloudFormation beginner-to-intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "AWS CloudFormation", turns: [
  // --- Why infrastructure as code ---
  { topic: "Infrastructure as code",
    good: "Infrastructure as code means describing your servers and databases in files you can rerun.",
    neutral: "With infrastructure as code, the cloud setup lives in text files rather than in someone's head or notes.",
    bad: "Infrastructure as code mainly means writing scripts that click through the AWS web interface for you." },
  { topic: "Why bother with IaC",
    good: "With your setup in code, you can rebuild an environment the same way twice, not from memory.",
    neutral: "Keeping infrastructure in code gives a team a written record of what it runs in AWS today.",
    bad: "Infrastructure as code typically pays off for huge companies; small projects get little out of it." },
  { topic: "What CloudFormation does",
    good: "You tell CloudFormation what resources you want, and it works out the API calls to create them.",
    neutral: "CloudFormation is an AWS service that creates and manages cloud resources, so you don't have to by hand.",
    bad: "CloudFormation needs its own EC2 instance in your account to carry out deployments." },
  { topic: "Template vs stack",
    good: "The template is the file describing what you want; a stack is the live set of resources made from it.",
    neutral: "You won't get far with CloudFormation without dealing with both templates and stacks every day.",
    bad: "A template and a stack are the same thing, and the two words get used interchangeably." },
  { topic: "YAML or JSON",
    good: "Templates can be YAML or JSON; most teams pick YAML since it's shorter and allows comments.",
    neutral: "CloudFormation templates are plain text files you open and edit in any text editor.",
    bad: "Templates have to be written in JSON, and CloudFormation rejects a YAML file when you deploy it." },
  // --- Template sections ---
  { topic: "Resources section",
    good: "Resources is the one section every template needs, and the others are optional extras.",
    neutral: "The Resources section lists the AWS things the stack should hold; it's often the longest part.",
    bad: "Parameters is the required section, and a template can deploy with zero resources listed." },
  { topic: "Parameters",
    good: "Parameters let you pass in values at deploy time, so the instance size or environment can vary.",
    neutral: "Parameters sit near the top of a template and hold values that get supplied at deploy time.",
    bad: "Parameters can hold plain text alone, so numbers and lists have to be written straight into the template." },
  { topic: "Outputs section",
    good: "Outputs show useful values after a deploy, like a bucket name or an API URL, in one place.",
    neutral: "The Outputs section sits near the end of a template, since it reports on what got built there.",
    bad: "Outputs are where you declare the resources a stack creates; without them, nothing is built." },
  { topic: "Mappings",
    good: "Mappings are small lookup tables in the template, handy for picking a value based on the region.",
    neutral: "Mappings are written as nested keys: a top-level name, then a second-level key, then the value.",
    bad: "Mappings fetch live values from other AWS accounts each time the stack gets deployed." },
  { topic: "Conditions",
    good: "Conditions let one template create a resource in some environments and skip it in others.",
    neutral: "Conditions add a bit of logic to a template, and too many of them can make it hard to read.",
    bad: "Conditions can tweak property values, yet every resource in the template gets created regardless." },
  // --- Names and references ---
  { topic: "Logical vs physical IDs",
    good: "The logical ID is the label inside the template; the physical ID is what the real resource gets.",
    neutral: "Each resource in a template has its own ID, and other parts of the template use it to point at that resource.",
    bad: "The logical ID you choose in the template becomes the exact name of the bucket or table in AWS." },
  { topic: "Ref",
    good: "Ref points at a parameter or another resource, and for most resources it gives back the name or ID.",
    neutral: "Ref shows up all over templates, since it links one piece of the template to another.",
    bad: "Ref pastes a full copy of the resource definition into the spot where you use it, like a macro." },
  { topic: "GetAtt",
    good: "GetAtt reads a specific attribute of a resource, such as a table's ARN or a queue's URL.",
    neutral: "With GetAtt you pull a value out of a resource that's defined somewhere else in the same template.",
    bad: "GetAtt works on parameters alone and has nothing to offer for reading values off a resource." },
  { topic: "Sub",
    good: "Sub builds a string by filling in placeholders, which helps with ARNs and URLs made of parts.",
    neutral: "Sub works on strings in a template and turns up wherever an ARN or URL gets built.",
    bad: "Sub can fill in parameter values, but it can't fill in anything that comes from resources in the template." },
  { topic: "Built-in values",
    good: "Built-in values give you the current region and account ID, so you don't hard-code them anywhere.",
    neutral: "A template is able to look up the region and account it's deployed into without asking for them.",
    bad: "To use the region, a template needs a parameter, and you type the region in on each deploy." },
  // --- Reuse across environments ---
  { topic: "Parameters per environment",
    good: "A parameter for the environment lets one template deploy dev, staging, and prod.",
    neutral: "Environment labels such as dev and prod often get passed into a template as parameters at deploy time.",
    bad: "Each environment needs its own copy of the template; one file serves a single environment." },
  { topic: "Sensible defaults",
    good: "Sensible parameter defaults make deploys easier, while still letting prod override what it needs.",
    neutral: "A parameter default is the value used when nobody supplies one at deploy time.",
    bad: "Once a parameter has a default, nobody can pass a different value for it at deploy time." },
  { topic: "Allowed values",
    good: "Limiting a parameter to a list of allowed values catches typos before anything deploys.",
    neutral: "Each parameter has a type, and the simplest and most frequent one is a plain string.",
    bad: "CloudFormation has no way to check parameter values, and a typo shows up when resources break later." },
  { topic: "Sharing outputs",
    good: "Outputs are a tidy way to hand values from a stack to deploy scripts or a pipeline.",
    neutral: "After a stack finishes deploying, its outputs show up along with the rest of its details.",
    bad: "Outputs stay private to whoever deployed the stack, and scripts or pipelines are locked out." },
  { topic: "One template, many environments",
    good: "Using one template for every environment keeps dev and prod alike, so bugs show up before prod.",
    neutral: "Dev, staging, and prod can each be a separate stack built from the same template.",
    bad: "Deploying one template twice in the same account fails, since the resources would clash." },
  { topic: "Hard-coded values",
    good: "Hard-coding an account ID or bucket makes a template hard to reuse; parameters or Ref fix that.",
    neutral: "Templates with fewer hard-coded values tend to be easier to move between accounts and regions.",
    bad: "Hard-coding each ID and bucket is often the better approach, since parameters make a template fragile." },
  // --- Readability and source control ---
  { topic: "Comments and readability",
    good: "A short comment in a YAML template can explain why a setting is there, not just what it is.",
    neutral: "A template is easier to work with when it's laid out neatly and resources are grouped in a sensible order.",
    bad: "Comments in a template can slow the deployment down, so it's best to strip them out first." },
  { topic: "Describing a stack",
    good: "A short description at the top of a template tells the next person what the stack is for.",
    neutral: "Give each stack a clear name; a vague one doesn't tell you what it holds.",
    bad: "The description at the top of a template decides which AWS region the stack gets created in." },
  { topic: "Stack as a unit",
    good: "A stack groups related resources, so you create, update, or delete them together as one unit.",
    neutral: "A stack holds anywhere from a couple of resources to a large number; it depends on the app's size.",
    bad: "Each resource in a template becomes its own separate stack; you manage them one at a time." },
  { topic: "Source control",
    good: "Keep templates in Git with the app code, so every infrastructure change gets reviewed and has history.",
    neutral: "Templates are text files, so they fit naturally into a Git repository next to other code.",
    bad: "Once a stack exists, the template file has served its purpose and can be thrown away." }
,
  // --- Creating a stack ---
  { topic: "Creating a stack",
    good: "To create a stack, you give CloudFormation a template and fill in any parameters it asks for.",
    neutral: "Creating a stack takes anywhere from seconds to many minutes, depending on what kind of resources are in it.",
    bad: "Creating a stack just stores the template in your account, and you still build each resource by hand." },
  { topic: "What a create does",
    good: "CloudFormation reads the template and makes the AWS calls for you; each listed resource gets created.",
    neutral: "While a create runs, the stack shows as in progress until every resource finishes or something fails.",
    bad: "One stack can hold only one type of resource, so a bucket and a Lambda function need two separate stacks." },
  { topic: "Order from references",
    good: "If one resource points at another with Ref or GetAtt, CloudFormation creates the one it points at first.",
    neutral: "References tie a template together, so names and IDs pass from one resource to the next.",
    bad: "CloudFormation builds resources in exactly the order they're written in the file, from top to bottom." },
  { topic: "Parallel creation",
    good: "Resources that don't depend on each other often get created at the same time, which speeds up a deploy.",
    neutral: "A big stack with lots of resources tends to take longer to deploy than a small stack does.",
    bad: "CloudFormation works on one resource at a time, waiting for each to finish before the next starts." },
  { topic: "DependsOn",
    good: "DependsOn makes CloudFormation wait for another resource, even when nothing references it.",
    neutral: "DependsOn sits on a resource in the template and points to one or more other resources from the same stack.",
    bad: "Every resource needs its own DependsOn entry, or CloudFormation has no way to work out the build order." },
  { topic: "When to add DependsOn",
    good: "Add DependsOn for hidden needs, like a server that needs a network route in place before it boots.",
    neutral: "Most templates need only a few DependsOn lines, and plenty of them get by with none at all.",
    bad: "Putting DependsOn on everything makes a stack deploy faster, as CloudFormation has less ordering to work out." },

  // --- Updating ---
  { topic: "Updating a stack",
    good: "To change your infrastructure, you edit the template and then run a stack update with the new version.",
    neutral: "A stack update can change the parameters, the template, or both, and it reports progress much like a create.",
    bad: "Uploading a new template to S3 updates the stacks built from it, with no other step needed." },
  { topic: "What an update touches",
    good: "On an update, CloudFormation compares old and new and changes only the resources that differ.",
    neutral: "Updates usually finish faster than the first create did, as long as most of the stack stays the same.",
    bad: "An update tears down the whole stack and rebuilds it from scratch; nothing carries over from before." },
  { topic: "Updating parameters",
    good: "You can update a stack with the same template and new parameter values, like a bigger instance size.",
    neutral: "Parameter values are saved with the stack, and the next update reuses them unless you change them.",
    bad: "Parameter values are locked at create time; changing one means deleting the stack and building it again." },
  { topic: "One update at a time",
    good: "A stack runs one operation at a time; a second update has to wait until the first one is done.",
    neutral: "As an update runs, the stack shows as in progress and its list of events keeps growing.",
    bad: "Two teammates can update the same stack at the same moment, and CloudFormation merges their changes together." },

  // --- Change sets ---
  { topic: "Change sets",
    good: "A change set shows what an update will add, change, or remove before you let it run.",
    neutral: "Change sets stay on the stack until you act, and from there you look one over, run it, or throw it away.",
    bad: "Making a change set applies the update right away, rather than waiting for you to run it." },
  { topic: "Reading a change set",
    good: "Check a change set for any resource marked for replacement, since that's the line worth a second look.",
    neutral: "Each row in a change set shows one resource and the kind of action CloudFormation plans for it.",
    bad: "A change set tends to list new resources only, not the ones the update will modify or remove." },
  { topic: "When to use change sets",
    good: "Change sets earn their keep on production stacks, where a surprise replacement could hurt real users.",
    neutral: "Change sets are optional; a stack update also runs directly without making one first.",
    bad: "A change set tests your update against live traffic and blocks anything that would cause downtime for users." },

  // --- Replacement ---
  { topic: "Replacement updates",
    good: "Some property changes can't happen in place, so CloudFormation builds a new resource and removes the old one.",
    neutral: "Each resource property has its own update behavior, and the AWS reference pages for that resource spell it out.",
    bad: "Changing a property always updates the existing resource in place, never swapping it for a new one." },
  { topic: "Replacing a database",
    good: "Replacing a database gives you a new, empty one, so check for replacement before changing RDS settings.",
    neutral: "Databases deserve extra care in a stack, because they hold data the rest of the app depends on.",
    bad: "When an RDS instance gets replaced, CloudFormation copies the old data across to the new one for you." },
  { topic: "Renaming a resource",
    good: "Changing a logical ID makes CloudFormation see a new resource: it creates one and deletes the old.",
    neutral: "Logical IDs sit under Resources as keys, and clear ones make a template much easier to follow.",
    bad: "Changing a logical ID is purely cosmetic, and the same resource underneath simply carries the new label from then on." },

  // --- When things fail ---
  { topic: "Rollback on create",
    good: "When a resource fails during a create, CloudFormation rolls back and removes what it had built so far.",
    neutral: "A rollback shows up in the stack's events as a run of delete steps, usually right after the failed step.",
    bad: "A failed create leaves the resources that did succeed running, and you finish the rest by hand." },
  { topic: "Rollback on update",
    good: "When an update fails, CloudFormation rolls back to the last working version instead of stopping halfway.",
    neutral: "Rollbacks may take a while on larger stacks, with each change undone in turn until the old state is back.",
    bad: "A failed update leaves the stack half-changed, with some resources new and some old, until you fix it." },
  { topic: "Stack events",
    good: "The stack's events list each step with a status and a reason, and that's where to look when a deploy fails.",
    neutral: "Each stack event carries a timestamp, and the newest events show at the top of the list.",
    bad: "Stack events show what succeeded; to see why a deploy failed, you have to dig through CloudWatch Logs instead." },
  { topic: "Finding the first error",
    good: "Look for the earliest failure in the events; later errors tend to be rollback noise.",
    neutral: "A failed deploy can leave quite a few red lines in the events, each one with its own short message.",
    bad: "The newest error at the top of the events is the real cause, and the earlier ones don't matter." },
  { topic: "A failed first create",
    good: "If a brand new stack fails and rolls back, you delete it and create it again rather than updating it.",
    neutral: "A new stack that rolls back still sits in the stack list, with no resources left inside it at all.",
    bad: "After a failed first create, you fix the template and run an update on that same stack." },

  // --- Deleting ---
  { topic: "Deleting a stack",
    good: "Deleting a stack deletes the resources it created, unless a resource is set to be kept.",
    neutral: "A stack delete starts from the AWS web interface, the command line, or a pipeline step.",
    bad: "Deleting a stack removes CloudFormation's record of it, while the actual resources stay running." },
  { topic: "Delete order",
    good: "On delete, CloudFormation works in reverse and removes things that depend on others before what they need.",
    neutral: "A stack delete takes about as long as the create did, depending on what kinds of resources are in it.",
    bad: "Before deleting a stack you must remove each resource yourself, or the stack delete fails." },

  // --- How you deploy ---
  { topic: "Pipeline vs console",
    good: "Deploying from a pipeline makes every change reviewed and repeatable, not a one-off click in the console.",
    neutral: "The console is handy for watching a deploy and reading the events while a stack updates.",
    bad: "A pipeline generally pays off for big teams; a solo developer should deploy each change from the console." },
  { topic: "Small frequent changes",
    good: "Small, frequent updates are easier to review and roll back than one big change.",
    neutral: "Some teams update their stacks many times a day, and others deploy about once a week or less.",
    bad: "Saving changes up for one big update is usually wiser, because fewer deploys means fewer chances to break things." }
,
  // --- Keeping data when a stack goes away ---
  { topic: "DeletionPolicy Retain",
    good: "With DeletionPolicy set to Retain, deleting the stack leaves that database running instead of removing it.",
    neutral: "DeletionPolicy goes on one resource in the template, and it is not a setting for the whole stack at once.",
    bad: "DeletionPolicy Retain stops CloudFormation from changing that resource during normal stack updates." },
  { topic: "Retained resources",
    good: "A retained resource keeps running after the stack is gone, so it still costs money until you clean it up.",
    neutral: "Once the stack is deleted, a retained resource just sits in the account as an ordinary AWS resource.",
    bad: "Rather than keeping them forever, AWS deletes retained resources on its own a few days after the stack is gone." },
  { topic: "DeletionPolicy Snapshot",
    good: "With Snapshot on an RDS database, CloudFormation takes a final backup and then deletes the database.",
    neutral: "Besides Retain, DeletionPolicy also offers Snapshot, which applies to resources that are able to make backups.",
    bad: "The Snapshot policy keeps the database running and also saves a backup copy when the stack is deleted." },
  { topic: "Choosing a policy",
    good: "Put Retain or Snapshot on anything holding data you'd hate to lose, like databases and important buckets.",
    neutral: "Decide on a DeletionPolicy for each stateful resource when you add it, since it's easy to forget later.",
    bad: "A database doesn't need a DeletionPolicy, because RDS keeps its own backups after the stack is deleted." },
  { topic: "Termination protection",
    good: "Termination protection blocks deleting the whole stack until someone turns it off, a guard against slips.",
    neutral: "Termination protection can be switched on or off for a stack at any time, not only when it's created.",
    bad: "With termination protection on, nobody can update the stack either, and the resources are frozen as they are." },
  { topic: "Protection vs policy",
    good: "Termination protection guards the stack as a whole; DeletionPolicy decides what happens to one resource.",
    neutral: "Turning on termination protection for production stacks is a sensible habit right after creating them.",
    bad: "Termination protection also keeps each resource's data if the stack ends up being deleted anyway." },
  { topic: "Non-empty S3 buckets",
    good: "Deleting a stack can fail on an S3 bucket that still has objects in it, so you'd empty the bucket first.",
    neutral: "S3 buckets show up in lots of stacks, holding files, logs or build output for the rest of the app.",
    bad: "When a stack is deleted, CloudFormation empties its S3 buckets for you and then removes them right away." },

  // --- Drift and manual changes ---
  { topic: "Manual changes",
    good: "If someone edits a resource by hand, the template no longer matches what's really running in AWS.",
    neutral: "Resources a stack creates are still regular AWS resources, and you can open them in the web interface.",
    bad: "CloudFormation copies changes made by hand in the AWS web interface back into the stack's template." },
  { topic: "What drift is",
    good: "Drift is the gap between a resource's real settings and what the stack's template says they should be.",
    neutral: "CloudFormation reports drift for a stack as a whole and also for each resource inside that stack.",
    bad: "Drift is when the template in your repo differs from the deployed one; it isn't about live resources." },
  { topic: "Drift detection",
    good: "Drift detection lists resources changed outside CloudFormation and shows which settings differ.",
    neutral: "A drift check doesn't run on its own; you start it on a stack and read the results once it's done.",
    bad: "Drift detection runs nonstop in the background and puts back any manual change the moment it happens." },
  { topic: "Fixing drift",
    good: "To fix drift, undo the hand edit, or put that change into the template and deploy it the normal way.",
    neutral: "Once a drift report turns up hand edits, start a chat with whoever has been changing those resources.",
    bad: "Once drift is found, the fix is to delete the stack and create it again from the template." },
  { topic: "Console clicking",
    good: "Make changes through the template rather than by clicking, because the next deploy may undo hand edits.",
    neutral: "The console is handy for looking at a stack's resources, events and outputs while you're learning.",
    bad: "Quick fixes in the console are the better habit, and templates are for setting things up at the start." },

  // --- Permissions ---
  { topic: "Who needs permissions",
    good: "CloudFormation acts with your permissions or a service role, so it needs rights for every resource type it creates.",
    neutral: "IAM is the AWS service that decides who is allowed to create, change or delete which resources in an account.",
    bad: "CloudFormation has full admin rights in every account, and the person running it needs no IAM rights." },
  { topic: "Service role",
    good: "A service role is an IAM role the stack uses, so deploys run with its rights instead of the deployer's.",
    neutral: "A service role for CloudFormation is just an IAM role that you create and then hand to the stack to use.",
    bad: "Service roles matter for stacks in another AWS account, but within one account they do nothing." },
  { topic: "IAM acknowledgment",
    good: "If a template creates IAM roles or policies, you have to confirm that before the deploy will go ahead.",
    neutral: "Templates for Lambda functions often include an IAM role, since the function needs one to run with.",
    bad: "The IAM acknowledgment is a warning and nothing more, and the deploy goes ahead if you skip past it." },
  { topic: "Least privilege",
    good: "Roles in a template should grant only the actions and resources the app really needs, nothing more.",
    neutral: "IAM roles and policies don't need a separate tool; a template can define them next to the resources that use them.",
    bad: "Start template roles with admin access, and tighten them later if a security review ever asks for it." },

  // --- Secrets ---
  { topic: "Hard-coded secrets",
    good: "Don't put passwords or API keys straight into a template; anyone who can read it can read them too.",
    neutral: "Templates often need a secret somewhere, for example a database password or a key for an outside API.",
    bad: "Writing a password into the template is OK as long as the repo is private, since only your team sees it." },
  { topic: "Secrets Manager",
    good: "Keep the secret in Secrets Manager or Parameter Store and have the template point to it there.",
    neutral: "Secrets Manager stores secret values, while Parameter Store holds both plain settings and secrets.",
    bad: "A template can't read from Secrets Manager, so secrets have to be typed in by hand on each deploy." },
  { topic: "NoEcho",
    good: "Marking a parameter NoEcho hides its value in the console and API output, but it doesn't encrypt it.",
    neutral: "NoEcho is a property you set on a parameter, and it gets used mostly for values like passwords or keys.",
    bad: "With NoEcho on a parameter the value is fully protected, so it's a good place to keep secrets long term." },
  { topic: "Secrets in outputs",
    good: "Keep secrets out of stack outputs, since outputs show in plain text to anyone who can view the stack.",
    neutral: "Outputs share values like a bucket name or a URL, and they appear on the stack's page in the console.",
    bad: "Outputs are hidden from other users, so putting a password in one is a tidy way to share it with the team." },

  // --- Tags and importing ---
  { topic: "Tagging",
    good: "Tags on a stack get passed down to most of its resources, which helps with tracking cost and ownership.",
    neutral: "A tag is a key and value pair on a resource, for instance the team that owns it or its environment.",
    bad: "Tags change how a resource behaves, so adding one to a running resource will restart or replace it." },
  { topic: "Tag habits",
    good: "Agree on a few tags across the team, such as owner and environment, and use them in every template.",
    neutral: "Tag keys and values are free-form text, so a team can choose whatever names suit the way it works.",
    bad: "Tags are useful for billing reports and little else; searching for resources by tag gets you nowhere." },
  { topic: "Importing resources",
    good: "You can import an existing resource into a stack, so something built by hand comes under CloudFormation.",
    neutral: "Importing works on one stack at a time, so you choose which existing resources go into that particular stack.",
    bad: "To bring a hand-built resource under CloudFormation, you must delete it and let the stack recreate it." },
  { topic: "Import needs a template",
    good: "Before importing, add the resource to the template so it matches how the real thing is set up today.",
    neutral: "Import fits well for a resource that someone set up by hand before the team started using templates for it.",
    bad: "During an import, CloudFormation resets the real resource's settings to its own defaults." },
  { topic: "Retain before import",
    good: "Put Retain on a resource you plan to import; then a later mistake can't delete something you rely on.",
    neutral: "Import works with many resource types, so S3 buckets and DynamoDB tables can both be brought into a stack.",
    bad: "An imported resource is left alone by a stack delete, since it came from outside the stack." }
,
  // --- Splitting stacks ---
  { topic: "Splitting stacks",
    good: "Splitting a big app into a few stacks keeps each one smaller, quicker to update, and easier to reason about.",
    neutral: "An AWS account isn't limited to one stack, and CloudFormation tracks each stack separately from the rest of them.",
    bad: "One giant stack for the whole app is the best plan, and separate stacks have no way to share values." },
  { topic: "Where to split",
    good: "A handy way to split is by pace of change: busy parts in one stack, slow-moving parts in another.",
    neutral: "There's no single right way to divide stacks; it's a design choice with several reasonable answers.",
    bad: "Each AWS resource belongs in its own stack rather than sharing, which is how CloudFormation is meant to be used." },
  { topic: "Nested stacks",
    good: "A nested stack is one that another stack creates, so a template piece can be reused as a building block.",
    neutral: "Nested stacks show up in the stack list too, listed right alongside the parent stack that created them.",
    bad: "A nested stack is a separate project you deploy by hand, and the parent template has no say in its lifecycle." },
  { topic: "Updating nested stacks",
    good: "With nested stacks you update through the parent, which passes the changes down to each child stack.",
    neutral: "The parent template points at each child template's file, while the files themselves usually sit in S3.",
    bad: "Nested stacks can't take parameters from the parent, and each child template must hard-code its own values." },
  // --- Exports and imports ---
  { topic: "Exports and imports",
    good: "An output can be exported under a name, and another stack in the same region can import it by that name.",
    neutral: "Export names must be unique within one account and region, so a naming pattern helps keep them apart.",
    bad: "A stack in another region or account can import an export by name, with zero setup needed on either side of the link." },
  { topic: "Exports in use",
    good: "Once another stack imports a value, you can't change or remove that export until the import goes away.",
    neutral: "You can list which stacks import a given export, and checking that list before any change is a good habit to keep.",
    bad: "Changing an exported value instantly updates each importing stack, with nothing else for anyone to deploy." },
  { topic: "Import link",
    good: "Exports tie stacks tightly together; passing values as parameters keeps them looser but takes more wiring.",
    neutral: "An imported value comes from an output in another stack, one that its owning stack chose to export by name.",
    bad: "Importing copies the value over once, and after that the two stacks have nothing to do with each other." },
  // --- SAM and CDK ---
  { topic: "SAM",
    good: "SAM is a shorter way to write serverless apps; it expands into regular CloudFormation when you deploy.",
    neutral: "SAM templates focus on serverless pieces such as Lambda functions, API endpoints, and DynamoDB tables.",
    bad: "SAM replaces CloudFormation outright, and SAM apps run on their own service with no stacks involved." },
  { topic: "SAM templates",
    good: "The SAM command-line tool can build and deploy your app, and it can also run functions locally for testing.",
    neutral: "A SAM template looks much the same as a CloudFormation template, plus a few extra shortcut resource types.",
    bad: "Plain CloudFormation resources are off-limits in a SAM template; it takes serverless types alone." },
  { topic: "CDK",
    good: "CDK lets you write infrastructure in a programming language and turns that code into a CloudFormation template.",
    neutral: "CDK works with several languages, TypeScript and Python among them, so a team can pick the one it already knows.",
    bad: "CDK talks to AWS directly and skips CloudFormation, leaving no stack to look at after a deploy." },
  { topic: "CDK output",
    good: "You can still read the template CDK generates, which helps when a deploy doesn't do what you expected.",
    neutral: "CDK code is regular code, so it can live in the same repo as the app and get tested with the same tools.",
    bad: "CDK code has to be a flat list of resources instead of real code with loops, same as a template." },
  // --- Checking templates ---
  { topic: "Linting templates",
    good: "A template linter catches typos, wrong property names, and bad values before you ever deploy.",
    neutral: "Template linters can run right in an editor as you type, or as a step in a build pipeline before anything ships.",
    bad: "Template mistakes usually show up only at deploy time, and waiting for a failure is the one way to find them." },
  { topic: "Validating templates",
    good: "Validating a template checks its basic structure, but it won't tell you a property value is wrong for a service.",
    neutral: "CloudFormation can validate a template before you create a stack, which gives fast feedback on syntax.",
    bad: "A template that passes validation is certain to deploy, since validation checks each property against AWS." },
  // --- Lambda code ---
  { topic: "Packaging Lambda code",
    good: "For Lambda, a package step uploads your zip to S3 and rewrites the template to point at it, all in one go.",
    neutral: "Lambda code has to sit somewhere CloudFormation can reach, and an S3 bucket is the usual spot for it.",
    bad: "CloudFormation reads Lambda code straight off your laptop each time the function runs, with no upload needed." },
  { topic: "Shipping new code",
    good: "If the code's location in the template never changes, CloudFormation may not notice a new version.",
    neutral: "Deploy tools usually give the uploaded code file a name based on a hash of its contents, so new code gets a new name.",
    bad: "Inline Lambda code in the template is the best approach, however large the function gets." },
  // --- Stateful and stateless ---
  { topic: "Stateful vs stateless",
    good: "Keeping databases and buckets in their own stack lets you rebuild app stacks without touching data.",
    neutral: "Databases and buckets are stateful resources that hold data; stateless ones don't keep anything.",
    bad: "Stateful and stateless resources behave identically in CloudFormation, and mixing them in one stack has no downside." },
  { topic: "Stateful stacks",
    good: "Stateful stacks change less often and deserve extra care, such as a retain policy and a close look at every change.",
    neutral: "Stateless pieces like Lambda functions and API routes can be rebuilt from the template at any time.",
    bad: "Stateful resources can't go in a stack at all; databases and buckets have to be created by hand." },
  // --- Environments and naming ---
  { topic: "Environments",
    good: "Putting dev, staging, and prod in separate AWS accounts keeps a dev mistake from touching prod.",
    neutral: "Each environment usually gets its own stack, often with the environment's name in the stack name.",
    bad: "The best way to roll out a change is to edit the prod stack directly and get to dev and staging later." },
  { topic: "Promoting changes",
    good: "Moving the same template from dev to staging to prod means prod only gets changes already tried.",
    neutral: "Prod stacks often get bigger settings than dev, with larger instances or longer backup retention.",
    bad: "Once a change works in dev, it can skip staging and go straight to prod without any real risk." },
  { topic: "Generated names",
    good: "If you leave a resource's name out, CloudFormation generates a unique one, so stacks don't clash.",
    neutral: "Generated names usually include the stack name and the logical ID, plus a random suffix tacked on the end of it.",
    bad: "Every resource must have a hard-coded name, or CloudFormation will refuse to create the stack at all." },
  { topic: "Fixed names",
    good: "Hard-coding a name can block a replacement, since the new resource can't take a name that's still in use.",
    neutral: "S3 bucket names have to be unique across all of AWS, not just within your own account or region.",
    bad: "Two stacks can each create a bucket with the same fixed name, and each stack quietly keeps its own copy." },
  // --- Comparisons and extras ---
  { topic: "Other IaC tools",
    good: "CloudFormation is AWS-only and tracks state for you; other infrastructure-as-code tools can span several clouds.",
    neutral: "Other infrastructure-as-code tools exist too, and they share the same idea of describing resources in files.",
    bad: "CloudFormation manages resources in other clouds just as easily as in AWS, with no extra setup or plugins required." },
  { topic: "Templates vs clicking",
    good: "Clicking around the console is fine for exploring, but a template gives you a repeatable, reviewable record.",
    neutral: "The console and CloudFormation can both create the same kinds of resources, and they end up as the same AWS objects.",
    bad: "Resources built by clicking in the console can't work alongside resources that a stack created." },
  { topic: "Custom resources",
    good: "A custom resource lets a template call your own Lambda function for a step CloudFormation can't do itself.",
    neutral: "Custom resources are handy but add code to maintain, so it's worth checking for a built-in option first.",
    bad: "Custom resources skip IAM permissions entirely, because CloudFormation runs them with full admin rights." },
  { topic: "Beginner mistakes",
    good: "A frequent early mistake is copying a template to a new project and forgetting to change its hard-coded names.",
    neutral: "Starting from a small working template and growing it piece by piece makes any mistakes much easier to track down.",
    bad: "Writing the whole template in one go before ever deploying it is the quickest way to get a working stack." }
] };
