// CloudFormation intermediate prep — 100 turns.
// Each turn: a topic plus three related statements.
//   good    — accurate and useful; what a fluent practitioner would say
//   neutral — true but shallow or beside the point
//   bad     — a plausible-sounding misconception
var QUIZ = { title: "AWS CloudFormation", turns: [
  // --- Template anatomy ---
  { topic: "Template sections",
    good: "Resources is the only required section; Parameters, Mappings, Conditions, and Outputs are optional layers around it.",
    neutral: "Templates can be written in either JSON or YAML, and most teams today pick YAML because it's shorter and allows comments.",
    bad: "Every template must declare Parameters, Resources, and Outputs, or it fails validation before anything is deployed." },
  { topic: "AWSTemplateFormatVersion",
    good: "AWSTemplateFormatVersion has only ever had one valid value, 2010-09-09, and it doesn't gate new features.",
    neutral: "The format version usually sits at the top of the template, just above the Description, by common convention.",
    bad: "Bump AWSTemplateFormatVersion to a recent date to unlock the newest resource types; old versions know only the originals." },
  { topic: "Logical vs physical IDs",
    good: "The logical ID is the name in your template; the physical ID is the real resource name or ID that CloudFormation creates in your account.",
    neutral: "Logical IDs have to be alphanumeric, and they're shown in the console's Resources tab next to each resource.",
    bad: "The logical ID is always used as the actual resource name in AWS, so it must be globally unique across accounts." },
  { topic: "Ref",
    good: "What Ref returns depends on type: a bucket name for S3, a queue URL for SQS, a topic ARN for SNS.",
    neutral: "Ref is one of the most common intrinsic functions and shows up in nearly every template, usually as !Ref in YAML.",
    bad: "Ref always returns the resource's ARN, whatever the type, since ARNs are the universal AWS identifier." },
  { topic: "Fn::GetAtt",
    good: "Fn::GetAtt reads attributes Ref doesn't give you, like a bucket's Arn or an RDS instance's Endpoint.Address.",
    neutral: "In YAML, GetAtt has the short form !GetAtt, written with a dot between the logical ID and the attribute.",
    bad: "Fn::GetAtt can read back any property you set, such as a bucket's VersioningConfiguration, since properties are attributes." },
  { topic: "Fn::Sub",
    good: "Fn::Sub interpolates ${Param}, ${Resource.Attr}, and pseudo parameters into one string, which reads far better than a long Fn::Join.",
    neutral: "Fn::Sub works with strings and is listed among the intrinsic functions in the CloudFormation template reference.",
    bad: "Fn::Sub can only substitute parameters; resource attributes still need to be stitched in with Fn::Join." },
  { topic: "Pseudo parameters",
    good: "Pseudo parameters like AWS::Region, AWS::AccountId, and AWS::StackName keep one template portable.",
    neutral: "Pseudo parameters start with the AWS:: prefix, and the docs have a page that lists every one of them.",
    bad: "You have to declare AWS::Region in the Parameters section before you can Ref it, just like any other input value to the template." },
  { topic: "Parameters",
    good: "Parameters make a template reusable, and AllowedValues or AllowedPattern reject bad input before anything is created.",
    neutral: "Parameters can have a Description, which the console shows as helper text next to the input box when you launch a stack.",
    bad: "Parameter constraints are only checked after resources are created, and a violation then triggers a rollback." },
  { topic: "AWS-specific parameter types",
    good: "Types like AWS::EC2::KeyPair::KeyName or AWS::EC2::VPC::Id are validated against your account and give a dropdown in the console.",
    neutral: "Parameters have a Type property, and String and Number are the types people reach for most often.",
    bad: "AWS-specific parameter types are only descriptive labels for the console; any string at all is accepted." },
  { topic: "SSM parameter types",
    good: "An AWS::SSM::Parameter::Value<String> parameter resolves at deploy time; the public AMI paths fetch the latest Amazon Linux.",
    neutral: "Systems Manager Parameter Store holds configuration values and is used by many AWS services and tools.",
    bad: "SSM-typed parameters re-resolve continuously in the background, so the running stack picks up a new value without needing any update." },
  { topic: "Intrinsics in Parameters",
    good: "Parameters can't use intrinsic functions, so a default can't be computed from another value.",
    neutral: "Parameters can have default values, which are filled in for you in the console when you create or update the stack.",
    bad: "A parameter default can Ref another resource in the same stack, which is handy for wiring things together." },
  { topic: "Mappings",
    good: "Mappings are static lookup tables read with Fn::FindInMap, such as an instance size per environment keyed by a parameter value.",
    neutral: "Mappings are declared at the top level of the template, typically placed somewhere near the Parameters section.",
    bad: "Mappings can be filled in at deploy time from resource attributes, like a lookup table built on the fly." },
  { topic: "Conditions",
    good: "Conditions use parameters, mappings, and other conditions, never resource attributes, to gate resources or outputs.",
    neutral: "Conditions use functions like Fn::Equals and Fn::Not, and they're declared in their own Conditions section.",
    bad: "A condition can check whether another resource was created successfully, so you can make later resources depend on that outcome." },
  { topic: "Fn::If and AWS::NoValue",
    good: "Fn::If with AWS::NoValue lets you drop a property entirely under a condition, as if it were never written.",
    neutral: "Fn::If takes a condition name and two values, and it's one of the condition functions covered together in the documentation.",
    bad: "AWS::NoValue sets the property to an empty string, which most AWS services then just treat as unset." },
  { topic: "Fn::GetAZs and Fn::Select",
    good: "Fn::Select over Fn::GetAZs picks availability zones by index, so subnets avoid hard-coded AZ names.",
    neutral: "Each region has several availability zones, and the exact number varies from one region to another.",
    bad: "Fn::GetAZs returns availability zones from every region at once, so you filter the list down to your region yourself." },
  { topic: "Outputs",
    good: "Outputs surface endpoints or ARNs after deployment, and can be exported for other stacks to read with Fn::ImportValue.",
    neutral: "Outputs appear in a tab on the stack's page in the console once the deployment has finished successfully.",
    bad: "Outputs are only for display in the console; other stacks and external tools have no way to read them." },
  { topic: "Template size limits",
    good: "A template body passed inline has a small size cap, so big templates go to S3 and are passed by URL.",
    neutral: "Templates can get long for big applications, and teams often split them into several files to keep them readable.",
    bad: "There's no template size limit as long as the YAML is valid, since CloudFormation streams the template in." },
  { topic: "Resources per stack",
    good: "A stack can hold up to 500 resources; large systems hit that and get split into nested or separate stacks.",
    neutral: "A stack contains resources, which are listed on the Resources tab along with their status.",
    bad: "Stacks have no resource limit, so splitting them up into several stacks is purely a matter of team style and taste." },

  // --- Dependencies ---
  { topic: "Implicit dependencies",
    good: "Ref and GetAtt create implicit dependencies, so CloudFormation orders creation and builds independent resources in parallel.",
    neutral: "Some resources depend on others, and CloudFormation shows each resource's status in the Events tab.",
    bad: "CloudFormation creates resources strictly top to bottom, in the exact order they're written in the template." },
  { topic: "DependsOn",
    good: "DependsOn covers dependencies CloudFormation can't infer, like an instance needing the gateway attached first.",
    neutral: "DependsOn can take a single logical ID or a list of them, and it's set at the same level as Type and Properties.",
    bad: "You should add DependsOn to every resource that uses Ref, or CloudFormation may end up creating them out of order." },
  { topic: "Circular dependencies",
    good: "Two security groups referencing each other inline form a cycle; moving rules into SecurityGroupIngress resources breaks it.",
    neutral: "Circular dependency errors can show up at validation or deploy time, and the error message names the resources involved.",
    bad: "Circular dependencies are fine, because CloudFormation creates both resources first and patches the references in afterward." },
  { topic: "Deletion order",
    good: "On stack delete, CloudFormation removes resources in reverse dependency order, so dependents go before what they depend on.",
    neutral: "Deleting a stack deletes its resources, and the stack shows DELETE_IN_PROGRESS in the console while it runs.",
    bad: "Stack deletion removes everything at once in parallel, regardless of dependencies, to finish faster." },

  // --- Updates & change sets ---
  { topic: "Change sets",
    good: "A change set previews adds, modifies, and removals, including replacements, before you execute.",
    neutral: "Change sets have names, and you can create several for one stack and look at each of them in the console before deciding.",
    bad: "A change set guarantees the update will succeed once executed, since every change has already been validated." },
  { topic: "Replacement in change sets",
    good: "Replacement: True means a new physical resource gets created and the old one deleted, which for a database can mean data loss.",
    neutral: "Change sets list the resources that change, along with the action planned for each one of them.",
    bad: "Replacement: Conditional means the change will simply be skipped if it would cause any problems." },
  { topic: "Update behaviors",
    good: "Each property's docs say whether a change causes no interruption, some interruption, or replacement; check that first.",
    neutral: "Some updates take longer than others, depending on the resource types involved and how many resources are being changed.",
    bad: "Updates always modify resources in place; replacement only happens if you delete the resource from the template." },
  { topic: "Custom physical names",
    good: "Setting a fixed name like BucketName blocks any update that requires replacement, since the new resource can't reuse that name.",
    neutral: "Many resource types let you set an explicit physical name through a property such as BucketName or TableName.",
    bad: "Hard-coding physical names is always best practice, because CloudFormation can then swap the old and new resources more cleanly." },
  { topic: "Renaming logical IDs",
    good: "Changing a logical ID reads as delete-plus-create to CloudFormation, unless you use stack refactoring to rename the resource.",
    neutral: "Logical IDs can be any alphanumeric name you like, and most teams pick descriptive ones that match the resource's purpose in the template.",
    bad: "Renaming a logical ID only changes a label in the template, so the underlying physical resource stays untouched on update." },
  { topic: "Empty updates",
    good: "An update with no real changes fails with 'No updates are to be performed', which is why `aws cloudformation deploy` has --no-fail-on-empty-changeset.",
    neutral: "Not every deploy actually changes something, and pipelines often re-run the same template many times across a normal week.",
    bad: "Re-running an unchanged template forces CloudFormation to recreate every resource, which is how teams refresh drifted stacks." },
  { topic: "UsePreviousValue",
    good: "On update, UsePreviousValue keeps an existing parameter value without passing it again, handy for secrets you keep out of scripts.",
    neutral: "Parameter values can change from one update to the next, and you supply them in the console, the CLI or a parameters file.",
    bad: "Leaving a parameter out of an update call always resets it to the template's Default value, so you must pass every parameter each time." },
  { topic: "Lambda code updates",
    good: "If a Lambda's S3Key and S3ObjectVersion don't change, CloudFormation sees no diff, so new code uploaded to the same key won't deploy.",
    neutral: "Lambda function code can come from an S3 bucket and key, or be written inline in the template for small functions, and both forms are common.",
    bad: "CloudFormation watches the S3 object and redeploys the Lambda automatically whenever the file under that key changes." },
  { topic: "EC2 user data",
    good: "Changing UserData on an EBS-backed instance makes CloudFormation stop and restart it, but by default the script doesn't rerun after first boot.",
    neutral: "UserData is passed base64-encoded, usually via Fn::Base64 wrapped around Fn::Sub so you can drop stack values into the script.",
    bad: "Editing UserData in the template reruns the script on the live instance right away, with no stop or restart needed." },
  { topic: "AMI changes",
    good: "Changing ImageId on an AWS::EC2::Instance replaces the instance outright, so anything kept only on its local disks is gone.",
    neutral: "AMIs are region-specific, which is why templates often look up image IDs through a Mappings section or an SSM parameter.",
    bad: "Changing ImageId reimages the existing instance in place, keeping its instance ID, private IP address and attached volumes intact." },

  // --- Failure & rollback ---
  { topic: "Automatic rollback",
    good: "If a create or update fails, CloudFormation rolls back to the last known good state by default, undoing what it did.",
    neutral: "Deployments sometimes fail partway through, and the console shows each resource's progress and status as the stack goes.",
    bad: "A failed update leaves the stack half-applied, so you have to track down and clean up the partial changes manually every time." },
  { topic: "ROLLBACK_COMPLETE",
    good: "A stack that fails its very first create lands in ROLLBACK_COMPLETE, which can't be updated; you delete it and create it again.",
    neutral: "Stack statuses like ROLLBACK_COMPLETE are shown in the console's stack list and returned by the DescribeStacks API call.",
    bad: "ROLLBACK_COMPLETE means the stack rolled back cleanly and is healthy, so you can just push an update with your fixes." },
  { topic: "UPDATE_ROLLBACK_FAILED",
    good: "When a rollback itself fails, fix the cause and run ContinueUpdateRollback, optionally skipping the stuck resources.",
    neutral: "Rollbacks can occasionally fail too, and the stack then shows a distinct status in the console until someone deals with it.",
    bad: "UPDATE_ROLLBACK_FAILED is permanent; the only way out is opening a support case and having AWS delete the stack for you." },
  { topic: "Reading stack events",
    good: "Scroll to the first FAILED event; the later 'Resource creation cancelled' events are just fallout from that one failure.",
    neutral: "Stack events show a timestamp, logical ID, status and reason for each step, and you can view them in the console or the CLI.",
    bad: "The most recent event at the top of the events list is always the root cause, since CloudFormation stops right after it." },
  { topic: "Debugging failures",
    good: "Disabling rollback, or choosing to preserve successfully provisioned resources, lets you inspect what failed instead of losing it.",
    neutral: "Debugging failed stacks takes patience, and it helps to read the error messages carefully before changing the template.",
    bad: "You can't turn rollback off for a stack, so the only way to debug a failure is to read the event messages afterward." },
  { topic: "Rollback triggers",
    good: "Rollback triggers watch CloudWatch alarms during an update and a monitoring window after it, rolling back if one fires.",
    neutral: "CloudWatch alarms monitor metrics and change state when a threshold is crossed, and they're used widely across AWS services.",
    bad: "By default, rollback triggers roll back any stack whose EC2 instances go over 80% CPU, even if you never configured any alarm yourself." },
  { topic: "Timeouts and signals",
    good: "A CreationPolicy makes CloudFormation wait for cfn-signal success signals; too few before the timeout and it fails.",
    neutral: "Some resources take a while to become ready after they're created, and boot scripts can take several minutes to finish.",
    bad: "CloudFormation marks an EC2 instance complete only once its application is fully running, so no signaling setup is needed." },

  // --- Protecting resources ---
  { topic: "DeletionPolicy",
    good: "DeletionPolicy: Retain keeps the resource when it's removed from the template or the stack is deleted; Snapshot takes a final backup.",
    neutral: "DeletionPolicy is a resource attribute, set at the same level as Type and Properties rather than inside the properties block.",
    bad: "DeletionPolicy: Retain stops anyone from deleting the resource, even from the console, the CLI or SDK calls made outside of CloudFormation." },
  { topic: "Default DeletionPolicy",
    good: "Most resources default to Delete, but RDS DB clusters and DB instances without a DBClusterIdentifier default to Snapshot.",
    neutral: "Default behavior varies by resource type, and the documentation for the DeletionPolicy attribute lists the exceptions.",
    bad: "Every resource defaults to Retain, so deleting a stack never deletes data unless you explicitly set the policy to Delete." },
  { topic: "UpdateReplacePolicy",
    good: "UpdateReplacePolicy decides what happens to the old physical resource when an update replaces it, separate from DeletionPolicy.",
    neutral: "UpdateReplacePolicy accepts values like Retain, Snapshot or Delete, and it's set alongside DeletionPolicy and the other resource attributes.",
    bad: "UpdateReplacePolicy controls whether an update is allowed to replace the resource at all, blocking replacements when set." },
  { topic: "Retained resources",
    good: "Retained resources are orphaned, keep costing money, and can block re-creating a stack that reuses the same names.",
    neutral: "Retained resources stay in your account after the stack goes away, and you can still find them in each service's own console.",
    bad: "Retained resources stay tracked by CloudFormation and are cleaned up automatically about 30 days after the stack itself is deleted." },
  { topic: "Non-empty buckets",
    good: "Deleting a stack fails on a non-empty S3 bucket; you empty it first, retain it, or use a custom resource to clear it out.",
    neutral: "S3 buckets hold objects, and a bucket defined in a stack is created and named like any other resource in the template.",
    bad: "CloudFormation empties an S3 bucket automatically when deleting the stack, including old object versions if versioning is on." },
  { topic: "Termination protection",
    good: "Termination protection blocks stack deletion until someone explicitly turns it off, a cheap guard for production stacks.",
    neutral: "Termination protection is a stack-level setting you can turn on when creating a stack or later from the stack's actions menu.",
    bad: "Termination protection also blocks stack updates, so a protected stack is effectively frozen until you switch it off again." },
  { topic: "Stack policies",
    good: "A stack policy can deny updates to specific resources, like a production database, unless it's overridden for one update.",
    neutral: "Stack policies are written in JSON, using Effect, Action, Principal and Resource elements much like other AWS policy documents.",
    bad: "A stack policy is just an IAM policy attached to the stack, so it controls which users are allowed to call CloudFormation." },

  // --- IAM & permissions ---
  { topic: "Capabilities",
    good: "You acknowledge CAPABILITY_IAM, CAPABILITY_NAMED_IAM or CAPABILITY_AUTO_EXPAND when a template creates IAM resources or uses macros.",
    neutral: "Capabilities are passed with the --capabilities flag on the CLI, or by ticking the acknowledgment boxes in the console.",
    bad: "Capabilities grant CloudFormation the IAM permissions it needs to create resources, so they replace a service role." },
  { topic: "Service roles",
    good: "With a service role, CloudFormation uses that role's permissions for stack operations, so deployers don't need broad rights.",
    neutral: "IAM roles have trust policies that say who may assume them, and roles are used all over AWS for delegating access.",
    bad: "CloudFormation always runs with full admin permissions behind the scenes, so IAM never limits what a stack can create." },
  { topic: "iam:PassRole",
    good: "Using a service role requires iam:PassRole on it; that's what stops people from escalating through a more powerful role.",
    neutral: "PassRole is an IAM action that shows up in a lot of policies, and it's listed in the IAM documentation with the other actions.",
    bad: "PassRole is only needed when attaching EC2 instance profiles, never for handing a service role to CloudFormation." },

  // --- Secrets ---
  { topic: "NoEcho",
    good: "NoEcho masks a parameter in the console and API, but not values you put in Outputs or Metadata, so it isn't secret storage.",
    neutral: "NoEcho is a property you set on a parameter, and it's commonly used on parameters for things like passwords or API keys.",
    bad: "NoEcho encrypts the parameter value with an AWS-managed KMS key, so it's safe to pass it straight through to an Outputs value later on." },
  { topic: "Dynamic references",
    good: "Dynamic references like {{resolve:secretsmanager:...}} fetch secrets at deploy time, so they never sit in the template.",
    neutral: "Secrets Manager stores credentials such as database passwords and API keys, and it's a commonly used service alongside CloudFormation.",
    bad: "Dynamic references copy the secret's resolved value back into the stored template on deploy, so the stack can replay it later." },
  { topic: "Secrets and drift",
    good: "Rotating a secret doesn't update resources that resolved it at deploy time; they keep the old value until the stack is updated again.",
    neutral: "Secrets Manager secrets can be rotated on a schedule, and the rotation settings are configured on the secret itself.",
    bad: "Every resource that references a secret through a dynamic reference picks up the new value the instant it rotates, since CloudFormation subscribes to it." },

  // --- Cross-stack ---
  { topic: "Exports and ImportValue",
    good: "One stack exports an output and other stacks read it with Fn::ImportValue, which is a simple way to share values like a VPC ID or subnet IDs.",
    neutral: "Exports are declared in the Outputs section of a template, each with an Export name, and they show up in the console.",
    bad: "Fn::ImportValue can read any output from any stack by name, whether or not the producing stack exported it." },
  { topic: "Export lock-in",
    good: "You can't change or delete an export while another stack imports it, which makes exports a tight coupling.",
    neutral: "Exports are listed on their own page in the CloudFormation console, along with the stacks that currently import them.",
    bad: "Changing an exported value automatically triggers an update on every importing stack, so consumers always stay in sync with the producer." },
  { topic: "Export scope",
    good: "Exports are scoped to a single account and region, and each export name must be unique within that account and region.",
    neutral: "Many teams use exports to share values between stacks, and the CloudFormation docs include examples of the pattern for VPCs.",
    bad: "Fn::ImportValue works across accounts and regions as long as the export names match exactly in each one." },
  { topic: "SSM instead of exports",
    good: "Writing shared values to SSM Parameter Store instead of exports loosens coupling, since consumers read the value without locking the producer stack.",
    neutral: "SSM Parameter Store is a key-value store that's part of Systems Manager, and it supports plain and secure strings.",
    bad: "SSM parameters can't be created as resources in CloudFormation templates, so exports are the only way to share values." },
  { topic: "Nested stacks",
    good: "Nested stacks use AWS::CloudFormation::Stack to compose templates, and they're updated and rolled back together through the parent.",
    neutral: "Nested stack templates are usually stored in S3, and the parent references each one by its TemplateURL.",
    bad: "Nested stacks deploy independently of their parent, so a child stack's failure never causes the parent stack to roll back or fail at all." },
  { topic: "Nested vs cross-stack",
    good: "Nested stacks suit one lifecycle split into parts; cross-stack refs suit separately owned stacks that change on their own schedule.",
    neutral: "Both nested stacks and cross-stack references are common in larger CloudFormation setups, and teams often use a mix of the two across projects.",
    bad: "Nested stacks and cross-stack references are fully interchangeable, so the choice between them doesn't affect updates or ownership." },
  { topic: "StackSets",
    good: "StackSets deploy one template to many accounts and regions, which is common for org-wide guardrails like logging roles or Config rules.",
    neutral: "A StackSet is made up of stack instances, and each instance points to a stack in a particular account and region.",
    bad: "StackSets just copy a template into many regions of the same account; they can't reach other accounts." },
  { topic: "Service-managed StackSets",
    good: "With service-managed permissions via Organizations, StackSets can auto-deploy to new accounts that join a target OU.",
    neutral: "AWS Organizations groups accounts into organizational units, and OUs can be nested several levels deep to reflect a company's structure.",
    bad: "StackSets can't integrate with AWS Organizations, so the admin and execution roles in each target account must always be created by hand." },

  // --- EC2 bootstrapping ---
  { topic: "cfn-init",
    good: "cfn-init reads AWS::CloudFormation::Init metadata to install packages, write files, and start services declaratively.",
    neutral: "cfn-init is one of the CloudFormation helper scripts, and it comes preinstalled on Amazon Linux AMIs along with the others in the same package.",
    bad: "cfn-init runs automatically on every instance at boot, whether or not user data calls it, as an AMI service." },
  { topic: "cfn-signal",
    good: "cfn-signal reports success or failure back to a CreationPolicy or wait condition, so the stack only finishes once the instance is really ready.",
    neutral: "cfn-signal is a helper script that runs on the instance, and it's usually invoked near the end of the user data script.",
    bad: "cfn-signal sends instance health metrics to CloudWatch so that CloudFormation can decide whether to keep or replace the instance." },
  { topic: "cfn-hup",
    good: "cfn-hup watches for changes to the resource's metadata and reruns hooks, so config updates apply in place.",
    neutral: "cfn-hup runs as a daemon on the instance, and its settings live in a config file under the /etc/cfn directory.",
    bad: "cfn-hup restarts the instance whenever the stack is updated, so the new configuration is picked up from a clean boot every time." },
  { topic: "Wait conditions",
    good: "A WaitCondition with a handle pauses the stack until something external signals; CreationPolicy is now preferred for EC2 and ASGs.",
    neutral: "Wait conditions have a Timeout property, and the wait condition and its handle are both declared as resources.",
    bad: "A WaitCondition simply sleeps for the number of seconds set in its Timeout, and then the stack continues on." },
  { topic: "Auto Scaling rolling updates",
    good: "An AutoScalingRollingUpdate policy replaces instances in batches when the launch template changes, keeping capacity up.",
    neutral: "Auto Scaling groups manage a fleet of EC2 instances, and they're one of the most commonly deployed resources in CloudFormation templates.",
    bad: "Changing the launch template automatically refreshes every instance in the group, even without any UpdatePolicy set on it." },
  { topic: "Replacing updates",
    good: "AutoScalingReplacingUpdate builds a whole new Auto Scaling group and switches over only once it's healthy, which is easy to roll back.",
    neutral: "There's more than one UpdatePolicy option for Auto Scaling groups, and the docs describe each one in turn.",
    bad: "AutoScalingReplacingUpdate terminates all the old instances first and then launches the new ones, so there's always a short gap in capacity." },

  // --- Extensibility ---
  { topic: "Custom resources",
    good: "A custom resource invokes a Lambda function or SNS topic on create, update, and delete, so you can handle anything CloudFormation doesn't support.",
    neutral: "Custom resources have a ServiceToken property, and their type is either AWS::CloudFormation::CustomResource or Custom::Name.",
    bad: "Custom resources are only meant for integrating third-party SaaS products, and they can't be used to manage or configure AWS services." },
  { topic: "Custom resource responses",
    good: "The handler must PUT a response to the presigned URL, or the stack hangs until the timeout, which defaults to an hour.",
    neutral: "Custom resource handlers receive an event with a RequestType field, along with other fields like the stack ID and the logical resource ID.",
    bad: "CloudFormation treats a custom resource as successful as soon as the Lambda function returns without an error." },
  { topic: "Custom resource deletes",
    good: "Handlers must handle Delete gracefully, and returning a new PhysicalResourceId on update triggers a Delete of the old one.",
    neutral: "Custom resources go through the same create, update, and delete lifecycle events as the built-in resource types do in a stack.",
    bad: "Custom resources never receive Delete events from CloudFormation, so any cleanup of what the handler created has to be done by hand afterward." },
  { topic: "Macros and transforms",
    good: "Macros are Lambda-backed transforms that rewrite the template before deploy; you list them under Transform and need CAPABILITY_AUTO_EXPAND.",
    neutral: "Transforms usually appear near the top of a template, and a template can list more than one of them in order.",
    bad: "Macros run after deployment finishes, tidying up, tagging, and renaming the resources that the stack created." },
  { topic: "SAM",
    good: "SAM is a transform, AWS::Serverless-2016-10-31, that expands short types like AWS::Serverless::Function into CloudFormation.",
    neutral: "SAM has its own CLI with commands for building, testing locally, and deploying, and it's widely used for serverless projects on AWS.",
    bad: "SAM is a separate deployment engine that keeps its own state file, so SAM applications don't use CloudFormation stacks at all." },
  { topic: "Language extensions",
    good: "The AWS::LanguageExtensions transform adds functions like Fn::ForEach and Fn::Length, which cut down on repetitive template code.",
    neutral: "Language extensions are optional, and templates that don't declare them work the same way they always have.",
    bad: "Plain CloudFormation has always had native loops and length functions built in, so no transform is needed to repeat resources in a template." },
  { topic: "Registry",
    good: "The registry holds public third-party and private resource types, so you can manage things like Datadog monitors as stack resources.",
    neutral: "The CloudFormation registry is visible in the console, where you can browse resource types, modules, and hooks and filter them by publisher.",
    bad: "CloudFormation can only manage the resource types that AWS itself built in, with no way to register more of them." },
  { topic: "Hooks",
    good: "Hooks run your checks before resources are created or updated and can fail or warn: proactive guardrails, not after-the-fact audits.",
    neutral: "Hooks can be configured per account and region, and they're managed through the CloudFormation registry.",
    bad: "Hooks are just SNS notifications that CloudFormation sends out after a stack finishes deploying or rolling back." },

  // --- Drift & import ---
  { topic: "Drift detection",
    good: "Drift detection compares live resources to what the template expects, so you can find console edits made outside it.",
    neutral: "Drift results can be viewed per resource in the console, with a status for each one and the date it was last checked.",
    bad: "Drift detection automatically reverts manual changes back to the template's values, so console edits don't stick for long." },
  { topic: "Drift coverage",
    good: "Drift detection only covers supported resource types, and only properties you set explicitly; defaults aren't compared.",
    neutral: "Drift detection is run on demand from the console or CLI, for a whole stack or for individual resources within it.",
    bad: "Drift detection compares every property of every resource in the stack, including service defaults you never set yourself." },
  { topic: "Resource import",
    good: "Import adopts existing resources into a stack; each one needs a DeletionPolicy attribute in the template.",
    neutral: "Import uses a change set of type IMPORT, which you create and then execute much like any other change set in the console.",
    bad: "Import recreates each resource from the template and then deletes the original, so expect a brief outage during the switch." },
  { topic: "IaC generator",
    good: "The IaC generator scans existing resources into a template, a fast start for getting click-ops infra into code.",
    neutral: "The IaC generator lives in the CloudFormation console, and AWS's documentation walks through how to start a scan.",
    bad: "The IaC generator reads your Terraform state files and converts them into an equivalent CloudFormation template automatically." },

  // --- Tooling & workflow ---
  { topic: "validate-template",
    good: "validate-template only checks syntax and structure; bad property values still fail at deploy, so pair it with cfn-lint.",
    neutral: "validate-template is an AWS CLI command that you can point at a local file or a template already uploaded to S3.",
    bad: "If validate-template passes, the stack is guaranteed to deploy, since it checks every property value against the live service APIs." },
  { topic: "cfn-lint",
    good: "cfn-lint checks templates against the resource specs, catching wrong property names, bad types and invalid values early.",
    neutral: "cfn-lint is an open source project maintained on GitHub, and it is commonly installed with pip or run as an editor plugin.",
    bad: "cfn-lint deploys a temporary test copy of the stack in your account to find errors, then tears it down when it's done." },
  { topic: "CloudFormation Guard",
    good: "cfn-guard lets you write policy-as-code rules, like 'buckets must be encrypted', and check templates against them in CI.",
    neutral: "Guard has its own domain-specific rule syntax, and its rule files are typically kept alongside templates in a repo.",
    bad: "cfn-guard is a managed WAF rule set that protects CloudFormation's API endpoints from malicious requests." },
  { topic: "package and deploy",
    good: "`package` uploads local artifacts to S3 and rewrites the paths; `deploy` then creates and executes a change set in one step.",
    neutral: "Both `package` and `deploy` are subcommands of `aws cloudformation` in the AWS CLI, and they're often used together in scripts.",
    bad: "`aws cloudformation deploy` skips change sets entirely and applies changes directly, which is why it's faster." },
  { topic: "CDK",
    good: "The CDK synthesizes CloudFormation templates, so stacks, rollbacks and drift still behave the CloudFormation way.",
    neutral: "The CDK supports several programming languages, including TypeScript, Python, Java, C# and Go, with TypeScript popular.",
    bad: "The CDK calls AWS service APIs directly from your machine and bypasses CloudFormation for speed, keeping its own state." },
  { topic: "CDK bootstrap",
    good: "cdk bootstrap creates a CDKToolkit stack with an asset bucket, an ECR repository and deploy roles per account and region.",
    neutral: "Bootstrapping is a setup step you run before your first CDK deployment, covered early in the getting-started guide.",
    bad: "cdk bootstrap installs the CDK CLI and its language dependencies on your local machine so synth can run." },
  { topic: "Git sync",
    good: "Git sync watches a repository branch and deploys the stack whenever the template or deployment file changes there.",
    neutral: "Many teams keep their templates in Git alongside application code, and providers like GitHub and GitLab are common choices.",
    bad: "CloudFormation keeps every template in its own internal Git repository, which you clone to see a stack's history." },
  { topic: "Stack notifications",
    good: "Stack events can go to SNS or EventBridge, so a pipeline or chat channel can react to failures without polling.",
    neutral: "Notifications are optional, and you can choose whether to configure them when you create or update a stack.",
    bad: "The only way to know a stack operation finished is to poll describe-stacks, because CloudFormation emits no events of its own." },
  { topic: "Stack tags",
    good: "Tags set on a stack propagate to resources that support tagging, an easy way to get consistent cost-allocation tags everywhere.",
    neutral: "Tags are key-value pairs, and you can add them in the console's stack options page or pass them with --tags.",
    bad: "Stack tags apply only to the stack object itself and never reach the resources it creates inside." },
  { topic: "Region scope",
    good: "A stack lives in one region; deploying the same template elsewhere means another stack there, or a StackSet.",
    neutral: "AWS has many regions, and the CloudFormation console shows a region selector at the top of the page like other services.",
    bad: "A single stack can create resources in any region, as long as you set a Region property on each resource that needs it." },

  // --- Practices & comparisons ---
  { topic: "Pricing",
    good: "CloudFormation is free for AWS resource types; you pay for the resources, plus a small per-operation fee for some third-party types.",
    neutral: "AWS publishes CloudFormation pricing on its pricing page, and the details are worth reviewing before a large rollout to production.",
    bad: "CloudFormation bills per stack per hour, whether or not anything is deploying, so lots of idle stacks quietly get expensive over a month." },
  { topic: "vs Terraform",
    good: "Unlike Terraform, CloudFormation keeps state on the AWS side, so there's no state file or locking to manage.",
    neutral: "Terraform and CloudFormation are both infrastructure-as-code tools, and plenty of organizations use one or both.",
    bad: "CloudFormation writes a local state file that you must commit to Git after every deploy, or the next update will fail." },
  { topic: "Manual changes",
    good: "Editing stack-managed resources in the console causes drift that a later update can silently overwrite or fail on.",
    neutral: "The console is handy for quick looks at a resource's current settings, and many engineers use it day to day.",
    bad: "Console changes to stack-managed resources are automatically written back into the stack's template, so nothing is lost." },
  { topic: "Stateful vs stateless stacks",
    good: "Teams often put databases and other stateful resources in their own stack with Retain, apart from busy app stacks.",
    neutral: "Teams organize stacks in different ways, depending on their size, structure and how they like to divide ownership.",
    bad: "Keeping the database in the same stack as the app is always safest, because they roll back together as one unit." },
  { topic: "Generated names",
    good: "Generated names let you deploy one template several times in an account, and replacement updates still work.",
    neutral: "Generated names include the stack name, the logical ID and a random suffix, so they can look long and a bit cryptic at first.",
    bad: "Generated physical names change on every stack update, so you can never rely on them from other systems." },
  { topic: "Environment parity",
    good: "One template with parameters or mappings for dev, staging and prod keeps environments consistent and promotion predictable.",
    neutral: "Most teams run more than one environment, often named something like dev, staging and prod, each in its own account or region.",
    bad: "Each environment should get its own hand-edited copy of the template, so prod tweaks never risk leaking into dev or staging." },
  { topic: "Stack timeouts",
    good: "A creation timeout makes a create that hangs, say on a missing signal, fail and roll back instead of waiting indefinitely.",
    neutral: "Timeouts are measured in minutes, and you can set one in the stack options when creating a stack.",
    bad: "Stack timeouts cancel the deploy but leave half-created resources in place, with no rollback afterward." },
  { topic: "Coverage gaps",
    good: "New features sometimes reach CloudFormation after the API; custom resources or the registry fill the gap meanwhile.",
    neutral: "AWS releases new features frequently, and announcements are posted on the What's New page and the AWS blogs.",
    bad: "Every new AWS feature is supported in CloudFormation on launch day, since service teams must ship both together." },
  { topic: "Cloud Control API",
    good: "Cloud Control API exposes resource type schemas via generic CRUD calls, which Terraform's awscc provider builds on.",
    neutral: "Cloud Control is an AWS API with its own documentation and CLI commands, and it's part of the wider CloudFormation family.",
    bad: "Cloud Control API is a console dashboard for viewing the status of all your CloudFormation stacks across every region at once." },
  { topic: "Deploying with pipelines",
    good: "A typical pipeline lints, creates a change set, pauses for review on risky changes like replacements, then executes it.",
    neutral: "CI/CD pipelines automate deployment, and services like CodePipeline, GitHub Actions and Jenkins are all commonly used for that.",
    bad: "Pipelines should call update-stack directly, because change sets just add delay without any real benefit." },
  { topic: "Long-running deletes",
    good: "Deletes can stall on things like ENIs still attached to Lambda functions in a VPC, so knowing the usual culprits saves time.",
    neutral: "Some deletes take longer than creates, and the stack's events tab shows progress while you wait.",
    bad: "Stack deletions are instant, because CloudFormation only removes the stack record and cleans up resources later." },
  { topic: "Least privilege templates",
    good: "Templates can define least-privilege IAM roles beside the resources using them, scoping policies with Ref and Fn::Sub.",
    neutral: "IAM roles can be defined directly in templates, and the AWS::IAM::Role resource type is one of the most commonly used.",
    bad: "Templates should grant AdministratorAccess to every role, because scoping policies to specific ARNs breaks resource replacement." }
] };
