// flourish.js — Flourish
//
// Every stock line the game says more than once lives here as a table of
// forty alternatives, so no message wears a groove. pick() rolls a fresh
// line through Rando (seeded runs reproduce); stable() keys the choice to
// an id so re-rendered UI text doesn't jitter between frames.
// Templates use {name}-style slots filled from the vars argument.

const Flourish = (function () {
    const TABLES = {
        // vision card title — short, it sits beside the ◆
        'doom-title': [
            'A doom gathers',
            'Something is coming',
            'A shadow on the loom',
            'The bones have spoken',
            'A thread pulls taut',
            'Trouble on the wind',
            'The candle saw it',
            'A dark thing ripens',
            'It approaches',
            'A knot in the days ahead',
            'The tea leaves agree',
            'Something stirs',
            'A storm in the weave',
            'The future clears its throat',
            'A doom takes shape',
            'It is written, faintly',
            'The vale is owed a grief',
            'A bad day is booked',
            'Something wicked pencils itself in',
            'The loom shudders',
            'A crow with a purpose',
            'The bones fell wrong',
            'A cloud with intentions',
            'Misfortune takes an interest',
            'The days bend toward it',
            'A debt comes due',
            'The candle flinched',
            'Something sharpens',
            'A doom on approach',
            'The weave is snagged',
            'Ill news, still traveling',
            'A grief in the post',
            'The future leans close',
            'Something climbs the calendar',
            'A dark appointment',
            'The signs align, unkindly',
            'A trouble finds its feet',
            'The vale is marked',
            'Something old wakes hungry',
            'A doom clears its schedule'
        ],
        // vision list when empty — chosen per day, not per render
        'quiet-candle': [
            'The candle burns steady. Nothing gathers — for now.',
            'The bones lie quiet. Enjoy it while it lasts.',
            'No visions tonight. The future is holding its tongue.',
            'The loom is smooth. Suspiciously smooth.',
            'Nothing stirs in the leaves. You check twice.',
            'The candle stands tall and says nothing.',
            'A quiet night. You distrust it professionally.',
            'The future, for once, minds its own business.',
            'No dooms on the books. The ledger feels light.',
            'The vale sleeps and nothing watches it. Probably.',
            'The bones have nothing to add.',
            'Still water in the scrying bowl. Just your face.',
            'The wind carries nothing but weather.',
            'Tonight the dark is only dark.',
            'The threads run straight. None of them snag.',
            'Not a whisper. You almost miss the whispers.',
            'The candle flame sits like a well-behaved child.',
            'Nothing gathers. The hens may relax.',
            'The days ahead look plain as porridge.',
            'No omens. The turnip at the shrine remains just a turnip.',
            'The loom hums its ordinary hum.',
            'Peace, of the temporary kind.',
            'The future keeps its curtains drawn, politely.',
            'The tea leaves spell nothing. Not even rude words.',
            'All quiet. You sharpen your worry anyway.',
            'The night has no teeth in it. Tonight.',
            'The stars go about their business without comment.',
            'Nothing coming that the bones will admit to.',
            'The vale breathes easy. You breathe carefully.',
            'The candle burns down without a single flinch.',
            'No shapes in the smoke worth naming.',
            'The weave lies flat and honest.',
            'A rare blank page in the book of trouble.',
            'The dark keeps to its corners.',
            'Nothing to warn about. Nobody believes you either way.',
            'The scrying bowl shows sky, and only sky.',
            'The bones sleep. Let them.',
            'The road ahead looks stubbornly ordinary.',
            'No doom tonight. The goat is pleased.',
            'Quiet. The good kind, so far.'
        ],
        // riddle: when, still distant
        'riddle-day': [
            'soon, or late',
            'before the moon forgets',
            'when it pleases',
            'in its own sour time',
            'not tomorrow, probably',
            'when the days have thinned',
            'after some sleeps, before others',
            'the bones count on their own fingers',
            'a handful of days, loosely held',
            'when the candle has burned lower',
            'past the next washing day, perhaps',
            'in the fat part of the week, or the lean',
            'when the moon has turned its face',
            'later than fear, sooner than hope',
            'the leaves will not be pinned down',
            'somewhere down the row of days',
            'when the road dust settles twice',
            'give it time; it is giving you some',
            'not yet, which is a kind of mercy',
            'in the space between two market days',
            'when the year leans that way',
            'the thread is long but not endless',
            'a while — the bones are smug about it',
            'when the crows agree on it',
            'after the bread goes stale, before the well runs dry',
            'in the future, unhelpfully',
            'when the weave brings the thread round',
            'some days off; count your blessings meanwhile',
            'the smoke drifts, and will not say',
            'when the hills have had a few more mornings',
            'past several suppers yet',
            'when it has finished sharpening',
            'in the slow ripening of bad fruit',
            'the calendar keeps that page folded',
            'not before the next rain, says the damp in your knee',
            'when the vale has almost stopped worrying',
            'a stretch of days, width unknown',
            'when the loom decides the row is done',
            'later — the sort of later that arrives',
            'in time. All things are, and this one too'
        ],
        // riddle: when, imminent
        'riddle-day-near': [
            'soon — the candle bends toward it',
            'very soon, the bones say',
            'days you could count on one hand',
            'close enough to smell the smoke of it',
            'the thread is nearly wound',
            'before the bread you baked goes hard',
            'soon; the crows are already gathering',
            'a breath or two of days away',
            'near — the leaves are certain and unkind',
            'it is lacing up its boots',
            'the candle gutters when you ask',
            'soon enough to start counting',
            'within the week, and the week is thin',
            'the bones rattle: shortly, shortly',
            'close — the smoke points at the door',
            'nearly here; the loom is almost out of slack',
            'a few sunrises, no more',
            'soon, and sooner if you dawdle',
            'the dark of it already touches the vale',
            'it has left wherever dooms wait',
            'before the moon changes its mind',
            'the scrying bowl trembles: days, not weeks',
            'near enough that the dogs feel it',
            'soon — even the turnip looks worried',
            'the last quiet days are spending themselves',
            'it is on the road, and the road is short',
            'within days; the bones refuse to be more polite',
            'close now, close as a held breath',
            'the candle leans like a tree in wind',
            'soon: the word tastes of iron',
            'few days stand between it and the vale',
            'nearly upon you, says every leaf in the cup',
            'the thread has almost reached the knot',
            'it comes quickly, as bad news does',
            'soon — sleep fast, there is little time for it',
            'the week will not end quietly',
            'days, and small ones at that',
            'the omen is already packing lighter',
            'almost here; the loom pulls tight',
            'soon. The bones do not repeat themselves. Soon'
        ],
        // riddle: who
        'riddle-victim': [
            'a face you know',
            'someone who has poured you a drink',
            'a name you would grieve',
            'a name you would miss',
            'someone who waves when you pass',
            'a voice you would know in the dark',
            'one of the vale\'s own',
            'somebody\'s favorite somebody',
            'a chair that would sit empty',
            'someone who owes you nothing and smiles anyway',
            'a hand you have shaken',
            'one who has knocked at your door',
            'a face from the festival',
            'someone the dogs run to greet',
            'a regular at somebody\'s table',
            'one whose laugh carries up the hill',
            'a person the bread is baked for',
            'someone you have warned before, or should have',
            'a soul the chapel bell would toll for',
            'one who remembers your name on bad days',
            'somebody the vale would walk slowly behind',
            'a garden that would go to weeds',
            'someone whose boots you would know by the door',
            'one the winter would be colder without',
            'a face in every harvest you remember',
            'someone who argues with you and means well',
            'a name the well-gossip is fond of',
            'one who has lent and never asked back',
            'somebody\'s reason to hurry home',
            'a whistler you would notice gone quiet',
            'one who saves you the good seat',
            'a soul with unfinished kindnesses',
            'someone the children mimic fondly',
            'a name stitched into the vale like a hem',
            'one whose window glows on your late walks',
            'somebody who believed you first',
            'a face the shrine candles know',
            'one more thread the vale cannot spare',
            'someone who calls the goat by name',
            'a person, which is the whole trouble'
        ],
        // riddle: how hard
        'riddle-magnitude': [
            'it may be small, or it may be great',
            'the bones will not say how hard',
            'its weight is still deciding itself',
            'somewhere between a bruise and a burial',
            'the leaves blur when you ask its size',
            'heavy or light — the smoke keeps its counsel',
            'enough to notice; perhaps enough to mourn',
            'the loom hides the thickness of the thread',
            'a slap or a landslide, the candle cannot tell',
            'its shadow will not hold still to be measured',
            'the scrying bowl shows only that it is coming, not how big its boots are',
            'you cannot yet tell if it whispers or roars',
            'the bones shrug, which is worse than an answer',
            'its heft is wrapped in fog',
            'maybe a stumble, maybe a fall from height',
            'the omen will not step on the scales',
            'small print or headline — the leaves won\'t say',
            'a pebble or a millstone; the dark grins either way',
            'the weave hides whether it is thread or rope',
            'it has a weight, and the weight has a secret',
            'the candle flame gives no measure, only warning',
            'somewhere on the long road between mishap and ruin',
            'the future mumbles when asked for numbers',
            'a splinter or a spear — too soon to say',
            'its size sleeps; you would rather not wake it to check',
            'the bones offer odds, not amounts',
            'enough. How much is enough remains open',
            'the smoke makes it look both smaller and larger than it is',
            'it could pass like weather or stay like winter',
            'the leaves show teeth but not how many',
            'a cough or a plague-wind; the bowl clouds over',
            'its true heft is written on the folded side of the page',
            'the loom will not let you feel the tension of that thread',
            'light as rumor, heavy as debt — one of the two',
            'the dark is coy about the tonnage',
            'you sense edges, not the whole of it',
            'the omen travels cloaked; its shoulders could be any width',
            'a scratch, a scar, or a story told for years',
            'the bones know and are being difficult',
            'hard to say. Possibly just hard'
        ],
        // doom broke against the ward, nobody was told
        'averted-quiet': [
            'It breaks and is gone. No one else will ever know what almost happened.',
            'It shatters on the ward. The vale sleeps through its own salvation.',
            'It comes, meets the ward, and dies unwitnessed. You alone keep the count.',
            'The doom spends itself on your quiet work. Nobody claps. Nobody knows.',
            'It breaks like a wave on a wall nobody saw you build.',
            'Averted. The vale will call it an ordinary Tuesday. Let them.',
            'It gutters out against the ward. The morning arrives, oblivious and whole.',
            'The danger passes through your preparations and comes out nothing.',
            'It hits the ward and unravels. One more secret for the chest.',
            'Silently met, silently broken. The bill for this will never be sent.',
            'The doom arrives to find the door already barred. It leaves no note.',
            'It breaks. Somewhere a family sleeps on, rich in what they didn\'t lose.',
            'Your ward holds. History will record that nothing happened here.',
            'The night swallows it whole. Only you heard it snap.',
            'It falls apart on the threshold you strengthened. The threshold is modest about it.',
            'Doom, meet ward. Ward wins. Crowd of witnesses: one.',
            'It is turned aside so cleanly the vale never feels the wind of it.',
            'The candle watched it break. The candle tells no one either.',
            'Another disaster filed quietly under "never happened".',
            'It presses, finds no purchase, and is gone by first light.',
            'The ward drinks the blow. You pour yourself something similar.',
            'What almost happened is now a story only you could tell, and won\'t.',
            'It breaks against your work like frost against a warm door.',
            'Unseen it came, unseen it failed. The ledger of the vale stays clean.',
            'The doom finds the vale already answered. It has no second question.',
            'Nothing happens, which took a great deal of doing.',
            'It dies at the ward-line. The rooster takes credit for the dawn.',
            'The vale is saved and yawns through it.',
            'Your preparations meet it in the dark and win the argument.',
            'It comes apart quietly, like a knot finally worked loose.',
            'The morning finds everything standing and no one curious why.',
            'Struck, held, broken. Applause: the wind, briefly.',
            'The doom checks the ward, finds it sound, and has nowhere else to be.',
            'It is over before anyone knew it had begun. That was the whole plan.',
            'One more grief that will never learn the vale\'s name.',
            'The ward takes the whole of it. You take the walk home.',
            'It breaks, and the silence afterward is your only witness.',
            'The vale owes you a debt it will never know to pay.',
            'Somewhere between midnight and dawn, nothing happened, hard.',
            'The doom meets your quiet work and becomes quieter still.'
        ],
        // doom broke against the ward, with the village watching
        'averted-warned': [
            'The vale holds its breath — and holds. They SAW it break against your ward. They will not forget.',
            'It breaks in full view of everyone you warned. The silence after is the best sound you know.',
            'The doom lands where you said, when you said — and dies on the ward they helped raise. Eyes turn to you.',
            'They watched it come, because you told them to. They watched it fail, because you made it.',
            'It shatters before the whole vale. Somewhere in the crowd, someone starts believing.',
            'The ward holds and the village sees it hold. That is worth more than the ward.',
            'Exactly as foretold, exactly as prevented. They will tell this one at the Wan Hart.',
            'It breaks. A cheer goes up. Someone claps you on the back hard enough to count as injury.',
            'The vigil pays. The doom dies in front of witnesses, which is how reputations are born.',
            'They saw the dark come up the road, and they saw your work turn it. Nobody is laughing at the bones tonight.',
            'It fails in public, spectacularly. You could not have staged it better, and you half wish you had.',
            'The doom breaks against the ward, and the crowd breaks into noise.',
            'You said it would come. It came. You said it could be stopped. Watch.',
            'The whole vale sees the wave break on the wall. The wall was your idea.',
            'It dies at the door with the village watching through every window.',
            'Foreseen, forestalled, and witnessed. The trifecta.',
            'The vigil-keepers see it with their own eyes: the doom, and the doom failing.',
            'It breaks, and the vale exhales as one animal.',
            'They kept the watch grudgingly. They will retell it gladly.',
            'The doom arrives on schedule and is refused entry. The crowd approves.',
            'Every doubter present watches the ward do exactly what you promised.',
            'It comes apart before them like a trick explained — except it was real, and it worked.',
            'The village sees the blow land and the vale not bruise. Word will travel.',
            'A doom dies in daylight, on time, as advertised.',
            'They saw. Whatever else happens, they saw.',
            'The ward holds. The children will play at being augur for a week.',
            'It breaks against the preparations, and belief quietly changes sides.',
            'You called the storm and built the roof. The vale stood under it and stayed dry.',
            'The doom fails its one appointment in front of everyone.',
            'Witnessed: one catastrophe, cancelled. The vale files out like a congregation.',
            'It hits the ward and stops. The story of it will not stop for years.',
            'The vigil ends in the best way: loudly, with nothing lost.',
            'They watched the dark try the door you barred. The door won.',
            'Seen coming, seen stopped. The bones take a bow on your behalf.',
            'The vale watched its own doom break, and knows whose hands broke it.',
            'It is turned before the crowd. Old men nod as if they always trusted you. They didn\'t.',
            'The warning cost you dear. Tonight it pays out in full view.',
            'A public doom, publicly broken. The Wan Hart pours one on the house.',
            'They held the vigil and the vigil held. Trust is built of nights like this.',
            'The doom breaks. The vale saw everything. That was the point.'
        ],
        // warned, but it landed anyway
        'hit-warned': [
            'It lands despite the vigil. Grim faces — but you were right, and they know it.',
            'The ward was not enough. The warning was still true. Both facts sit heavy.',
            'It comes as foretold and hits as feared. Nobody blames the teller. Almost nobody.',
            'The vigil could not hold it. The vale is hurt, and believes you completely.',
            'You were right. It is very cold comfort, and it is still comfort.',
            'It breaks through. Being believed does not stop the counting of the cost.',
            'The doom keeps its appointment despite everything laid against it.',
            'It lands. The village looks at the wreckage, then at you, and nods bitterly: you said.',
            'The preparations blunt nothing enough. The prophecy, at least, was sound.',
            'Foretold and unstoppable both. The vale learns the difference tonight.',
            'It hits. In the quiet after, someone says: at least we knew. It helps less than hoped.',
            'The ward gives what it had. The doom had more.',
            'You warned them, they watched, it came anyway. The watching was not wasted — only outmatched.',
            'It lands hard. Your word stands harder. Small trade, tonight.',
            'The vigil bought courage, not safety. Courage is what remains.',
            'True vision, insufficient wall. The vale keeps both lessons.',
            'It arrives exactly as promised, which no one thanks you for.',
            'The doom out-weighs the ward. The truth of the warning survives the wreck.',
            'They believed, they prepared, they lost anyway. They do not stop believing.',
            'It falls as foreseen. Grim arithmetic: right about the storm, short on the roof.',
            'The blow lands through every preparation. The vale grieves informed.',
            'No one says you lied. The damage says you underbuilt.',
            'It comes through the ward like rain through old thatch. You had named the day, at least.',
            'The vigil watched it happen. Watching, this time, was all the vigil could do.',
            'Struck, despite everything. The warning stands; the building doesn\'t.',
            'The doom honors the prophecy and ignores the defense.',
            'It lands. The vale, bruised, moves closer to the augur rather than away.',
            'Not enough ward in the world tonight. The foretelling, though, was exact.',
            'They knew what was coming. It came anyway. Knowing changes the grief, not the size of it.',
            'The doom takes its toll despite the toll already paid in vigilance.',
            'You cannot say they weren\'t warned. You wish that sentence tasted better.',
            'It breaks the ward and keeps coming. The vale holds the line the wall could not.',
            'Right about everything but the weight of it.',
            'The vigil fails upward: the loss is real, and so, now, is your word.',
            'It lands among the prepared, who at least were not surprised.',
            'The warning held. The rest gave way.',
            'Foreseen grief is still grief. The vale carries it looking at you with hard respect.',
            'The doom proves stronger than the shield and no stronger than the prophecy.',
            'It hits, and even in the wreckage they grant you this: you saw it true.',
            'The ward buckles. The trust, strangely, does not.'
        ],
        // knew plenty, said nothing, it landed
        'knew-quiet': [
            'You knew. You said nothing. That sits in the chest like a stone.',
            'You could have named the day and the door. You named neither. The silence has weight now.',
            'You held the vision like a coin and spent nothing. The vale paid instead.',
            'You knew enough. You chose the quiet. The quiet chooses to stay with you.',
            'The bones told you. You told no one. Somewhere a debt is entered in your name.',
            'It happened as you foresaw, to people you did not warn. Sleep will negotiate tonight.',
            'You watched it come from a long way off and let it arrive.',
            'The knowing was yours alone, and so is this.',
            'You kept the secret. The secret kept its appointment.',
            'A word from you might have mattered. The word stayed behind your teeth.',
            'You saw the thread pull tight and did not call out. The snap echoes.',
            'The candle showed you everything but never made you speak.',
            'You knew, and the vale finds out the hard way that you didn\'t say.  No — worse: they never find out at all.',
            'Foreknowledge, unshared, curdles into something you must carry.',
            'You had the warning in your hand and left it there.',
            'It came as no surprise — to you. To them it came as ruin.',
            'The vision was clear. Your throat was not. The stone in the chest grows a brother.',
            'You let them sleep through what you were awake to.',
            'Silence was easier. It is not easier now.',
            'You measured the doom, filed it, and said nothing to the people under it.',
            'The augur\'s burden: you rehearsed the warning and never gave the performance.',
            'What you knew and didn\'t say has moved in behind your ribs.',
            'You saw the wave. The vale learned of it by drowning.',
            'Your quiet cost them dear and you know the exact price.',
            'The bones did their work. You did not do yours.',
            'You knew the name, the day, the door. All three knock now from inside.',
            'A warning withheld is a wager. Tonight you lose it on their behalf.',
            'The vision came true unimpeded, as you allowed.',
            'You carry the only copy of the truth: that this was foreseen and unspoken.',
            'They will call it fate. You know its other name.',
            'You chose the chest-stone over the vigil. It is heavier than a vigil.',
            'The doom found them unwarned. Un-warned is a word with your mark on it.',
            'What almost had a chance died in your silence.',
            'You knew and the knowing helped no one. That was a choice.',
            'The quiet before the doom was yours to break. You kept it whole.',
            'It lands, and your first thought is: yes, that is how I saw it. The thought is no comfort.',
            'You were the early warning. You declined the position.',
            'The grief is theirs. The foreknowledge was yours. The arithmetic is ugly.',
            'You said nothing, and nothing is what stood between them and it.',
            'The stone in your chest has a name and a date, and you knew both in advance.'
        ],
        // building hit but standing — {name}
        'scarred': [
            '{name} is scarred, but stands.',
            '{name} takes the blow and stays on its feet.',
            '{name} is marked for it, but the roof still meets the walls.',
            '{name} shudders, sheds some shingles, and holds.',
            '{name} wears a new scar and the same stubborn posture.',
            '{name} is battered — bent, not broken.',
            '{name} loses some of its looks and none of its footing.',
            '{name} groans, settles, and decides to remain a building.',
            '{name} is hurt, but the door still opens in the morning.',
            '{name} carries the damage the way the vale carries winters.',
            '{name} stands, uglier and undefeated.',
            '{name} is chipped, charred at the edges, and still there at dawn.',
            '{name} takes it on the chin, architecturally speaking.',
            '{name} will need work. It will not need mourning.',
            '{name} is wounded; the walls hold a grudge and everything else.',
            '{name} sags a little and stands a lot.',
            '{name} survives with scars to show at the tavern, if buildings could.',
            '{name} keeps its feet like an old fighter — worse-looking, still in the ring.',
            '{name} is dented, not done.',
            '{name} comes through torn but true.',
            '{name} holds, though it will creak about this for years.',
            '{name} takes damage the carpenter will curse and the vale will forgive.',
            '{name} is roughed up and still righteous.',
            '{name} loses a corner and keeps its character.',
            '{name} stands scarred — proof against the worst of it.',
            '{name} is the worse for wear and the better for standing.',
            '{name} takes the hit; the foundations decline to be impressed.',
            '{name} is bruised timber and unbowed frame.',
            '{name} bleeds dust from new cracks, and stands in them.',
            '{name} gets a scar and a story; both will last.',
            '{name} is knocked about, not knocked down.',
            '{name} suffers, visibly. Falls, no.',
            '{name} stands with a new lean and an old spine.',
            '{name} is hurt where it shows and whole where it matters.',
            '{name} weathers it — barely, which still counts.',
            '{name} takes the doom\'s signature and refuses the rest.',
            '{name} is left standing amid its own splinters.',
            '{name} endures, needing paint and deserving praise.',
            '{name} holds the line at the cost of its good looks.',
            '{name} is scarred. Standing, though. Standing.'
        ],
        // ruined building restored — {name}
        'rebuilt': [
            '{name} stands again, smelling of new timber.',
            '{name} is raised anew, nails still bright.',
            '{name} stands again, sawdust in every corner and hope in the beams.',
            '{name} is whole once more; the vale argues over whether the roofline improved.',
            '{name} rises from its own ashes, tidier than it fell.',
            '{name} is rebuilt — the third-best barn-raising songs were sung.',
            '{name} stands again, its new door still stiff with pride.',
            '{name} is back, smelling of pitch and fresh-cut pine.',
            '{name} returns to the skyline, such as the skyline is.',
            '{name} is mended, beam by beam, grudge by grudge.',
            '{name} stands again. The old ruin is already becoming a story.',
            '{name} is restored; the first fire in its hearth draws a small crowd.',
            '{name} rises again, straighter than anyone remembered it.',
            '{name} is rebuilt, and someone has carved the date in a corner post.',
            '{name} stands anew, still settling into its own weight.',
            '{name} is back on its feet, shingles gleaming like new coin.',
            '{name} is raised again by many hands and one long argument about joists.',
            '{name} returns, and the vale pretends it was never gone.',
            '{name} stands again, fresh thatch bright as a haircut.',
            '{name} is whole; the smell of new wood follows people home.',
            '{name} is rebuilt at last — the ladder may finally come down.',
            '{name} stands again, and the goat has already tested the new fence.',
            '{name} rises rebuilt, mortar still damp, spirits already dry.',
            '{name} is up again, defiant in fresh paint.',
            '{name} stands anew; its old key, absurdly, still fits.',
            '{name} is restored to the vale, with fewer drafts and more opinions about it.',
            '{name} rises again, hammered back into the world.',
            '{name} is rebuilt — new bones, old soul.',
            '{name} stands again, first swallows already inspecting the eaves.',
            '{name} is raised whole; the ruin is officially outvoted.',
            '{name} returns, smelling of sap and second chances.',
            '{name} stands rebuilt, and the rain has nothing to say about it now.',
            '{name} is whole again; the vale exhales a breath it held for days.',
            '{name} is back, better nailed than before.',
            '{name} rises, and someone hangs a horseshoe over the new door immediately.',
            '{name} stands again, warm light in its windows by nightfall.',
            '{name} is rebuilt; the timber still remembers being trees.',
            '{name} is raised once more, square to the world.',
            '{name} stands again, new from sill to ridgepole.',
            '{name} is whole, and the vale is one roof richer again.'
        ],
        // rank-up coda: greater fame draws greater dooms
        'fame': [
            'Fame is a lamp: it draws grander moths.',
            'A taller reputation casts a longer shadow, and things hunt in shadows.',
            'Renown travels. So does word of what renown is worth breaking.',
            'The louder the name, the larger the wolves that learn it.',
            'Bigger bells call bigger storms.',
            'The vale\'s trust grows — and the dark, competitive as ever, takes notice.',
            'Every rung climbed is visible from further off. Not everything watching is kind.',
            'A famous augur is a lighthouse. Lighthouses are found by everything at sea.',
            'Glory has a scent, and the things that follow it have noses.',
            'The higher the perch, the more interesting you look to the sky.',
            'Word of your sight spreads. So does the ambition of what you\'ll be seeing.',
            'A great name is a great target, hung where fate can read it.',
            'The dark keeps a ledger of reputations and settles the largest first.',
            'More renown, more ruin lining up to be foretold.',
            'You are becoming known. Known is another word for findable.',
            'The bigger the legend, the heavier the dooms sent to test it.',
            'Grand titles attract grand troubles; it is nearly a law of weather.',
            'A brighter flame, a wider circle of singed and curious things.',
            'Your name carries further now — past the last farm, into the listening dark.',
            'Prestige is bait. You are now excellent bait.',
            'The vale looks up to you. Other things look down, and take aim.',
            'Fortune loves a rising star. So do the things that eat them.',
            'Each new honor is a drumbeat, and drums carry.',
            'Now even the far hills know your name. The far hills keep poor company.',
            'Greater sight, greater stakes. The loom weaves heavier thread for you now.',
            'The taller the tree, the more the storm considers it personally.',
            'Your legend grows teeth of its own — and attracts things with more.',
            'Acclaim is warm. Moths were only the beginning.',
            'The dark promotes you too, in its way.',
            'Every new admirer is matched, somewhere, by a new appetite.',
            'Renown rings like a bell in the deep places, and the deep places ring back.',
            'You are famous enough now to be worth a proper catastrophe.',
            'The bones whisper your name with more respect and more worry.',
            'Standing this tall, you make an excellent lightning argument.',
            'What is admired is measured; what is measured is tested.',
            'Your star rises — visible now to navigators of every intention.',
            'Bigger name, bolder dooms. The arithmetic of legend.',
            'Honor gathers around you, and trouble hates to miss a gathering.',
            'The vale sings of you. Some of what hears the song hums along, hungrily.',
            'A great augur draws great dooms, the way a steeple draws the storm.'
        ],
        // Turn Fate: the doom is pushed three days out, at a cost to the head
        'turn-fate': [
            'You reach into the loom and pull one thread three days looser. Your head rings with it.',
            'You lean on fate with both hands and buy three days. The price is paid in skull.',
            'Three days, wrenched from the weave. Somewhere behind your eyes, something files a complaint.',
            'You shove the doom three days down the road. The road shoves back, in your temples.',
            'The thread yields three days of slack. Your vision swims for the borrowing.',
            'You bend the calendar by three days. The calendar bends you back, slightly.',
            'Three more days, torn loose from the loom. Your ears will whistle till sundown.',
            'You put your shoulder to fate and move it three days. Fate leaves a bruise you can\'t see.',
            'The doom is rescheduled: three days hence. Your headache is very much today.',
            'You claw three days back from the dark. The dark takes its fee out of your skull.',
            'Fate gives ground — three days of it — and salts the ground behind your eyes.',
            'You untie a knot three days tighter than your fingers. Your hands shake after.',
            'Three days won. The inside of your head sounds like a struck bell.',
            'You haggle with the weave and get three days. The weave rounds up its price, in migraine.',
            'The thread slides three days through your grip, burning all the way.',
            'You push the appointed day three squares down the calendar. Something in your skull objects formally.',
            'Three days of grace, pulled like a tooth — and about as gently.',
            'You wrestle the doom three days backward. Best two falls of three; you feel all three.',
            'The loom gives up three days with bad grace. Your nose may bleed. Fair trade.',
            'You reach past the veil and reset the date. The veil resets your equilibrium.',
            'Three days, prised loose from destiny. Destiny keeps your steadiness as deposit.',
            'You slow the coming doom by three days. The world hums off-key for hours.',
            'Fate is a heavy door. You drag it three days open and pay in vertigo.',
            'The doom\'s day slides back three. The pressure behind your eyes moves in the other direction.',
            'You bargain nothing — you simply take three days. The taking costs you your morning.',
            'Three stolen days. The loom marks you down as a known thief, and charges accordingly.',
            'You grip the future and twist, gently, three days\' worth. Your teeth ache with the torque.',
            'The weave stretches three days thinner. So, for a while, does your sense of up.',
            'You buy the vale three days with coin minted in your own skull.',
            'The thread gives three days before it locks. Your hands smell faintly of lightning.',
            'Three days pushed onto the doom\'s ledger. The interest is a ringing in your ears.',
            'You lever the appointed night three days off its hinge. The effort blurs the room.',
            'Fate concedes three days, muttering. Your head does the muttering for it.',
            'You drag the dark date three days further off. The dragging goes through your spine.',
            'Three days\' delay, pulled hand-over-hand from the loom. Your grip will remember.',
            'The doom is put off three days. Your body files this under "we will discuss this later".',
            'You spend something wordless and get three days back. The exchange rate is punishing.',
            'Three days looser. The world takes a moment to stop sounding underwater.',
            'You move the unmovable by exactly three days. It moves you back by one bad night.',
            'The loom surrenders three days. You surrender the rest of the afternoon.'
        ],
        // a day's labor — {n} supplies gained
        'work': [
            'A day\'s honest work. +{n} supplies.',
            'You put your back into the vale\'s business. +{n} supplies.',
            'Sweat now, soup later. +{n} supplies.',
            'The augur rolls up both sleeves. +{n} supplies.',
            'Plain work, plainly done. +{n} supplies.',
            'You trade an aching back for a fuller store. +{n} supplies.',
            'No visions today, just callouses. +{n} supplies.',
            'The bones rest; the hands do not. +{n} supplies.',
            'Honest toil, the kind with splinters. +{n} supplies.',
            'You work like someone who eats. +{n} supplies.',
            'A day spent on earthly matters, profitably. +{n} supplies.',
            'The future can wait; the woodpile couldn\'t. +{n} supplies.',
            'You lend the vale your hands for a day. +{n} supplies.',
            'Muscle over mysticism, for one day. +{n} supplies.',
            'The stores grow by the width of your effort. +{n} supplies.',
            'You haul, stack, mend, and repeat. +{n} supplies.',
            'A day of good plain graft. +{n} supplies.',
            'Even seers must fill the pantry. +{n} supplies.',
            'You earn your keep the old way. +{n} supplies.',
            'Work done, larder heavier. +{n} supplies.',
            'The vale\'s chores meet the vale\'s augur. Chores lose. +{n} supplies.',
            'You spend the day usefully un-mystical. +{n} supplies.',
            'Hands dirty, conscience clean. +{n} supplies.',
            'A long day measured in sacks and stacks. +{n} supplies.',
            'You sweat like a prophecy of rain. +{n} supplies.',
            'Nothing foretold, plenty stored. +{n} supplies.',
            'The day is spent; the stores are not. +{n} supplies.',
            'You do the work that keeps winters survivable. +{n} supplies.',
            'One day of labor, banked against dark days. +{n} supplies.',
            'The augur proves surprisingly good with a barrow. +{n} supplies.',
            'You keep busy the mortal way. +{n} supplies.',
            'Grain moved, wood split, virtue accumulated. +{n} supplies.',
            'A workmanlike day, no omens attached. +{n} supplies.',
            'You add your sweat to the vale\'s savings. +{n} supplies.',
            'The stores thank you in their quiet way. +{n} supplies.',
            'Day given, provisions gotten. +{n} supplies.',
            'You labor while the loom minds itself. +{n} supplies.',
            'Simple work, honest arithmetic. +{n} supplies.',
            'The pantry grows an inch prouder. +{n} supplies.',
            'You finish the day tired in the good way. +{n} supplies.'
        ],
        // coda after a villager is lost
        'memorial': [
            'A stone is raised by the chapel.',
            'A new stone joins the quiet row by the chapel.',
            'The chapel bell tolls once for each year of them.',
            'The vale digs, and grieves, and plants a stone.',
            'By the chapel, a fresh-cut stone learns their name.',
            'A stone is set, and flowers appear on it before anyone is asked.',
            'The chapel yard grows by one small, heavy addition.',
            'Their name is given to stone for safekeeping.',
            'A marker rises by the chapel wall, facing the morning.',
            'The vale walks slowly behind them one last time.',
            'A stone is raised; the mason works with his hat off.',
            'By nightfall there is a stone, and someone sitting with it.',
            'The chapel keeps one more name now, in its stone ledger.',
            'A grave is tended into being with unbearable care.',
            'The vale gives them back to the hill, with a stone to mark the lending.',
            'One more stone stands watch in the chapel yard.',
            'Their place at table becomes a place by the wall.',
            'A stone is raised, plain and true, like they were.',
            'The bell speaks their name in the only language it has.',
            'Earth is opened, closed, and crowned with stone.',
            'The chapel yard accepts one more of the vale\'s own.',
            'A stone goes up; the carver adds a swallow, unasked.',
            'They are laid down gently, under new-cut letters.',
            'The vale writes their name in stone, having no safer place.',
            'A marker is raised, and the grass is left to grow soft around it.',
            'The row by the chapel is one stone longer tonight.',
            'Stone takes the weight the vale cannot carry.',
            'A grave by the chapel, dug by friends, which is the worst way and the best.',
            'Their name outlives the night, chiseled deep.',
            'The chapel shadow falls on one more stone at evening.',
            'A stone is set upright, the way they lived.',
            'The vale plants its grief by the chapel and waters it often.',
            'One stone more. The hill holds them all without complaint.',
            'They are given stone, silence, and every hat in the vale held to chest.',
            'The mason cuts the dates and hates the second one.',
            'A stone rises where they rest, patient as they never were.',
            'The chapel yard makes room, as it always does, sorrowfully.',
            'Their stone joins the others, and the others seem to make it welcome.',
            'A last bed is made and a stone stands guard over it.',
            'The vale raises a stone, which is how it says what it cannot.'
        ],
        // session-start line, after "Day N."
        'day-dawn': [
            'The vale is quiet. You know better.',
            'Morning arrives, acting innocent.',
            'The sun comes up as if nothing were owed.',
            'A peaceful dawn. You take attendance of the shadows anyway.',
            'The vale wakes easy. You wake counting.',
            'Cocks crow, kettles sing, and the loom hums beneath it all.',
            'The morning is calm the way deep water is calm.',
            'Dew on the fields, dread in the tea leaves. An ordinary day.',
            'The vale stretches and yawns. You check the bones first.',
            'Dawn, bright and punctual. Dooms are punctual too.',
            'A soft morning. You trust it about half an inch.',
            'The day begins politely. They often do, before.',
            'Smoke rises straight from every chimney. You watch it for hints.',
            'The vale opens its shutters. You have been up for hours.',
            'Morning light on the hills, and the candle already lit against evening.',
            'The birds are loud and uninformed. It must be nice.',
            'Another day steps in, wiping its boots and hiding its hands.',
            'The vale goes about its breakfast. You go about the omens.',
            'Quiet lanes, warm bread, and the future breathing down the week.',
            'It looks like a day when nothing will happen. So did the other ones.',
            'Sunrise pays its usual visit. You read its expression carefully.',
            'The morning makes no promises. Wise of it.',
            'The vale is calm; the calm, as usual, is on loan.',
            'A new day, unopened. You shake it gently first, listening.',
            'The kettle whistles. Somewhere far off, so does something else.',
            'The day starts clean. Days rarely finish that way.',
            'All quiet along the hedgerows. You keep your boots by the door.',
            'Morning again. The loom worked the night shift; you check its output.',
            'The vale believes in this fine weather. You take it under advisement.',
            'A well-behaved dawn. You have met well-behaved dawns before.',
            'The village wakes to birdsong. You woke to something less melodic.',
            'The light comes up slow and gold, hiding nothing. Almost nothing.',
            'The day introduces itself pleasantly. You note the exits.',
            'Bread bakes, hens fuss, fate files its paperwork unseen.',
            'The morning is honest as far as it goes. It never goes far enough.',
            'You greet the dawn the professional way: suspiciously.',
            'The vale hums its small songs. You listen underneath them.',
            'Sunlight strolls in over the hills, whistling, hands in its pockets.',
            'A gentle start. The candle stays lit regardless.',
            'The day opens like a door. You watch what comes through.'
        ]
    };

    function fill(text, vars) {
        return text.replace(/\{(\w+)\}/g, (m, k) => vars?.[k] ?? m);
    }

    // A fresh random line each call, drawn through Rando so seeded runs reproduce.
    function pick(key, vars) {
        return fill(Rando.choice(TABLES[key]), vars);
    }

    // A line keyed to an id, for UI text that re-renders — same seed, same line.
    function stable(key, seed, vars) {
        const table = TABLES[key];
        return fill(table[seed % table.length], vars);
    }

    return { pick, stable };
})();
